package main

import (
	"bytes"
	_ "embed"
	"encoding/json"
	"fmt"
	"strings"
)

//go:embed guest/main.go.txt
var wrapper []byte

//go:embed driver.go
var driverSource []byte

const CheckID = "wp3codec-canonical-v0"
const InvocationID = "wp3codec-wasip1-go1.27-v0"

type vector struct {
	Name, Op string
	Input    []byte
	Output   []byte
	Rejected bool
}
type request struct {
	Op    string
	Input []byte
}
type answer struct {
	Output   []byte
	Rejected bool
}

// Expectations are independently authored from CF-V0-019, never generated by the candidate.
func vectors() []vector {
	return []vector{
		{"escape", "encode", []byte(`"a\n\t\u0000/é"`), []byte(`"a\u000a\u0009\u0000/é"`), false},
		{"utf8-key-order", "encode", []byte(`{"é":null,"a":true,"Z":false,"A":[]}`), []byte(`{"A":[],"Z":false,"a":true,"é":null}`), false},
		{"canonical", "verify", []byte(`{"a":[true,false,null,"1"]}`), nil, false},
		{"whitespace", "verify", []byte(` {"a":null}`), nil, true},
		{"terminal-lf", "verify", []byte("null\n"), nil, true},
		{"scalar-number", "encode", []byte(`1`), nil, true},
		{"surrogate", "encode", []byte(`"\ud800"`), nil, true},
		{"invalid-utf8", "encode", []byte{'"', 0xff, '"'}, nil, true},
		{"duplicate-key", "encode", []byte(`{"a":null,"a":true}`), nil, true},
		{"depth", "encode", []byte(strings.Repeat("[", 65) + "null" + strings.Repeat("]", 65)), nil, true},
	}
}
func driverInput() []byte {
	rows := []request{}
	for _, v := range vectors() {
		rows = append(rows, request{v.Op, v.Input})
	}
	b, _ := json.Marshal(rows)
	return b
}

// TestCanonicalOutput is the protected driver assertion unit. Guest bytes are answers, never verdicts.
func TestCanonicalOutput(data []byte) error {
	var got []answer
	d := json.NewDecoder(bytes.NewReader(data))
	d.DisallowUnknownFields()
	if err := d.Decode(&got); err != nil {
		return fmt.Errorf("answer framing: %w", err)
	}
	if !bytes.Equal(data, mustJSONLine(got)) {
		return fmt.Errorf("noncanonical answer framing")
	}
	groups := []struct {
		name  string
		cases []vector
	}{{name: "PLE-V0-005 canonical vectors", cases: vectors()}}
	ordinal := 0
	for _, group := range groups {
		for _, v := range group.cases {
			if ordinal >= len(got) {
				return fmt.Errorf("%s: missing answer", group.name)
			}
			actual := got[ordinal]
			ordinal++
			if actual.Rejected != v.Rejected || !bytes.Equal(actual.Output, v.Output) {
				return fmt.Errorf("%s assertion failed: %s", group.name, v.Name)
			}
		}
	}
	if ordinal != len(got) {
		return fmt.Errorf("extra answers")
	}
	return nil
}
func mustJSONLine(v any) []byte { b, _ := json.Marshal(v); return append(b, '\n') }
