package main

import (
	"bytes"
	"compress/zlib"
	"context"
	"encoding/hex"
	"io"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"testing"

	"github.com/Beamfall/corvint/internal/authoritystore"
	"github.com/Beamfall/corvint/internal/cem/gitauth"
	"github.com/Beamfall/corvint/internal/cem/gitrun"
	"github.com/Beamfall/corvint/internal/localauthority"
)

func TestEvidenceFilesDeterministicallyBindEveryGeneratedByte(t *testing.T) {
	for _, wide := range []bool{false, true} {
		t.Run(strconv.FormatBool(wide), func(t *testing.T) {
			blob := closureObject("blob", []byte("content"), wide)
			tree := closureTree("file", "100644", blob, wide)
			commit := closureCommit(tree, "same", wide)
			original := capsule{"corvint-source-capsule/0", []capsuleObject{blob, tree, commit}}
			c, _, err := completeCapsule(original, commit.OID, commit.OID, tree.OID)
			if err != nil {
				t.Fatal(err)
			}
			in := enrolledInput{root: authoritystore.RootDocument{RootID: "unit-only", Epoch: "1", Generation: "1", AuthorityGID: "600"}, enrollment: localauthority.Enrollment{Binding: localauthority.Binding{Base: commit.OID, Target: commit.OID, Tree: tree.OID}}, raw: map[string][]byte{"objects.json": mustJSONLine(original)}, capsule: c}
			handle := digest([]byte("fixture"))
			m, files, err := evidenceFiles(in, handle)
			if err != nil {
				t.Fatal(err)
			}
			again, againFiles, err := evidenceFiles(in, handle)
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(mustJSONLine(m), mustJSONLine(again)) {
				t.Fatal("manifest nondeterministic")
			}
			objects := map[string][]byte{}
			for _, o := range c.Objects {
				objects[o.OID] = o.Data
			}
			for _, f := range m.Files {
				raw := files[f.Path]
				if !bytes.Equal(raw, againFiles[f.Path]) || digest(raw) != f.SHA256 || strconv.Itoa(len(raw)) != f.Size {
					t.Fatal("generated byte binding")
				}
				if f.OID != "" {
					reader, err := zlib.NewReader(bytes.NewReader(raw))
					if err != nil {
						t.Fatal(err)
					}
					decoded, err := io.ReadAll(reader)
					reader.Close()
					if err != nil || !bytes.Equal(decoded, objects[f.OID]) {
						t.Fatal("object representation changed")
					}
				}
			}
			if m.CapsuleSHA256 != digest(in.raw["objects.json"]) || m.EnrollmentHandle != handle || m.ReaderGID != "600" {
				t.Fatal("publication binding")
			}
		})
	}
}

func TestMinimalPublishedViewRunsFrozenGitWithoutUnchangedBlobsOrHistory(t *testing.T) {
	for _, wide := range []bool{false, true} {
		t.Run(strconv.FormatBool(wide), func(t *testing.T) {
			old := closureObject("blob", []byte("old\n"), wide)
			next := closureObject("blob", []byte("new\n"), wide)
			unchanged := closureObject("blob", []byte("not supplied\n"), wide)
			entry := func(name string, object capsuleObject) []byte {
				oid, _ := hex.DecodeString(object.OID)
				return append([]byte("100644 "+name+"\x00"), oid...)
			}
			oldTree := closureObject("tree", append(entry("changed", old), entry("stable", unchanged)...), wide)
			newTree := closureObject("tree", append(entry("changed", next), entry("stable", unchanged)...), wide)
			base := closureCommit(oldTree, "base", wide)
			target := closureCommit(newTree, "target", wide)
			original := capsule{"corvint-source-capsule/0", []capsuleObject{old, next, oldTree, newTree, base, target}}
			c, _, err := completeCapsule(original, base.OID, target.OID, newTree.OID)
			if err != nil {
				t.Fatal(err)
			}
			in := enrolledInput{root: authoritystore.RootDocument{RootID: "unit-only", Epoch: "1", Generation: "1", AuthorityGID: "600"}, enrollment: localauthority.Enrollment{Binding: localauthority.Binding{Base: base.OID, Target: target.OID, Tree: newTree.OID}}, raw: map[string][]byte{"objects.json": mustJSONLine(original)}, capsule: c}
			_, files, err := evidenceFiles(in, digest([]byte("fixture")))
			if err != nil {
				t.Fatal(err)
			}
			root := t.TempDir()
			if err := os.MkdirAll(filepath.Join(root, ".git/refs"), 0700); err != nil {
				t.Fatal(err)
			}
			for path, raw := range files {
				p := filepath.Join(root, path)
				if err := os.MkdirAll(filepath.Dir(p), 0700); err != nil {
					t.Fatal(err)
				}
				if err := os.WriteFile(p, raw, 0600); err != nil {
					t.Fatal(err)
				}
			}
			repo, err := gitauth.Open(root, gitrun.NewDefaultBudget())
			if err != nil {
				t.Fatal(err)
			}
			patch, err := repo.CanonicalDiff(context.Background(), base.OID, target.OID)
			if err != nil || !bytes.Contains(patch, []byte("-old\n+new\n")) {
				t.Fatalf("minimal view diff: %s %v", patch, err)
			}
			if _, err := repo.BlobBytes(context.Background(), unchanged.OID); err == nil {
				t.Fatal("unsupplied blob unexpectedly readable")
			}
		})
	}
}

func TestEvidenceStagePermissionsAndFailureCleanup(t *testing.T) {
	if runtime.GOOS != "darwin" {
		t.Skip("Darwin publication profile")
	}
	parent := t.TempDir()
	stage, err := os.MkdirTemp(parent, ".pending-")
	if err != nil {
		t.Fatal(err)
	}
	raw := []byte("fixture")
	manifest := authoritystore.EvidenceManifest{Files: []authoritystore.EvidenceFile{{Path: ".git/HEAD"}}}
	held, err := os.Open(stage)
	if err != nil {
		t.Fatal(err)
	}
	defer held.Close()
	if err := writeEvidenceStageFD(held, manifest, map[string][]byte{".git/HEAD": raw}, raw, uint32(os.Getuid()), uint32(os.Getgid())); err != nil {
		t.Fatal(err)
	}
	if err := filepath.WalkDir(stage, func(p string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		info, err := d.Info()
		if err != nil {
			return err
		}
		mode := os.FileMode(0440)
		if d.IsDir() {
			mode = 0550
		}
		if info.Mode().Perm() != mode {
			t.Fatalf("%s mode %o", p, info.Mode().Perm())
		}
		return nil
	}); err != nil {
		t.Fatal(err)
	}
	// A failure before the audited rename leaves no active publication. The same
	// deferred cleanup used by publishEvidence removes readonly stage directories.
	if err := removeEvidenceStageFD(held); err != nil {
		t.Fatal(err)
	}
	if err := os.Remove(stage); err != nil {
		t.Fatal(err)
	}
	entries, err := os.ReadDir(parent)
	if err != nil || len(entries) != 0 {
		t.Fatalf("stage survived: %v %v", entries, err)
	}
}
