import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,writeFile,readFile,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { createRunner,validEnvelope,decodeEnvelope } from './runtime.js';
const good={profile:'corvint-pi-adapter/0',event:'stop',host:'pi',surface:'extension',hostVersion:'0.85.1',adapterVersion:'0.1.0',support:'FALLBACK',receiptId:'harness-receipt:sha256:'+'a'.repeat(64),context:'',degradations:['frontier-authority-unavailable'],fault:null,shouldContinue:false};
test('AHI-024 Pi closed envelope rejects forged identity and continuation',()=>{assert.equal(validEnvelope(good,'stop'),true);for(const delta of [{host:'codex'},{hostVersion:null},{shouldContinue:true},{extra:1},{receiptId:'fake'},{degradations:['unknown']},{fault:'unknown'}])assert.equal(validEnvelope({...good,...delta},'stop'),false);});
test('AHI-024 Pi config conflicts refuse before child effects; explicit option wins',async()=>{let calls=0;const spawnImpl=()=>{calls++;throw Error('marker')};const a=createRunner({env:{CORVINT_BIN:''},spawnImpl});assert.equal((await a.run({event:'stop',input:{}})).fault,'invalid-binary-config');assert.equal(calls,0);const b=createRunner({binary:'/explicit',env:{CORVINT_BIN:''},spawnImpl});assert.equal((await b.run({event:'stop',input:{}})).fault,'missing-binary');assert.equal(calls,1);});
test('AHI-024 Pi kills TERM-ignoring grandchild after leader closes',async()=>{const root=await mkdtemp(path.join(tmpdir(),'pi-cleanup-'));let pid;try{const script=path.join(root,'child');await writeFile(script,`#!/bin/sh\ntrap 'exit 0' TERM\n/bin/sh -c 'trap "" TERM; echo $$ > "${root}/pid"; while :; do sleep 1; done' &\nwait\n`,{mode:0o755});const abort=new AbortController();const runner=createRunner({binary:script});const work=runner.run({cwd:root,event:'stop',input:{},hostVersion:'0.85.1',signal:abort.signal});for(let n=0;n<100;n++){try{pid=Number(await readFile(path.join(root,'pid'),'utf8'));break}catch{await new Promise(r=>setTimeout(r,10))}}assert.ok(pid);abort.abort();assert.equal((await work).fault,'aborted');await runner.close();assert.throws(()=>process.kill(pid,0),{code:'ESRCH'});}finally{if(pid)try{process.kill(pid,'SIGKILL')}catch{}await rm(root,{recursive:true,force:true});}});

test('AHI-024 Pi duplicate output identity is refused before shape decoding',()=>{const raw=JSON.stringify(good);assert.throws(()=>decodeEnvelope(raw.replace('{','{"host":"forged",')));assert.deepEqual(decodeEnvelope(raw),good);});
