package delta

import (
	"context"
	json "encoding/json/v2"
	"fmt"
	"github.com/Beamfall/corvint/internal/flowdocs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDeltaEmptyChangeBindsPrevious(t *testing.T) {
	t.Run("DLT-V0-004 bound baseline validity", testDeltaEmptyChangeBindsPrevious)
}
func testDeltaEmptyChangeBindsPrevious(t *testing.T) {
	root, base, head := fixtureMerge(t)
	ctx := context.Background()
	gen, err := flowdocs.Generate(ctx, root, flowdocs.Options{Revision: head, Scope: "web"})
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := flowdocs.Encode(gen.Manifest)
	good := filepath.Join(t.TempDir(), "prior.json")
	os.WriteFile(good, raw, 0600)
	for _, kind := range []string{"valid", "missing", "malformed", "wrong-revision"} {
		t.Run(kind, func(t *testing.T) {
			name := good
			switch kind {
			case "missing":
				name += "-missing"
			case "malformed":
				name = filepath.Join(t.TempDir(), "bad")
				os.WriteFile(name, []byte("{"), 0600)
			case "wrong-revision":
				name = filepath.Join(t.TempDir(), "wrong")
				os.WriteFile(name, []byte(strings.ReplaceAll(string(raw), head, base)), 0600)
			}
			r, err := Compile(ctx, root, Options{Base: head, Head: head, Build: "163", PreviousGeneration: name})
			if err != nil {
				t.Fatal(err)
			}
			if kind == "valid" {
				if len(r.InputDigests) != 1 || hasUnknown(r, "documentation-baseline-invalid") {
					t.Fatalf("valid missing binding %+v", r)
				}
			} else {
				if !hasUnknown(r, "documentation-baseline-invalid") {
					t.Fatalf("invalid ignored %+v", r)
				}
				if kind != "missing" && len(r.InputDigests) != 1 {
					t.Fatal("captured invalid input unbound")
				}
			}
		})
	}
}
func TestDeltaDocumentationExclusionsAndHTML(t *testing.T) {
	t.Run("DLT-V0-004 documentation exclusions stay incomplete", testDeltaDocumentationExclusionsAndHTML)
}
func testDeltaDocumentationExclusionsAndHTML(t *testing.T) {
	for _, kind := range []string{"oversize-js", "generated-js", "unsupported-go", "html-base", "html-head"} {
		t.Run(kind, func(t *testing.T) {
			root, base, _ := fixtureMerge(t)
			p := "web/excluded.js"
			body := "// Code generated by test; DO NOT EDIT.\nexport function excluded() {}\n"
			switch kind {
			case "oversize-js":
				body = "export function excluded() {}\n" + strings.Repeat(" ", 1_000_001)
			case "unsupported-go":
				p = "unsupported/a.go"
				body = "package a\nfunc A(){}\n"
			case "html-base", "html-head":
				p = "web/template.html"
				body = strings.Repeat("x", (4<<20)+1)
			}
			put(t, root, p, body)
			git(t, root, "add", ".")
			git(t, root, "commit", "-qm", "excluded")
			head := git(t, root, "rev-parse", "HEAD")
			if kind == "html-base" {
				base = head
				os.Remove(filepath.Join(root, p))
				git(t, root, "add", ".")
				git(t, root, "commit", "-qm", "remove html")
				head = git(t, root, "rev-parse", "HEAD")
			}
			r, err := Compile(context.Background(), root, Options{Base: base, Head: head, Build: "163"})
			if err != nil {
				t.Fatal(err)
			}
			if !hasUnknown(r, "documentation-incomplete") || !r.RunFullSuite {
				t.Fatalf("exclusion disappeared %+v", r)
			}
		})
	}
}
func TestDeltaReachedUnitDenominatorIncludesDiamond(t *testing.T) {
	t.Run("DLT-V0-006 affected unit denominator", testDeltaReachedUnitDenominatorIncludesDiamond)
}
func testDeltaReachedUnitDenominatorIncludesDiamond(t *testing.T) {
	root, _, _ := fixtureMerge(t)
	for p, body := range map[string]string{"a/a.go": "package a\nfunc A(){}\n", "b/b.go": "package b\nimport \"example.invalid/demo/a\"\nfunc B(){a.A()}\n", "c/c.go": "package c\nimport \"example.invalid/demo/a\"\nfunc C(){a.A()}\n", "d/d.go": "package d\nimport (\"example.invalid/demo/b\";\"example.invalid/demo/c\")\nfunc D(){b.B();c.C()}\n", "d/d_test.go": "package d\nimport \"testing\"\nfunc TestD(t *testing.T){D()}\n"} {
		put(t, root, p, body)
	}
	git(t, root, "add", ".")
	git(t, root, "commit", "-qm", "diamond")
	base := git(t, root, "rev-parse", "HEAD")
	put(t, root, "a/a.go", "package a\nfunc A(){println(1)}\n")
	git(t, root, "add", ".")
	git(t, root, "commit", "-qm", "change a")
	head := git(t, root, "rev-parse", "HEAD")
	r, err := Compile(context.Background(), root, Options{Base: base, Head: head, Build: "163"})
	if err != nil {
		t.Fatal(err)
	}
	if r.Denominators.AffectedUnits != 4 {
		t.Fatalf("diamond denominator %d", r.Denominators.AffectedUnits)
	}
	n := 0
	for _, g := range r.Gaps {
		if g.Denominator == "affected-units" {
			n++
		}
	}
	if n != 4 {
		t.Fatalf("missing diamond gaps: %d", n)
	}
}

func TestDeltaUnknownsSurviveObservationLimit_DLT_V0_009(t *testing.T) {
	t.Run("DLT-V0-009 display limits preserve uncertainty and decision", func(t *testing.T) {
		for _, kind := range []string{"tests", "documentation"} {
			t.Run(kind, func(t *testing.T) {
				r := Record{
					Schema: Schema, Base: strings.Repeat("1", 40), Head: strings.Repeat("2", 40), Tree: strings.Repeat("3", 40), Build: "test",
					ChangedPathDigest: digest("paths", []byte("docs/guide.md")), ChangedPaths: []string{"docs/guide.md"},
					InputDigests: []string{}, Documentation: []Span{}, Tests: []Test{}, Gaps: []Gap{}, WorkKeys: []string{}, Unknowns: []Unknown{},
					MandatoryChecksRequired: true, Denominators: Denominators{Runtime: "unknown"},
				}
				r.unknown("provider-coverage-missing", 2, []byte("before display limit"))
				before := r.Unknowns[0]
				for i := 0; i < MaxObservations+3; i++ {
					path := fmt.Sprintf("pkg/check_%04d.go", i)
					if kind == "tests" {
						r.addTest(Test{Path: path, Repository: digest("repository", []byte("root")), Unit: digest("unit", []byte(path)), Origin: "in-repository", Confidence: "unscored"})
					} else {
						path = fmt.Sprintf("docs/span-%04d.md", i)
						r.addSpan(Span{ID: digest("span", []byte(path)), Path: path, State: "added", Digest: digest("body", []byte(path))})
					}
				}
				if !r.RunFullSuite || !hasUnknown(r, "observation-bound-exceeded") {
					t.Fatalf("display limit did not retain its full-suite uncertainty: %+v", r.Unknowns)
				}
				if kind == "tests" && len(r.Tests) != MaxObservations || kind == "documentation" && len(r.Documentation) != MaxObservations {
					t.Fatalf("display limit: tests=%d documentation=%d", len(r.Tests), len(r.Documentation))
				}
				r.unknown("provider-capture-unavailable", 3, []byte("after display limit"))
				after := r.Unknowns[len(r.Unknowns)-1]
				r.finalize()
				if r.Decision != "findings" || !r.RunFullSuite || r.Denominators.Complete || !r.MandatoryChecksRequired {
					t.Fatalf("display limit hid obligations: decision=%s full-suite=%v complete=%v mandatory=%v", r.Decision, r.RunFullSuite, r.Denominators.Complete, r.MandatoryChecksRequired)
				}
				if len(r.Unknowns) != 3 || r.Unknowns[0].Code != "observation-bound-exceeded" || r.Unknowns[0].Count != 3 || r.Unknowns[1] != after || r.Unknowns[2] != before {
					t.Fatalf("sorted uncertainty/counts/digests changed across limit: %+v", r.Unknowns)
				}
				raw, err := r.Canonical()
				if err != nil {
					t.Fatal(err)
				}
				var round Record
				if err := json.Unmarshal(raw, &round, json.RejectUnknownMembers(true)); err != nil {
					t.Fatal(err)
				}
				if len(round.Unknowns) != len(r.Unknowns) || round.Decision != "findings" || !round.RunFullSuite || round.Denominators.Complete {
					t.Fatal("canonical output lost bounded-record uncertainty or decision")
				}
				for i, unknown := range r.Unknowns {
					if round.Unknowns[i] != unknown {
						t.Fatalf("canonical output changed uncertainty %d: %+v", i, round.Unknowns[i])
					}
				}
			})
		}
	})
}

func TestDeltaGraphAboveDefaultGitBudget(t *testing.T) {
	t.Run("DLT-V0-002 immutable graph admits a tree above the default Git operation ceiling", testDeltaGraphAboveDefaultGitBudget)
}
func testDeltaGraphAboveDefaultGitBudget(t *testing.T) {
	root, _, _ := fixtureMerge(t)
	const packages, perPackage = 12, 100 // 1,200 Go sources: one blob read each exceeds 1,024
	for p := range packages {
		for f := range perPackage {
			put(t, root, fmt.Sprintf("wide/p%02d/f%03d.go", p, f), fmt.Sprintf("package p%02d\nfunc F%03d() {}\n", p, f))
		}
	}
	git(t, root, "add", ".")
	git(t, root, "commit", "-qm", "wide")
	base := git(t, root, "rev-parse", "HEAD")
	put(t, root, "wide/p00/f000.go", "package p00\nfunc F000() { println(1) }\n")
	git(t, root, "add", ".")
	git(t, root, "commit", "-qm", "change one")
	head := git(t, root, "rev-parse", "HEAD")
	r, err := Compile(context.Background(), root, Options{Base: base, Head: head, Build: "163"})
	if err != nil {
		t.Fatal(err)
	}
	if hasUnknown(r, "immutable-graph-unavailable") || r.Denominators.AffectedUnits == 0 {
		t.Fatalf("graph refused above default budget: units %d unknowns %+v", r.Denominators.AffectedUnits, r.Unknowns)
	}
}
