package delta

import (
	"context"
	"github.com/Beamfall/corvint/internal/flowdocs"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDeltaEmptyChangeBindsPrevious(t *testing.T) {
	t.Run("DLT-V0-004 bound baseline validity", testDeltaEmptyChangeBindsPrevious)
}
func testDeltaEmptyChangeBindsPrevious(t *testing.T) {
	root, base, head := fixtureMerge(t)
	ctx := context.Background()
	gen, err := flowdocs.Generate(ctx, root, flowdocs.Options{Revision: head, Scope: "web"})
	if err != nil {
		t.Fatal(err)
	}
	raw, _ := flowdocs.Encode(gen.Manifest)
	good := filepath.Join(t.TempDir(), "prior.json")
	os.WriteFile(good, raw, 0600)
	for _, kind := range []string{"valid", "missing", "malformed", "wrong-revision"} {
		t.Run(kind, func(t *testing.T) {
			name := good
			switch kind {
			case "missing":
				name += "-missing"
			case "malformed":
				name = filepath.Join(t.TempDir(), "bad")
				os.WriteFile(name, []byte("{"), 0600)
			case "wrong-revision":
				name = filepath.Join(t.TempDir(), "wrong")
				os.WriteFile(name, []byte(strings.ReplaceAll(string(raw), head, base)), 0600)
			}
			r, err := Compile(ctx, root, Options{Base: head, Head: head, Build: "163", PreviousGeneration: name})
			if err != nil {
				t.Fatal(err)
			}
			if kind == "valid" {
				if len(r.InputDigests) != 1 || hasUnknown(r, "documentation-baseline-invalid") {
					t.Fatalf("valid missing binding %+v", r)
				}
			} else {
				if !hasUnknown(r, "documentation-baseline-invalid") {
					t.Fatalf("invalid ignored %+v", r)
				}
				if kind != "missing" && len(r.InputDigests) != 1 {
					t.Fatal("captured invalid input unbound")
				}
			}
		})
	}
}
func TestDeltaDocumentationExclusionsAndHTML(t *testing.T) {
	t.Run("DLT-V0-004 documentation exclusions stay incomplete", testDeltaDocumentationExclusionsAndHTML)
}
func testDeltaDocumentationExclusionsAndHTML(t *testing.T) {
	for _, kind := range []string{"oversize-js", "generated-js", "unsupported-go", "html-base", "html-head"} {
		t.Run(kind, func(t *testing.T) {
			root, base, _ := fixtureMerge(t)
			p := "web/excluded.js"
			body := "// Code generated by test; DO NOT EDIT.\nexport function excluded() {}\n"
			switch kind {
			case "oversize-js":
				body = "export function excluded() {}\n" + strings.Repeat(" ", 1_000_001)
			case "unsupported-go":
				p = "unsupported/a.go"
				body = "package a\nfunc A(){}\n"
			case "html-base", "html-head":
				p = "web/template.html"
				body = strings.Repeat("x", (4<<20)+1)
			}
			put(t, root, p, body)
			git(t, root, "add", ".")
			git(t, root, "commit", "-qm", "excluded")
			head := git(t, root, "rev-parse", "HEAD")
			if kind == "html-base" {
				base = head
				os.Remove(filepath.Join(root, p))
				git(t, root, "add", ".")
				git(t, root, "commit", "-qm", "remove html")
				head = git(t, root, "rev-parse", "HEAD")
			}
			r, err := Compile(context.Background(), root, Options{Base: base, Head: head, Build: "163"})
			if err != nil {
				t.Fatal(err)
			}
			if !hasUnknown(r, "documentation-incomplete") || !r.RunFullSuite {
				t.Fatalf("exclusion disappeared %+v", r)
			}
		})
	}
}
func TestDeltaReachedUnitDenominatorIncludesDiamond(t *testing.T) {
	t.Run("DLT-V0-006 affected unit denominator", testDeltaReachedUnitDenominatorIncludesDiamond)
}
func testDeltaReachedUnitDenominatorIncludesDiamond(t *testing.T) {
	root, _, _ := fixtureMerge(t)
	for p, body := range map[string]string{"a/a.go": "package a\nfunc A(){}\n", "b/b.go": "package b\nimport \"example.invalid/demo/a\"\nfunc B(){a.A()}\n", "c/c.go": "package c\nimport \"example.invalid/demo/a\"\nfunc C(){a.A()}\n", "d/d.go": "package d\nimport (\"example.invalid/demo/b\";\"example.invalid/demo/c\")\nfunc D(){b.B();c.C()}\n", "d/d_test.go": "package d\nimport \"testing\"\nfunc TestD(t *testing.T){D()}\n"} {
		put(t, root, p, body)
	}
	git(t, root, "add", ".")
	git(t, root, "commit", "-qm", "diamond")
	base := git(t, root, "rev-parse", "HEAD")
	put(t, root, "a/a.go", "package a\nfunc A(){println(1)}\n")
	git(t, root, "add", ".")
	git(t, root, "commit", "-qm", "change a")
	head := git(t, root, "rev-parse", "HEAD")
	r, err := Compile(context.Background(), root, Options{Base: base, Head: head, Build: "163"})
	if err != nil {
		t.Fatal(err)
	}
	if r.Denominators.AffectedUnits != 4 {
		t.Fatalf("diamond denominator %d", r.Denominators.AffectedUnits)
	}
	n := 0
	for _, g := range r.Gaps {
		if g.Denominator == "affected-units" {
			n++
		}
	}
	if n != 4 {
		t.Fatalf("missing diamond gaps: %d", n)
	}
}
