package appflows

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/Beamfall/corvint/internal/doccorpus"
)

// Proven-documentation schemas (AFU-V1-030, AFU-V1-032).
const (
	DocClaimsSchema  = "flow-doc-claims/0"
	DocWaiversSchema = "flow-doc-waivers/0"
	DocCheckSchema   = "flow-doc-check/0"
)

// Claim states (AFU-V1-031).
const (
	ClaimProven       = "PROVEN"
	ClaimContradicted = "CONTRADICTED"
	ClaimStale        = "STALE"
	ClaimUnproven     = "UNPROVEN"
)

// The closed `flows docs --check` failure codes (AFU-V1-032, AFU-V1-033).
const (
	DocLostProven   = "claim-lost-proven"
	DocBytesDiffer  = "rendered-bytes-differ"
	DocUnknownClaim = "unknown-anchor"
	DocBadAnchor    = "invalid-anchor"
)

const (
	docUnanchoredRow = "unanchored-documents"
	docCoverageRule  = "a Markdown document under the docs root is unanchored when it carries no valid corvint-claim anchor comment"
	docLimitation    = "an anchor proves the named outcome, not the surrounding prose; unanchored text is UNPROVEN, never PROVEN"
	docPageHeader    = "<!-- Generated by corvint flows docs from flow intents and run evidence. Do not edit; regenerate. -->\n"
	maxDocFiles      = 512
	maxDocBytes      = 4 * MaxBytes
)

var (
	docAnchor       = regexp.MustCompile(`(?s)<!--\s*corvint-claim(.*?)-->`)
	docAnchorFields = regexp.MustCompile(`^\s+flow=(\S+)\s+variation=(\S+)\s+outcome=(\S+)\s*$`)
)

// DocOptions names the committed page, its claim sidecar, the optional hand-written docs root and the
// run evidence, all repository-relative except the evidence files, which are already read.
type DocOptions struct {
	Page, Claims, DocsRoot string
	Evidence               []TestRunEvidence
}

// DocClaims is the flow-doc-claims/0 sidecar: every rendered and anchored claim, sorted by ID.
type DocClaims struct {
	Schema string     `json:"schema"`
	Page   string     `json:"page"`
	Claims []DocClaim `json:"claims"`
}

// DocClaim is one claim: an outcome of a variation, stated on the page or in an anchored document.
type DocClaim struct {
	ID        string        `json:"id"`
	Source    string        `json:"source"`
	Flow      string        `json:"flow"`
	Variation string        `json:"variation"`
	Outcome   string        `json:"outcome"`
	Evidence  []DocEvidence `json:"evidence"`
	State     string        `json:"state"`
}

// DocEvidence identifies one required test key and project pair; run IDs are not claim identity.
type DocEvidence struct {
	TestKey string `json:"test_key"`
	Project string `json:"project,omitempty"`
}

// DocWaivers is the repository-owned flow-doc-waivers/0 file.
type DocWaivers struct {
	Schema  string      `json:"schema"`
	Waivers []DocWaiver `json:"waivers"`
}

// DocWaiver excuses one claim until its expiry date (YYYY-MM-DD, UTC), exclusive.
type DocWaiver struct {
	Claim    string `json:"claim"`
	Reason   string `json:"reason"`
	Reviewer string `json:"reviewer"`
	Expires  string `json:"expires"`
}

// DocCheck is the flow-doc-check/0 report of `flows docs --check`.
type DocCheck struct {
	Schema   string       `json:"schema"`
	Revision string       `json:"revision"`
	Status   string       `json:"status"`
	Failures []DocFailure `json:"failures"`
	Waived   []string     `json:"waived"`
	Coverage *DocCoverage `json:"coverage,omitempty"`
}

// DocFailure is one check failure with a closed code.
type DocFailure struct {
	Code   string `json:"code"`
	Claim  string `json:"claim,omitempty"`
	Path   string `json:"path,omitempty"`
	Line   int    `json:"line,omitempty"`
	Detail string `json:"detail"`
}

// DocCoverage is the single row listing unanchored documents under the docs root (AFU-V1-033).
type DocCoverage struct {
	Row         string   `json:"row"`
	Value       int      `json:"value"`
	Denominator int      `json:"denominator"`
	Revision    string   `json:"revision"`
	Rule        string   `json:"rule"`
	Limitation  string   `json:"limitation"`
	Paths       []string `json:"paths"`
}

// docBuild is one regeneration at HEAD: every claim, the anchor failures and the coverage row.
type docBuild struct {
	set      IntentSet
	claims   []DocClaim
	failures []DocFailure
	coverage *DocCoverage
	revision string
}

type docFile struct {
	path string
	raw  []byte
}

// RenderDocs regenerates the page and its sidecar from the committed intents and hand-written docs
// (AFU-V1-030). An anchor failure refuses the render (AFU-V1-033).
func RenderDocs(ctx context.Context, root string, set IntentSet, o DocOptions) ([]byte, []byte, error) {
	b, err := buildDocs(ctx, root, set, o)
	if err != nil {
		return nil, nil, err
	}
	if len(b.failures) != 0 {
		f := b.failures[0]
		return nil, nil, fmt.Errorf("%s at %s:%d: %s", f.Code, f.Path, f.Line, f.Detail)
	}
	return renderDocs(b, o)
}

// WriteDocs replaces the page and then the sidecar, each through a confined temporary file (AFU-V1-036).
func WriteDocs(root string, o DocOptions, page, claims []byte) error {
	if err := ReplaceConfined(root, o.Page, page); err != nil {
		return err
	}
	return ReplaceConfined(root, o.Claims, claims)
}

// CheckDocs compares the committed page and sidecar with regeneration at HEAD (AFU-V1-032). It reads
// only committed files, so it never mutates the repository; today is the UTC date YYYY-MM-DD.
func CheckDocs(ctx context.Context, root string, set IntentSet, o DocOptions, waiversPath, today string) (DocCheck, error) {
	b, err := buildDocs(ctx, root, set, o)
	if err != nil {
		return DocCheck{}, err
	}
	waivers, err := committedWaivers(ctx, root, b.revision, waiversPath)
	if err != nil {
		return DocCheck{}, err
	}
	committed, err := committedDocs(ctx, root, b.revision, o)
	if err != nil {
		return DocCheck{}, err
	}
	effective, lost, waived := applyWaivers(b.claims, committed.claims, waivers, today)
	b.claims = effective
	page, claims, err := renderDocs(b, o)
	if err != nil {
		return DocCheck{}, err
	}
	failures := append(lost, bytesFailure(o.Page, committed.page, page)...)
	failures = append(failures, bytesFailure(o.Claims, committed.sidecar, claims)...)
	failures = append(failures, b.failures...)
	report := DocCheck{Schema: DocCheckSchema, Revision: b.revision, Status: "pass", Failures: failures, Waived: waived, Coverage: b.coverage}
	if len(failures) != 0 {
		report.Status = "fail"
	}
	return report, nil
}

func buildDocs(ctx context.Context, root string, set IntentSet, o DocOptions) (docBuild, error) {
	if err := validDocOptions(o); err != nil {
		return docBuild{}, err
	}
	links, at, err := evaluateSet(ctx, root, set)
	if err != nil {
		return docBuild{}, err
	}
	b := docBuild{set: set, claims: docClaims(set, links, o.Evidence, at, o.Page), failures: []DocFailure{}, revision: at.commit}
	if o.DocsRoot == "" {
		return b, nil
	}
	docs, err := committedMarkdown(ctx, root, at.commit, o.DocsRoot, o.Page)
	if err != nil {
		return docBuild{}, err
	}
	anchored, failures, paths := anchorClaims(docs, b.claims)
	b.claims = append(b.claims, anchored...)
	b.failures = failures
	b.coverage = docCoverage(docs, paths, at.commit)
	return b, nil
}

func validDocOptions(o DocOptions) error {
	if !safePath(o.Page) || !safePath(o.Claims) || o.Page == "." || o.Claims == "." || o.Page == o.Claims {
		return errors.New("--page and --claims must be two different canonical repository-relative paths")
	}
	if o.DocsRoot != "" && (!safePath(o.DocsRoot) || o.DocsRoot == ".") {
		return errors.New("--docs-root must name a directory inside the repository root")
	}
	return nil
}

// docClaims derives one page claim per outcome of every variation, in intent order.
func docClaims(set IntentSet, links []EvaluatedLink, evidence []TestRunEvidence, at head, page string) []DocClaim {
	claims := []DocClaim{}
	for _, intent := range set.Flows {
		own := flowLinks(links, intent.FlowID)
		for _, v := range intent.Variations {
			pairs := variationEvidence(intent, v, own, evidence, at)
			for _, o := range v.Outcomes {
				claims = append(claims, DocClaim{ID: claimID(intent.FlowID, v.VariationID, o), Source: page, Flow: intent.FlowID, Variation: v.VariationID,
					Outcome: o, Evidence: evidenceIDs(pairs), State: claimState(pairs, own, v, o)})
			}
		}
	}
	return claims
}

func claimID(flow, variation, outcome string) string { return flow + "/" + variation + "/" + outcome }

func evidenceIDs(pairs []TestEvidence) []DocEvidence {
	ids := []DocEvidence{}
	for _, p := range pairs {
		ids = append(ids, DocEvidence{TestKey: p.TestKey, Project: p.Project})
	}
	return ids
}

// claimState applies AFU-V1-031 conservatively: failed or flaky evidence contradicts, a stale link or
// stale evidence is stale, and PROVEN needs a verified variation, a declared assertion link for the
// outcome and every declared link of the variation, its steps and the outcome reviewed.
func claimState(pairs []TestEvidence, links []EvaluatedLink, v FlowVariation, outcome string) string {
	members := append([]string{v.VariationID, outcome}, v.Steps...)
	relevant := slices.DeleteFunc(slices.Clone(links), func(l EvaluatedLink) bool { return !slices.Contains(members, l.From) })
	switch {
	case slices.ContainsFunc(pairs, func(e TestEvidence) bool { return e.State == "failed" || e.State == "flaky" }):
		return ClaimContradicted
	case slices.ContainsFunc(relevant, func(l EvaluatedLink) bool { return l.ReviewState == ReviewStale }):
		return ClaimStale
	case slices.ContainsFunc(pairs, func(e TestEvidence) bool { return e.State == "stale" }):
		return ClaimStale
	case len(pairs) == 0 || slices.ContainsFunc(pairs, func(e TestEvidence) bool { return e.State != "verified" }):
		return ClaimUnproven
	case len(declaredTargets(links, "assertion", outcome)) == 0:
		return ClaimUnproven
	case slices.ContainsFunc(relevant, func(l EvaluatedLink) bool { return l.ReviewState != ReviewReviewed && l.ReviewState != ReviewInferred }):
		return ClaimUnproven
	}
	return ClaimProven
}

// committedMarkdown reads every Markdown file under dir at rev except the page, bounding the count
// and the recorded sizes before any read (AFU-V1-037).
func committedMarkdown(ctx context.Context, root, rev, dir, page string) ([]docFile, error) {
	entries, err := docTree(ctx, root, rev, dir+"/")
	if err != nil {
		return nil, err
	}
	if len(entries) == 0 {
		return nil, fmt.Errorf("docs root %s is absent at the evaluated revision", dir)
	}
	markdown := slices.DeleteFunc(entries, func(e treeEntry) bool { return e.name == page || !strings.HasSuffix(strings.ToLower(e.name), ".md") })
	if err = docBound(markdown); err != nil {
		return nil, err
	}
	docs := []docFile{}
	for _, e := range markdown {
		raw, err := committedBlob(ctx, root, e)
		if err != nil {
			return nil, err
		}
		docs = append(docs, docFile{path: e.name, raw: raw})
	}
	return docs, nil
}

func docBound(entries []treeEntry) error {
	if len(entries) > maxDocFiles {
		return fmt.Errorf("docs root exceeds %d Markdown documents", maxDocFiles)
	}
	total := 0
	for _, e := range entries {
		size, _ := strconv.Atoi(e.size)
		total += size
	}
	if total > maxDocBytes {
		return errors.New("docs root exceeds its byte bound")
	}
	return nil
}

// docTree lists the committed entries under a pathspec at rev with their full repository paths.
func docTree(ctx context.Context, root, rev, pathspec string) ([]treeEntry, error) {
	out, err := git(ctx, root, "--literal-pathspecs", "ls-tree", "-r", "-z", "-l", "--full-tree", rev, "--", pathspec)
	if err != nil {
		return nil, errors.New("committed documentation unreadable at the evaluated revision")
	}
	entries := []treeEntry{}
	for line := range bytes.SplitSeq(bytes.TrimSuffix(out, []byte{0}), []byte{0}) {
		if len(line) == 0 {
			continue
		}
		meta, name, _ := strings.Cut(string(line), "\t")
		fields := strings.Fields(meta)
		if len(fields) != 4 {
			return nil, errors.New("committed documentation unreadable at the evaluated revision")
		}
		entries = append(entries, treeEntry{name: name, mode: fields[0], kind: fields[1], oid: fields[2], size: fields[3]})
	}
	return entries, nil
}

// anchorClaims turns each valid anchor into a claim with the rendered claim's evidence and state, and
// reports malformed or unknown anchors. It returns the unanchored document paths.
func anchorClaims(docs []docFile, claims []DocClaim) ([]DocClaim, []DocFailure, []string) {
	known := map[string]DocClaim{}
	for _, c := range claims {
		known[c.ID] = c
	}
	anchored, failures, unanchored := []DocClaim{}, []DocFailure{}, []string{}
	for _, d := range docs {
		own, bad := documentAnchors(d, known)
		anchored = append(anchored, own...)
		failures = append(failures, bad...)
		if len(own) == 0 {
			unanchored = append(unanchored, d.path)
		}
	}
	return anchored, failures, unanchored
}

func documentAnchors(d docFile, known map[string]DocClaim) ([]DocClaim, []DocFailure) {
	claims, failures := []DocClaim{}, []DocFailure{}
	for _, m := range docAnchor.FindAllSubmatchIndex(d.raw, -1) {
		line := bytes.Count(d.raw[:m[0]], []byte("\n")) + 1
		fields := docAnchorFields.FindStringSubmatch(string(d.raw[m[2]:m[3]]))
		if fields == nil || !flowIDPattern.MatchString(fields[1]) || !memberPattern.MatchString(fields[2]) || !memberPattern.MatchString(fields[3]) {
			failures = append(failures, DocFailure{Code: DocBadAnchor, Path: d.path, Line: line, Detail: "a claim anchor needs flow=, variation= and outcome= with valid IDs"})
			continue
		}
		id := claimID(fields[1], fields[2], fields[3])
		c, ok := known[id]
		if !ok {
			failures = append(failures, DocFailure{Code: DocUnknownClaim, Claim: id, Path: d.path, Line: line, Detail: "the anchor names no flow, variation and outcome of the committed intents"})
			continue
		}
		c.ID, c.Source = d.path+":"+id, d.path
		claims = append(claims, c)
	}
	slices.SortFunc(claims, func(x, y DocClaim) int { return strings.Compare(x.ID, y.ID) })
	return slices.CompactFunc(claims, func(a, b DocClaim) bool { return a.ID == b.ID }), failures
}

func docCoverage(docs []docFile, unanchored []string, revision string) *DocCoverage {
	return &DocCoverage{Row: docUnanchoredRow, Value: len(unanchored), Denominator: len(docs), Revision: revision,
		Rule: docCoverageRule, Limitation: docLimitation, Paths: unanchored}
}

func renderDocs(b docBuild, o DocOptions) ([]byte, []byte, error) {
	claims := slices.Clone(b.claims)
	slices.SortFunc(claims, func(x, y DocClaim) int { return strings.Compare(x.ID, y.ID) })
	sidecar, err := doccorpus.Encode(DocClaims{Schema: DocClaimsSchema, Page: o.Page, Claims: claims})
	if err != nil {
		return nil, nil, err
	}
	return renderPage(b.set, claimStates(claims)), sidecar, nil
}

func claimStates(claims []DocClaim) map[string]string {
	states := map[string]string{}
	for _, c := range claims {
		states[c.ID] = c.State
	}
	return states
}

// renderPage is the fixed 1.0 template: intent fields only, escaped, and no free prose (AFU-V1-030).
func renderPage(set IntentSet, states map[string]string) []byte {
	var b strings.Builder
	b.WriteString(docPageHeader + "\n# Application flows\n")
	for _, intent := range set.Flows {
		writeFlow(&b, intent, states)
	}
	return []byte(b.String())
}

func writeFlow(b *strings.Builder, intent FlowIntent, states map[string]string) {
	fmt.Fprintf(b, "\n## Flow `%s`\n\n- Kind: %s\n- Actor: %s\n", intent.FlowID, intent.Kind, docText(intent.Actor))
	if intent.Proposed {
		b.WriteString("- Proposed: not reviewed\n")
	}
	fmt.Fprintf(b, "- Preconditions: %s\n- Steps:\n", docList(intent.Preconditions))
	for i, s := range intent.Steps {
		fmt.Fprintf(b, "  %d. `%s`: %s\n", i+1, s.StepID, docText(s.Action))
	}
	behaviors := map[string]string{}
	for _, o := range intent.Outcomes {
		behaviors[o.OutcomeID] = o.Behavior
	}
	for _, v := range intent.Variations {
		fmt.Fprintf(b, "\n### Variation `%s`\n\n- Preconditions: %s\n- Steps: %s\n- Projects: %s\n- Outcomes:\n",
			v.VariationID, docList(v.Preconditions), docIDs(v.Steps), docList(v.Projects))
		for _, o := range v.Outcomes {
			fmt.Fprintf(b, "  - %s`%s`: %s\n", stateMark(states[claimID(intent.FlowID, v.VariationID, o)]), claimID(intent.FlowID, v.VariationID, o), docText(behaviors[o]))
		}
	}
}

// stateMark marks every claim that is not PROVEN (AFU-V1-031).
func stateMark(state string) string {
	if state == ClaimProven {
		return ""
	}
	return "**" + state + ":** "
}

func docList(values []string) string {
	if len(values) == 0 {
		return "none"
	}
	escaped := []string{}
	for _, v := range values {
		escaped = append(escaped, docText(v))
	}
	return strings.Join(escaped, "; ")
}

func docIDs(ids []string) string {
	if len(ids) == 0 {
		return "none"
	}
	return "`" + strings.Join(ids, "`, `") + "`"
}

// docText backslash-escapes every ASCII punctuation character, so intent text renders literally and
// can never form an anchor comment, a link or markup.
func docText(s string) string {
	var b strings.Builder
	for _, r := range s {
		if strings.ContainsRune("!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~", r) {
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	return b.String()
}

// committedFiles is the committed page and sidecar; a nil page or sidecar is absent at HEAD.
type committedFiles struct {
	page, sidecar []byte
	claims        []DocClaim
}

func committedDocs(ctx context.Context, root, rev string, o DocOptions) (committedFiles, error) {
	page, err := committedFile(ctx, root, rev, o.Page)
	if err != nil {
		return committedFiles{}, err
	}
	sidecar, err := committedFile(ctx, root, rev, o.Claims)
	if err != nil {
		return committedFiles{}, err
	}
	var decoded DocClaims
	if sidecar != nil && Decode(sidecar, &decoded) == nil && decoded.Schema == DocClaimsSchema {
		return committedFiles{page: page, sidecar: sidecar, claims: decoded.Claims}, nil
	}
	return committedFiles{page: page, sidecar: sidecar}, nil
}

// committedFile reads one regular committed file at rev, or returns nil when it is absent.
func committedFile(ctx context.Context, root, rev, name string) ([]byte, error) {
	entries, err := docTree(ctx, root, rev, name)
	if err != nil {
		return nil, err
	}
	i := slices.IndexFunc(entries, func(e treeEntry) bool { return e.name == name })
	if i < 0 {
		return nil, nil
	}
	return committedBlob(ctx, root, entries[i])
}

// committedWaivers reads and validates the waivers file at rev; no path means no waiver.
func committedWaivers(ctx context.Context, root, rev, name string) ([]DocWaiver, error) {
	if name == "" {
		return []DocWaiver{}, nil
	}
	if !safePath(name) {
		return nil, errors.New("--waivers must be a canonical repository-relative path")
	}
	raw, err := committedFile(ctx, root, rev, name)
	if err != nil {
		return nil, err
	}
	if raw == nil {
		return nil, fmt.Errorf("waivers file %s is absent at the evaluated revision", name)
	}
	var w DocWaivers
	if err = Decode(raw, &w); err != nil {
		return nil, err
	}
	return w.Waivers, validateWaivers(w)
}

// validateWaivers requires the schema and, per entry, a unique claim ID, reason, reviewer and a
// calendar expiry date (AFU-V1-032).
func validateWaivers(w DocWaivers) error {
	if w.Schema != DocWaiversSchema {
		return errors.New("waivers schema must be " + DocWaiversSchema)
	}
	seen := map[string]bool{}
	for _, entry := range w.Waivers {
		expiry, err := time.Parse(time.DateOnly, entry.Expires)
		if err != nil || expiry.Format(time.DateOnly) != entry.Expires {
			return errors.New("a waiver expiry must be a YYYY-MM-DD date")
		}
		if !flowText(entry.Claim) || !flowText(entry.Reason) || !flowText(entry.Reviewer) || seen[entry.Claim] {
			return errors.New("a waiver needs a unique claim ID, a reason and a reviewer")
		}
		seen[entry.Claim] = true
	}
	return nil
}

// applyWaivers finds each committed claim whose state changed or which is gone. An unexpired waiver
// keeps the committed claim for the byte comparison; otherwise a lost PROVEN is a failure.
func applyWaivers(regenerated, committed []DocClaim, waivers []DocWaiver, today string) ([]DocClaim, []DocFailure, []string) {
	current := claimStates(regenerated)
	byClaim := map[string]DocWaiver{}
	for _, w := range waivers {
		byClaim[w.Claim] = w
	}
	effective, failures, waived := slices.Clone(regenerated), []DocFailure{}, []string{}
	for _, c := range committed {
		state, present := current[c.ID]
		if present && state == c.State {
			continue
		}
		w, named := byClaim[c.ID]
		if named && today < w.Expires {
			waived = append(waived, c.ID)
			effective = keepCommitted(effective, c)
			continue
		}
		if c.State == ClaimProven {
			failures = append(failures, lostProven(c, state, present, w, named))
		}
	}
	return effective, failures, waived
}

func keepCommitted(claims []DocClaim, c DocClaim) []DocClaim {
	i := slices.IndexFunc(claims, func(x DocClaim) bool { return x.ID == c.ID })
	if i >= 0 {
		claims[i] = c
	}
	return claims
}

func lostProven(c DocClaim, state string, present bool, w DocWaiver, named bool) DocFailure {
	detail := "the claim was PROVEN and is now " + state
	if !present {
		detail = "the claim was PROVEN and is no longer rendered"
	}
	if named {
		detail += "; its waiver expired on " + w.Expires
	}
	return DocFailure{Code: DocLostProven, Claim: c.ID, Path: c.Source, Detail: detail}
}

func bytesFailure(name string, committed, regenerated []byte) []DocFailure {
	if committed != nil && bytes.Equal(committed, regenerated) {
		return []DocFailure{}
	}
	return []DocFailure{{Code: DocBytesDiffer, Path: name, Detail: "the committed bytes differ from regeneration at the evaluated revision"}}
}

// ReplaceConfined replaces rel under root through a temporary file created exclusively in the same
// directory and a rename, following no symlink; an existing target must be a regular file (AFU-V1-036).
func ReplaceConfined(root, rel string, data []byte) error {
	if !safePath(rel) || rel == "." {
		return errors.New("flow output must be a canonical repository-relative path")
	}
	r, err := os.OpenRoot(root)
	if err != nil {
		return errors.New("flow root unavailable")
	}
	defer r.Close()
	if err = realParents(r, rel); err != nil {
		return err
	}
	if st, err := r.Lstat(rel); err == nil && !st.Mode().IsRegular() {
		return errors.New("flow output target must be a regular file")
	}
	tmp, err := writeTemp(r, rel, data)
	if err != nil {
		return err
	}
	if err = r.Rename(tmp, rel); err != nil {
		_ = r.Remove(tmp)
		return errors.New("cannot replace flow output")
	}
	return nil
}

func writeTemp(r *os.Root, rel string, data []byte) (string, error) {
	suffix := make([]byte, 8)
	_, _ = rand.Read(suffix)
	tmp := path.Join(path.Dir(rel), "."+path.Base(rel)+".tmp-"+hex.EncodeToString(suffix))
	f, err := r.OpenFile(tmp, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0644)
	if err != nil {
		return "", errors.New("cannot exclusively create flow output")
	}
	_, err = f.Write(data)
	if err == nil {
		err = f.Sync()
	}
	if closeErr := f.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		_ = r.Remove(tmp)
		return "", errors.New("cannot write flow output")
	}
	return tmp, nil
}
