package frontierrepo

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/Beamfall/corvint/internal/cem/wire"
	"github.com/Beamfall/corvint/internal/cem/workflow"
	"github.com/Beamfall/corvint/internal/lrfrepo"
	"github.com/Beamfall/corvint/internal/tcq"
)

// These are the original real-Git TCQ-0 vectors, never regenerated by Go.
func TestFrozenTCQConformanceVectors(t *testing.T) {
	root, err := filepath.EvalSymlinks(t.TempDir())
	if err != nil {
		t.Fatal(err)
	}
	write := func(p, s string) {
		t.Helper()
		p = filepath.Join(root, p)
		if err := os.MkdirAll(filepath.Dir(p), 0755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(p, []byte(s), 0644); err != nil {
			t.Fatal(err)
		}
	}
	git := func(args ...string) string {
		t.Helper()
		cmd := exec.Command("git", args...)
		cmd.Dir = root
		cmd.Env = append(os.Environ(), "GIT_CONFIG_NOSYSTEM=1", "GIT_CONFIG_GLOBAL=/dev/null", "GIT_CONFIG_SYSTEM=/dev/null", "GIT_AUTHOR_NAME=TCQ Conformance", "GIT_AUTHOR_EMAIL=tcq@example.invalid", "GIT_COMMITTER_NAME=TCQ Conformance", "GIT_COMMITTER_EMAIL=tcq@example.invalid", "GIT_AUTHOR_DATE=2000-01-01T00:00:00+0000", "GIT_COMMITTER_DATE=2000-01-01T00:00:00+0000")
		var stdout, stderr bytes.Buffer
		cmd.Stdout, cmd.Stderr = &stdout, &stderr
		if err := cmd.Run(); err != nil {
			t.Fatalf("git %v: %v %s", args, err, &stderr)
		}
		return strings.TrimSpace(stdout.String())
	}
	write("docs/spec.md", "# TCQ vector\n\n## Requirements\n\n- `TCQ-CONF-001`: The value must change.\n")
	write("docs/rule.md", "Rule: changes cite stable evidence.\n")
	write("src/app.py", "value = 1\n")
	git("init", "-q", "--object-format=sha1", "--template=")
	git("add", ".")
	git("commit", "-qm", "base")
	base := git("rev-parse", "HEAD")
	write("src/app.py", "value = 2\n")
	write("tests/test_app.py", "def test_value_changes():\n    \"\"\"TCQ-CONF-001 is exercised.\"\"\"\n    assert True\n")
	git("add", ".")
	git("commit", "-qm", "target")
	target := git("rev-parse", "HEAD")
	if base != "cf0a02e6586e3197d50b117a84094e94f81a8e85" || target != "59cf4f6560ad25e420d3b06e05c09b452936e7e1" {
		t.Fatalf("fixture identities changed: %s %s", base, target)
	}
	ctx := context.Background()
	session, err := workflow.Open(root)
	if err != nil {
		t.Fatal(err)
	}
	if _, err = session.Prepare(ctx, workflow.PrepareOptions{Base: base, Target: target}); err != nil {
		t.Fatal(err)
	}
	cemPath := filepath.Join(root, wire.ExcludedCEMPath)
	raw, err := os.ReadFile(cemPath)
	if err != nil {
		t.Fatal(err)
	}
	document, err := wire.ParseMap(raw)
	if err != nil {
		t.Fatal(err)
	}
	hunk := ""
	for _, h := range document.Hunks {
		if h.Path == "src/app.py" {
			hunk = h.ID
		}
	}
	if hunk == "" {
		t.Fatal("missing source hunk")
	}
	if _, err = session.Cite(ctx, workflow.CiteOptions{MapPath: wire.ExcludedCEMPath, Hunk: hunk, EvidencePath: "docs/rule.md", Bytes: "0:36", Relation: "specification"}); err != nil {
		t.Fatal(err)
	}
	canonicalFile := func(p string) []byte {
		t.Helper()
		raw, err := os.ReadFile(p)
		if err != nil {
			t.Fatal(err)
		}
		value, err := wire.Parse(raw)
		if err != nil {
			t.Fatal(err)
		}
		return append(wire.CanonicalValue(value), '\n')
	}
	cemRaw := canonicalFile(cemPath)
	if err := os.WriteFile(cemPath, cemRaw, 0600); err != nil {
		t.Fatal(err)
	}
	ocmPath := ".corvint/change.ocm.json"
	if _, err := lrfrepo.PrepareOCM(ctx, root, lrfrepo.PrepareOptions{MapPath: ocmPath, CEMPath: wire.ExcludedCEMPath, IntentPath: "docs/spec.md", Target: target, ExpectedBase: base}); err != nil {
		t.Fatal(err)
	}
	// OCM's public writer deliberately refuses Python enumeration. This is an
	// independently authored legacy input to TCQ's existing native read seam.
	body, err := os.ReadFile(filepath.Join(root, "tests/test_app.py"))
	if err != nil {
		t.Fatal(err)
	}
	anchor := []byte(`"""TCQ-CONF-001 is exercised."""`)
	start := bytes.Index(body, anchor)
	if start < 0 {
		t.Fatal("missing fixture anchor")
	}
	claim := map[string]any{"extractor": "corvint-test-claim/1", "path": "tests/test_app.py", "blobOid": git("rev-parse", target+":tests/test_app.py"), "selector": "test:test_value_changes#doc", "span": map[string]any{"start": start, "end": start + len(anchor)}, "spanSha256": digestHex(anchor)}
	claimBody, err := json.Marshal(claim)
	if err != nil {
		t.Fatal(err)
	}
	claim["id"] = "claim:sha256:" + digestHex(claimBody)
	if claim["id"] != "claim:sha256:4e8d0663d78cd2dbd656b0dc67fc47d5e3dac6fb8a32e8a63c3c327cc14d4130" {
		t.Fatal("fixture claim identity changed")
	}
	var mapped map[string]any
	if err := json.Unmarshal(canonicalFile(filepath.Join(root, ocmPath)), &mapped); err != nil {
		t.Fatal(err)
	}
	mapped["claims"] = []any{claim}
	mapped["obligations"] = []any{map[string]any{"id": "TCQ-CONF-001", "disposition": "linked", "reason": "change-and-test-linked", "hunkIds": []string{hunk}, "claimIds": []any{claim["id"]}}}
	mappedRaw, err := json.Marshal(mapped)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(root, ocmPath), mappedRaw, 0600); err != nil {
		t.Fatal(err)
	}
	ocmRaw := canonicalFile(filepath.Join(root, ocmPath))
	adapter := New(ctx, root)
	repository, err := adapter.tree()
	if err != nil {
		t.Fatal(err)
	}
	request := tcq.Request{CEM: cemRaw, OCM: ocmRaw, ExpectedBase: base, Target: target}
	compare := func(name string) {
		t.Helper()
		result, err := tcq.Evaluate(repository, adapter, request)
		if err != nil {
			t.Fatal(err)
		}
		want, err := os.ReadFile(filepath.Join("../../conformance/tcq-0", name+".tcq.json"))
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(result.Raw(), want) {
			t.Fatalf("%s frozen vector changed:\n%s\nwant:\n%s", name, result.Raw(), want)
		}
	}
	compare("static")
	command, err := tcq.MakeTestCommand([]string{"python3", "-m", "unittest"}, ".", "python-unittest", "3.13.7", target, tcq.CleanTargetAttested)
	if err != nil {
		t.Fatal(err)
	}
	report := []byte(`<testsuite><testcase file="tests/test_app.py" name="test_value_changes"/></testsuite>`)
	observation, err := tcq.MakeTestObservation(repository, command, report, target, 0)
	if err != nil {
		t.Fatal(err)
	}
	request.Command, request.Observation, request.Report = command, observation, report
	compare("dynamic")
	request.Observation, request.Report = nil, nil
	if _, err := tcq.Evaluate(repository, adapter, request); err == nil || err.Error() != "invalid-tcq-input" {
		t.Fatalf("partial tuple: %v", err)
	}
	hostile := []byte(`<!DOCTYPE testsuite [<!ENTITY xxe SYSTEM "file:///etc/passwd">]><testsuite/>`)
	if _, err := tcq.MakeTestObservation(repository, command, hostile, target, 0); err == nil || err.Error() != "invalid-junit" {
		t.Fatalf("hostile XML: %v", err)
	}
}
