package contextindex

import (
	"math/rand"
	"strings"
	"testing"
)

// TestIsGeneratedHeaderMatchesRegexpExactly pins the literal gate in
// isGeneratedHeader to the regexp it is standing in for. The gate is only
// sound while every string the pattern accepts also contains "code generated"
// under ASCII case folding; this test is what makes that claim falsifiable.
func TestIsGeneratedHeaderMatchesRegexpExactly(t *testing.T) {
	cases := []string{
		"",
		"package main\n",
		"// Code generated by protoc. DO NOT EDIT.",
		"// code generated by mockgen. do not edit.",
		"// CODE GENERATED BY STRINGER. DO NOT EDIT.",
		"// CoDe GeNeRaTeD by x. Do NoT eDiT.",
		"// Code generated. DO NOT EDIT",        // missing final period
		"// Code  generated by x. DO NOT EDIT.", // double space, must not match
		"// Codegenerated by x. DO NOT EDIT.",   // no separator
		"code generated",                        // literal present, pattern absent
		"CODE GENERATED",                        // fold present, pattern absent
		"/* Code generated by y. DO NOT EDIT. */",
		"\x00\x00Code generated by z. DO NOT EDIT.",
		strings.Repeat("x", 4000) + "Code generated by w. DO NOT EDIT.",
		"Ｃode generated by w. DO NOT EDIT.", // full-width C, must not fold to ASCII
		"CODE GENERATED BY x. DO NOT EDIT." + strings.Repeat("y", 100),
	}

	// Randomized differential sweep over the alphabet that can produce a match.
	source := rand.New(rand.NewSource(20260829))
	alphabet := []rune("CcOoDdEeGgNnRrAaTt .\nDONOTEDIT-/*\x00Ｃ")
	for count := 0; count < 20000; count++ {
		length := source.Intn(48)
		var builder strings.Builder
		for index := 0; index < length; index++ {
			builder.WriteRune(alphabet[source.Intn(len(alphabet))])
		}
		cases = append(cases, builder.String())
	}
	// Mutations of a known-matching header, which is where a fold bug would hide.
	base := "// Code generated by tool. DO NOT EDIT."
	for count := 0; count < 5000; count++ {
		runes := []rune(base)
		position := source.Intn(len(runes))
		runes[position] = alphabet[source.Intn(len(alphabet))]
		cases = append(cases, string(runes))
	}

	for _, input := range cases {
		want := generatedHeader.Match([]byte(input))
		got := isGeneratedHeader([]byte(input))
		if got != want {
			t.Fatalf("isGeneratedHeader(%q) = %v, regexp says %v", input, got, want)
		}
	}
}

// TestMarkerLiteralGateAdmitsEveryMatch pins the file-level gate in compile():
// no string the marker pattern matches may lack both literals.
func TestMarkerLiteralGateAdmitsEveryMatch(t *testing.T) {
	source := rand.New(rand.NewSource(20260830))
	alphabet := []rune("featurscnio:-0123456789 \nABZ_")
	for count := 0; count < 40000; count++ {
		length := source.Intn(40)
		var builder strings.Builder
		for index := 0; index < length; index++ {
			builder.WriteRune(alphabet[source.Intn(len(alphabet))])
		}
		text := builder.String()

		gated := strings.Contains(text, "feature:") || strings.Contains(text, "scenario:")
		if gated {
			continue
		}
		for _, line := range strings.Split(text, "\n") {
			if matches := markerMatches(line); len(matches) != 0 {
				t.Fatalf("gate skipped %q but markerMatches found %d in line %q",
					text, len(matches), line)
			}
		}
	}
}

func TestGeneratedHeaderMustStartALine(t *testing.T) {
	for _, item := range []struct {
		name      string
		prefix    string
		generated bool
	}{
		{"go header", "// Code generated by stringer. DO NOT EDIT.\n\npackage x\n", true},
		{"indented hash header", "  # Code generated by protoc. DO NOT EDIT.\nimport x\n", true},
		{"marker quoted in a string literal", "package x\n\nvar fixture = map[string]string{\n\t\"gen.go\": \"// Code generated by fixture. DO NOT EDIT.\\n\",\n}\n", false},
		{"marker mid-line in prose", "The tool writes 'Code generated by corvint. DO NOT EDIT.' at the top.\n", false},
	} {
		if got := isGeneratedHeader([]byte(item.prefix)); got != item.generated {
			t.Errorf("%s: generated = %v, want %v", item.name, got, item.generated)
		}
	}
}
