package contextindex

import (
	"context"
	"errors"
	"os/exec"
	"reflect"
	"runtime"
	"strings"
	"testing"
)

func impactRepository(t *testing.T, objectFormat string) string {
	t.Helper()
	root := t.TempDir()
	arguments := []string{"init", "-q"}
	if objectFormat != "" {
		arguments = append(arguments, "--object-format="+objectFormat)
	}
	command := testGitOptional(t, root, arguments...)
	if command != "" {
		t.Skipf("git %v unsupported: %s", arguments, command)
	}
	testGit(t, root, "config", "user.email", "corvint@example.test")
	testGit(t, root, "config", "user.name", "Corvint Test")
	files := map[string]string{
		"go.mod":                       "module example.test/fixture\n\ngo 1.27.0\n",
		"internal/token/token.go":      "package token\n\n// feature:stream-token scenario:revoked-token\nfunc MintToken() string { return \"token\" }\n",
		"internal/token/token_test.go": "package token\n\n// feature:stream-token\nfunc TestMintToken() { _ = MintToken() }\n",
		"internal/token/other.go":      "package token\n\nfunc Other() {}\n",
		"internal/token/use.go":        "package token\n\nfunc UseToken() string { return MintToken() }\n",
		"internal/api/api.go":          "package api\n\nimport \"example.test/fixture/internal/token\"\n\nvar _ = token.MintToken\n",
		"internal/aaa/token_test.go":   "package aaa\n\nimport \"example.test/fixture/internal/token\"\n\n// feature:session-browser\nfunc TestToken() { _ = token.MintToken }\n",
		"internal/multi/token_test.go": "package multi\n\nimport \"example.test/fixture/internal/token\"\n\n// feature:reveal-unlock feature:navigation-manifest\nfunc TestBroadCoverage() { _ = token.MintToken }\n",
		"internal/zapi/api.go":         "package zapi\n\nimport \"example.test/fixture/internal/token\"\n\nvar _ = token.MintToken\n",
		"internal/auth/scope.go":       "package auth\n\nfunc scopeAllowsSession() bool { return true }\n",
		"internal/auth/scope_test.go":  "package auth\n\n// feature:session-lifecycle\nfunc TestScope() {}\n",
		"internal/auth/use_scope.go":   "package auth\n\nfunc Authorize() bool { return scopeAllowsSession() }\n",
		"internal/auth/comment_only.go": "package auth\n\n// scopeAllowsSession is not called here.\n" +
			"var commentOnly = \"scopeAllowsSession\"\n",
		"web/caller.ts":               "import \"example.test/fixture/internal/token\";\n",
		"vendor/example/bad.go":       "package bad\n",
		"internal/token/generated.go": "// Code generated by fixture. DO NOT EDIT.\npackage token\n",
		"testing/features.yaml": "features:\n" +
			"  - id: stream-token\n    area: auth\n    summary: Mint a stream token.\n    adr: [\"0012\"]\n    applies: [server]\n    status: shipped\n" +
			"  - id: session-browser\n    area: auth\n    summary: Browse sessions.\n    status: shipped\n" +
			"  - id: session-lifecycle\n    area: auth\n    summary: Enforce sessions.\n    status: shipped\n" +
			"  - id: reveal-unlock\n    area: reveal\n    summary: Reveal content.\n    status: partial\n" +
			"  - id: navigation-manifest\n    area: browse\n    summary: Navigate content.\n    status: partial\n",
		"testing/scenarios.yaml": "scenarios:\n  - id: revoked-token\n    area: auth\n    summary: Revoked tokens are denied.\n    features: [stream-token]\n    applies: [server]\n    status: shipped\n",
		"docs/adr/0012-token.md": "# Token decision\n\nstatus: accepted\n",
		"docs/specs/token.md":    "# Token spec\n\nstatus: accepted\n\nCovers internal/token/token.go.\n",
	}
	for relative, content := range files {
		writeTestFile(t, root, relative, content)
	}
	testGit(t, root, "add", ".")
	testGit(t, root, "commit", "-qm", "impact fixture")
	return root
}

func testGitOptional(t *testing.T, root string, arguments ...string) string {
	t.Helper()
	command := execCommand("git", append([]string{"-c", "gc.auto=0", "-c", "maintenance.auto=false", "-C", root}, arguments...)...)
	output, err := command.CombinedOutput()
	if err != nil {
		return string(output)
	}
	return ""
}

var execCommand = exec.Command

func TestImpactCompilesFullGoPathResultClosure(t *testing.T) {
	root := impactRepository(t, "")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	receipt, err := Impact(index, []string{"internal/token/token.go"}, 20)
	if err != nil {
		t.Fatal(err)
	}
	kinds := make(map[string]bool)
	for _, raw := range anySlice(receipt["results"]) {
		item := raw.(map[string]any)
		kinds[stringValue(item["kind"])] = true
	}
	for _, kind := range []string{"path", "test", "reference", "reverse-import", "feature", "scenario", "spec"} {
		if !kinds[kind] {
			t.Errorf("missing %s result; kinds=%v", kind, kinds)
		}
	}
	resultIDs := make(map[string]bool)
	for _, raw := range anySlice(receipt["results"]) {
		item := raw.(map[string]any)
		resultIDs[stringValue(item["id"])] = true
	}
	if !resultIDs["web/caller.ts"] {
		t.Fatalf("non-Go reverse importer missing; ids=%v", resultIDs)
	}
	encoded, err := CanonicalJSON(receipt)
	if err != nil {
		t.Fatal(err)
	}
	coverage := receipt["coverage"].(map[string]any)
	if coverage["packet_bytes"] != len(encoded) {
		t.Fatalf("packet_bytes=%v encoded=%d", coverage["packet_bytes"], len(encoded))
	}
}

func resultKeys(receipt map[string]any) []string {
	result := make([]string, 0)
	for _, raw := range anySlice(receipt["results"]) {
		item := raw.(map[string]any)
		result = append(result, stringValue(item["kind"])+":"+stringValue(item["id"]))
	}
	return result
}

func BenchmarkMergeEvidence(b *testing.B) {
	candidate := map[string]any{"evidence": evidenceBenchmarkItems(5, 10)}
	b.ReportAllocs()
	b.ResetTimer()
	for b.Loop() {
		existing := map[string]any{"evidence": evidenceBenchmarkItems(0, 5)}
		mergeEvidence(existing, candidate)
		runtime.KeepAlive(existing)
	}
}

func TestMergeEvidenceAllocationRatchet(t *testing.T) {
	candidate := map[string]any{"evidence": evidenceBenchmarkItems(5, 10)}
	allocations := testing.AllocsPerRun(100, func() {
		runtime.KeepAlive(mergeEvidenceBenchmarkFixture(candidate))
	})
	if allocations > 16 {
		t.Fatalf("merge evidence allocations=%.0f want <=16", allocations)
	}
	result := testing.Benchmark(BenchmarkMergeEvidence)
	if bytes := result.AllocedBytesPerOp(); bytes > 2200 {
		t.Fatalf("merge evidence bytes/op=%d want <=2200", bytes)
	}
	if allocations := result.AllocsPerOp(); allocations > 15 {
		t.Fatalf("merge evidence allocs/op=%d want <=15", allocations)
	}
	if restored := testing.AllocsPerRun(100, func() {
		runtime.KeepAlive(mergeEvidenceWithSetBenchmarkFixture(candidate))
	}); restored <= 16 {
		t.Fatalf("restored merge evidence allocations=%.0f want >16", restored)
	}
}

func TestMergeEvidencePreservesUniqueTypedOrder(t *testing.T) {
	existingItem := map[string]any{"path": "a.go", "line": 7, "reason": "direct"}
	candidateItem := map[string]any{"path": "b.go", "line": 9, "reason": "reference"}
	existing := map[string]any{"evidence": []any{existingItem}}
	candidate := map[string]any{"evidence": []any{existingItem, candidateItem}}
	mergeEvidence(existing, candidate)
	got := anySlice(existing["evidence"])
	if len(got) != 2 || stringValue(got[0].(map[string]any)["path"]) != "a.go" || stringValue(got[1].(map[string]any)["path"]) != "b.go" {
		t.Fatalf("evidence=%#v", got)
	}
}

func TestMergeEvidenceMatchesRestoredSetControl(t *testing.T) {
	cases := []struct {
		name      string
		existing  []any
		candidate []any
	}{
		{"overlap", evidenceBenchmarkItems(0, 5), evidenceBenchmarkItems(3, 10)},
		{"candidate duplicates", evidenceBenchmarkItems(0, 2), append(evidenceBenchmarkItems(2, 4), evidenceBenchmarkItems(2, 4)...)},
		{"capacity", evidenceBenchmarkItems(0, maxEvidence), evidenceBenchmarkItems(maxEvidence, maxEvidence+3)},
	}
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			got := map[string]any{"evidence": append([]any(nil), test.existing...)}
			want := map[string]any{"evidence": append([]any(nil), test.existing...)}
			candidate := map[string]any{"evidence": test.candidate}
			mergeEvidence(got, candidate)
			mergeEvidenceWithSet(want, candidate)
			if !reflect.DeepEqual(got, want) {
				t.Fatalf("merge evidence=%#v, restored control=%#v", got, want)
			}
		})
	}
}

func TestMergeEvidenceCapsProductionBound(t *testing.T) {
	existing := map[string]any{"evidence": evidenceBenchmarkItems(0, maxEvidence-1)}
	candidate := map[string]any{"evidence": evidenceBenchmarkItems(maxEvidence-2, maxEvidence+3)}
	mergeEvidence(existing, candidate)
	got := anySlice(existing["evidence"])
	if len(got) != maxEvidence {
		t.Fatalf("evidence count=%d want %d", len(got), maxEvidence)
	}
	for index, raw := range got {
		line := raw.(map[string]any)["line"]
		if line != 100+index {
			t.Fatalf("evidence[%d] line=%v want %d", index, line, 100+index)
		}
	}
}

func mergeEvidenceBenchmarkFixture(candidate map[string]any) map[string]any {
	existing := map[string]any{"evidence": evidenceBenchmarkItems(0, 5)}
	mergeEvidence(existing, candidate)
	return existing
}

func mergeEvidenceWithSetBenchmarkFixture(candidate map[string]any) map[string]any {
	existing := map[string]any{"evidence": evidenceBenchmarkItems(0, 5)}
	mergeEvidenceWithSet(existing, candidate)
	return existing
}

// mergeEvidenceWithSet is the exact pre-change production implementation.
func mergeEvidenceWithSet(existing, candidate map[string]any) {
	existingEvidence := anySlice(existing["evidence"])
	seen := make(map[evidenceKey]struct{}, len(existingEvidence))
	for _, raw := range existingEvidence {
		item := raw.(map[string]any)
		seen[evidenceIdentity(item)] = struct{}{}
	}
	for _, raw := range anySlice(candidate["evidence"]) {
		item := raw.(map[string]any)
		key := evidenceIdentity(item)
		if _, ok := seen[key]; !ok && len(existingEvidence) < maxEvidence {
			existingEvidence = append(existingEvidence, item)
			seen[key] = struct{}{}
		}
	}
	existing["evidence"] = existingEvidence
}

func evidenceBenchmarkItems(first, last int) []any {
	items := make([]any, 0, last-first)
	for index := first; index < last; index++ {
		items = append(items, map[string]any{
			"path":   "internal/contextindex/impact.go",
			"line":   100 + index,
			"reason": "benchmark evidence",
		})
	}
	return items
}

func TestImpactPreservesProductionAndTestScoping(t *testing.T) {
	root := impactRepository(t, "")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}

	production, err := Impact(index, []string{"internal/token/token.go"}, 50)
	if err != nil {
		t.Fatal(err)
	}
	productionKeys := resultKeys(production)
	for _, want := range []string{
		"reverse-import:internal/zapi/api.go",
		"reverse-import:internal/aaa/token_test.go",
		"feature:stream-token",
		"feature:session-browser",
	} {
		if !stringIn(productionKeys, want) {
			t.Errorf("production impact missing %s; keys=%v", want, productionKeys)
		}
	}
	for _, unwanted := range []string{"feature:reveal-unlock", "feature:navigation-manifest"} {
		if stringIn(productionKeys, unwanted) {
			t.Errorf("production impact included broad importer marker %s; keys=%v", unwanted, productionKeys)
		}
	}
	zapi := indexOf(productionKeys, "reverse-import:internal/zapi/api.go")
	aaa := indexOf(productionKeys, "reverse-import:internal/aaa/token_test.go")
	if zapi < 0 || aaa < 0 || zapi >= aaa {
		t.Fatalf("production importer order=%v", productionKeys)
	}

	testOnly, err := Impact(index, []string{"internal/token/token_test.go"}, 50)
	if err != nil {
		t.Fatal(err)
	}
	testKeys := resultKeys(testOnly)
	if !stringIn(testKeys, "feature:stream-token") {
		t.Fatalf("test-only impact omitted direct marker; keys=%v", testKeys)
	}
	if stringIn(testKeys, "feature:session-browser") {
		t.Fatalf("test-only impact leaked importer marker; keys=%v", testKeys)
	}
	for _, key := range testKeys {
		if strings.HasPrefix(key, "reverse-import:") {
			t.Fatalf("test-only impact returned reverse importer %s; keys=%v", key, testKeys)
		}
	}
}

func TestImpactUsesSyntaxReferencesAndDeduplicatesMultiPathResults(t *testing.T) {
	root := impactRepository(t, "")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}

	auth, err := Impact(index, []string{"internal/auth/scope.go"}, 50)
	if err != nil {
		t.Fatal(err)
	}
	authKeys := resultKeys(auth)
	for _, want := range []string{
		"test:internal/auth/scope_test.go",
		"reference:internal/auth/use_scope.go",
		"feature:session-lifecycle",
	} {
		if !stringIn(authKeys, want) {
			t.Errorf("auth impact missing %s; keys=%v", want, authKeys)
		}
	}
	if stringIn(authKeys, "reference:internal/auth/comment_only.go") {
		t.Fatalf("comment/string-only occurrence became a reference; keys=%v", authKeys)
	}

	multi, err := Impact(index, []string{"internal/token/token.go", "internal/token/other.go"}, 50)
	if err != nil {
		t.Fatal(err)
	}
	seen := make(map[string]bool)
	for _, key := range resultKeys(multi) {
		if seen[key] {
			t.Fatalf("duplicate multi-path result %s", key)
		}
		seen[key] = true
	}
	if !seen["reverse-import:internal/api/api.go"] {
		t.Fatalf("multi-path impact omitted shared importer; keys=%v", resultKeys(multi))
	}
}

func TestImpactReturnsOutOfScopeForTrackedExclusions(t *testing.T) {
	root := impactRepository(t, "")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	for _, changedPath := range []string{"vendor/example/bad.go", "internal/token/generated.go"} {
		receipt, err := Impact(index, []string{changedPath}, 10)
		if err != nil {
			t.Fatalf("Impact(%q): %v", changedPath, err)
		}
		if receipt["state"] != "OUT_OF_SCOPE" || len(anySlice(receipt["results"])) != 0 {
			t.Fatalf("Impact(%q) state=%v results=%v", changedPath, receipt["state"], receipt["results"])
		}
	}
}

func TestImpactRejectsInvalidBoundsBeforeCompilation(t *testing.T) {
	index := &Index{Module: "example.test/fixture"}
	tooMany := make([]string, maxImpactPaths+1)
	for position := range tooMany {
		tooMany[position] = "internal/token/token.go"
	}
	for _, test := range []struct {
		name  string
		paths []string
		limit int
		want  string
	}{
		{"empty paths", nil, 10, "non-empty list"},
		{"empty path", []string{""}, 10, "non-empty strings"},
		{"traversal", []string{"../outside.go"}, 10, "normalized and repository-relative"},
		{"unnormalized", []string{"internal/token/../token/token.go"}, 10, "normalized and repository-relative"},
		{"too many paths", tooMany, 10, "100-path bound"},
		{"zero limit", []string{"internal/token/token.go"}, 0, "limit must be"},
		{"excess limit", []string{"internal/token/token.go"}, maxLimit + 1, "limit must be"},
	} {
		t.Run(test.name, func(t *testing.T) {
			_, err := Impact(index, test.paths, test.limit)
			if err == nil || !strings.Contains(err.Error(), test.want) {
				t.Fatalf("error=%v want substring %q", err, test.want)
			}
		})
	}
}

func indexOf(values []string, value string) int {
	for index, candidate := range values {
		if candidate == value {
			return index
		}
	}
	return -1
}

func TestPythonWordBoundariesAreUnicodeAware(t *testing.T) {
	if !containsPythonWord("Fünf()", "Fünf") {
		t.Fatal("Unicode identifier was not matched")
	}
	for _, value := range []string{"xFünf", "Fünf٣"} {
		if containsPythonWord(value, "Fünf") {
			t.Fatalf("matched inside Unicode word %q", value)
		}
	}
}

func TestImpactRejectsUnqualifiedModuleAndAcceptsPOSIXBackslashPath(t *testing.T) {
	index := &Index{Module: "", Sources: map[string]Source{"token/value.go": {Path: "token/value.go"}}}
	_, err := Impact(index, []string{"token/value.go"}, 10)
	var unsupported *Error
	if err == nil || !errors.As(err, &unsupported) || unsupported.Code != "unsupported-impact-repository" {
		t.Fatalf("unqualified module error = %#v", err)
	}
	if runtime.GOOS == "windows" {
		return
	}
	root := impactRepository(t, "")
	writeTestFile(t, root, `internal/token/odd\name.go`, "package token\n")
	testGit(t, root, "add", `internal/token/odd\name.go`)
	testGit(t, root, "commit", "-qm", "add backslash path")
	built, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := Impact(built, []string{`internal/token/odd\name.go`}, 10); err != nil {
		t.Fatalf("POSIX backslash path: %v", err)
	}
}

func TestImpactMixedRenameUsesCommittedBlobAndBothEndpoints(t *testing.T) {
	root := impactRepository(t, "")
	original := testGit(t, root, "rev-parse", "HEAD:internal/token/token.go")
	testGit(t, root, "mv", "internal/token/token.go", "internal/token/renamed.go")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	for _, endpoint := range []string{"internal/token/token.go", "internal/token/renamed.go"} {
		if !stringIn(index.DirtyPaths, endpoint) {
			t.Fatalf("dirty paths %v omit %s", index.DirtyPaths, endpoint)
		}
	}
	if index.Sources["internal/token/token.go"].BlobHash != original {
		t.Fatalf("blob=%s want=%s", index.Sources["internal/token/token.go"].BlobHash, original)
	}
	receipt, err := Impact(index, []string{"internal/token/token.go"}, 10)
	if err != nil {
		t.Fatal(err)
	}
	if receipt["state"] != "READY" {
		t.Fatalf("state=%v", receipt["state"])
	}
	freshness := receipt["freshness"].(map[string]any)
	if freshness["state"] != "mixed-worktree" || freshness["mixed_path_count"] != 2 {
		t.Fatalf("freshness=%v", freshness)
	}
	if _, err := Impact(index, []string{"internal/token/renamed.go"}, 10); err == nil || !strings.Contains(err.Error(), "not tracked") {
		t.Fatalf("renamed path error=%v", err)
	}
}

func TestImpactSHA256EvidenceUsesSHA256BlobIdentity(t *testing.T) {
	root := impactRepository(t, "sha256")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	receipt, err := Impact(index, []string{"internal/token/token.go"}, 1)
	if err != nil {
		t.Fatal(err)
	}
	result := anySlice(receipt["results"])[0].(map[string]any)
	evidenceItem := anySlice(result["evidence"])[0].(map[string]any)
	if blob := stringValue(evidenceItem["blob_hash"]); len(blob) != 64 {
		t.Fatalf("blob hash=%q", blob)
	}
}

// TestImpactWithholdsUnverifiableADRAuthority pins `CF-V0-031` and `CF-V0-032` on
// the oracle-shared `impact` surface. `Impact(index, paths, limit)` receives only
// the change set the caller declares and no revision the caller did not author, so
// it cannot establish that a cited decision is independent of the change it is
// describing. The clause admits exactly two dispositions for such a surface, and
// this one reports rather than claims: the citation stays, with confidence `low`
// and authority `unverified-contract`, and the abstention is named.
//
// The refusal is deliberately unconditional. A predicate over `paths` would
// downgrade an honest caller who declares the decision it touched and would never
// touch an attacker, who reaches this code through the ledger record's `adr:`
// field and simply omits the path -- a control that closes nothing, which
// `CF-V0-025` forbids asserting.
func TestImpactWithholdsUnverifiableADRAuthority(t *testing.T) {
	root := impactRepository(t, "")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	receipt, err := Impact(index, []string{"internal/token/token.go"}, 20)
	if err != nil {
		t.Fatal(err)
	}
	cited := 0
	for _, entry := range anySlice(receipt["results"]) {
		for _, item := range anySlice(entry.(map[string]any)["evidence"]) {
			record := item.(map[string]any)
			if record["path"] != "docs/adr/0012-token.md" {
				if record["authority"] == "accepted-contract" || record["authority"] == "partially-superseded-contract" {
					t.Fatalf("impact asserted accepted authority it cannot verify: %v", record)
				}
				continue
			}
			cited++
			if record["authority"] != UnverifiedContractAuthority || record["confidence"] != "low" {
				t.Fatalf("cited decision keeps unverifiable authority: %v", record)
			}
			if record["reason"] != "ADR-0012 governs feature:stream-token" {
				t.Fatalf("withholding rewrote the citation itself: %v", record)
			}
		}
	}
	if cited == 0 {
		t.Fatal("fixture no longer reaches the ADR authority branch, so it discriminates nothing")
	}
	// CF-V0-032 (decision 0101) words the entry exactly and places it first.
	const withheld = "ADR-0012 governs feature:stream-token: no caller-independent revision is available at which to resolve the cited decision status, so accepted authority is withheld"
	uncertainty := anySlice(receipt["coverage"].(map[string]any)["uncertainty"])
	if len(uncertainty) == 0 || uncertainty[0] != withheld {
		t.Fatalf("abstention is not named in the CF-V0-032 form: %v", uncertainty)
	}
}

// TestImpactWithheldAuthorityUncertaintySurvivesBudgetCompilation proves the
// `CF-V0-032` derivation requirement: the uncertainty entry is computed from the
// emitted evidence, so every path that rebuilds coverage -- including budget
// compilation, which discards and rewrites the array -- carries the explanation
// alongside the label it explains.
func TestImpactWithheldAuthorityUncertaintySurvivesBudgetCompilation(t *testing.T) {
	root := impactRepository(t, "")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	budget := MaxPacketBytes
	receipt, err := EvalImpact(index, []string{"internal/token/token.go"}, 20, &budget)
	if err != nil {
		t.Fatal(err)
	}
	uncertainty := anySlice(receipt["coverage"].(map[string]any)["uncertainty"])
	if !anyContains(uncertainty, "ADR-0012 governs feature:stream-token: no caller-independent revision is available") {
		t.Fatalf("budget compilation dropped the named abstention: %v", uncertainty)
	}
}

// TestImpactCoverageDenominatesTheAdmittedUniverse proves that `omitted_results`
// counts the results the ranking ceiling dropped, not the zero that a receipt
// reports when it measures its own truncated output.  Coverage has to be
// denominated in the universe admitted for abstention to mean anything: a
// consumer reading `omitted_results: 0` must be able to conclude that nothing
// was dropped, which is only sound while `requested_results` names the
// pre-truncation count.
func TestImpactCoverageDenominatesTheAdmittedUniverse(t *testing.T) {
	root := impactRepository(t, "")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	admitted, err := Impact(index, []string{"internal/token/token.go"}, maxLimit)
	if err != nil {
		t.Fatal(err)
	}
	universe := len(anySlice(admitted["results"]))
	limit := universe - 2
	if limit < 1 {
		t.Fatalf("fixture ranks %d results, too few to truncate", universe)
	}
	truncated, err := Impact(index, []string{"internal/token/token.go"}, limit)
	if err != nil {
		t.Fatal(err)
	}
	coverage := truncated["coverage"].(map[string]any)
	if coverage["requested_results"] != universe {
		t.Fatalf("requested_results = %v, want the %d admitted results", coverage["requested_results"], universe)
	}
	if coverage["included_results"] != limit {
		t.Fatalf("included_results = %v, want %d", coverage["included_results"], limit)
	}
	if coverage["omitted_results"] != universe-limit {
		t.Fatalf("omitted_results = %v, want the %d results the ranking ceiling dropped", coverage["omitted_results"], universe-limit)
	}
}

// TestImpactAdmitsPythonPathsWithoutAGoModule pins decision 0015: the Go
// module is a precondition for .go paths only; a .py path in a module-free
// repository resolves its reverse importers as the oracle does.
func TestImpactAdmitsPythonPathsWithoutAGoModule(t *testing.T) {
	root := t.TempDir()
	if command := testGitOptional(t, root, "init", "-q"); command != "" {
		t.Skipf("git init unsupported: %s", command)
	}
	testGit(t, root, "config", "user.email", "corvint@example.test")
	testGit(t, root, "config", "user.name", "Corvint Test")
	files := map[string]string{
		"src/pkg/__init__.py": "VERSION = \"1\"\n",
		"src/pkg/engine.py":   "def run() -> str:\n    return \"engine\"\n",
		"tools/dotted.py":     "from src.pkg.engine import run\n\n\ndef main() -> str:\n    return run()\n",
		"tools/main.go":       "package main\n\nfunc main() {}\n",
	}
	for relative, content := range files {
		writeTestFile(t, root, relative, content)
	}
	testGit(t, root, "add", ".")
	testGit(t, root, "commit", "-qm", "module-free python fixture")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	receipt, err := Impact(index, []string{"src/pkg/engine.py"}, 10)
	if err != nil {
		t.Fatalf("python path without module: %v", err)
	}
	ids := make([]string, 0)
	for _, raw := range anySlice(receipt["results"]) {
		ids = append(ids, raw.(map[string]any)["id"].(string))
	}
	if strings.Join(ids, ",") != "src/pkg/engine.py,tools/dotted.py" {
		t.Fatalf("results = %v", ids)
	}
	var unsupported *Error
	if _, err := Impact(index, []string{"tools/main.go"}, 10); !errors.As(err, &unsupported) || unsupported.Code != "unsupported-impact-repository" {
		t.Fatalf("go path without module: %v", err)
	}
	if _, err := Impact(index, []string{"src/pkg/engine.py", "tools/main.go"}, 10); !errors.As(err, &unsupported) || unsupported.Code != "unsupported-impact-repository" {
		t.Fatalf("mixed paths without module: %v", err)
	}
}
