package contextindex

import (
	"bytes"
	"context"
	"errors"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// pinParityRepository is built to reach every branch of the pin decision, so a
// comparison over it is a comparison of the decision and not only of the happy
// path: a clean regular file and a clean executable (both pinned from the
// worktree), a tracked file modified in the worktree and a tracked file deleted
// from it (both dirty, so both pinned from the committed blob), a symlink
// (never eligible), two paths that share one blob oid, an empty file, and a
// generated-header file whose exclusion is decided from the pinned prefix.
//
// It returns the root and the path made unreadable, which reaches the residual
// blob branch because the worktree cannot supply bytes.
func pinParityRepository(t *testing.T) (string, string) {
	t.Helper()
	root := t.TempDir()
	testGit(t, root, "init", "-q")
	testGit(t, root, "config", "user.email", "corvint@example.test")
	testGit(t, root, "config", "user.name", "Corvint Test")
	files := map[string]string{
		"go.mod": "module example.test/pin\n\ngo 1.27.0\n",
		"testing/features.yaml": "features:\n" +
			"  - id: session-revocation\n    area: auth\n    summary: Revoke an expired device session.\n    adr: []\n    applies: [server]\n    status: shipped\n",
		"testing/scenarios.yaml": "scenarios:\n" +
			"  - id: revoked-device\n    area: auth\n    summary: Expired device session is revoked.\n    features: [session-revocation]\n    applies: [server]\n    status: shipped\n",
		"internal/auth/session.go":      "package auth\n\n// feature:session-revocation\nfunc EnforceSessionRevocation() bool { return true }\n",
		"internal/auth/session_test.go": "package auth\n\nfunc TestEnforceSessionRevocation() {}\n",
		"internal/auth/modified.go":     "package auth\n\nfunc SessionHeartbeat() int { return 1 }\n",
		"internal/auth/deleted.go":      "package auth\n\nfunc SessionExpiry() int { return 2 }\n",
		"internal/auth/unreadable.go":   "package auth\n\nfunc SessionRevocationAudit() int { return 3 }\n",
		"internal/copy/one.go":          "package copyone\n\nfunc SharedBlobDeclaration() {}\n",
		"internal/copy/two.go":          "package copyone\n\nfunc SharedBlobDeclaration() {}\n",
		"internal/empty/empty.go":       "",
		"internal/gen/table.go":         "// Code generated by corvint. DO NOT EDIT.\n\npackage gen\n\nfunc GeneratedSessionTable() {}\n",
		"script/run.sh":                 "#!/bin/sh\necho session revocation\n",
		"docs/session-revocation.md":    "# Session revocation\n\nstatus: shipped\n\nSee internal/auth/session.go for the enforcement path.\n",
	}
	for path, content := range files {
		writeTestFile(t, root, path, content)
	}
	if err := os.Chmod(filepath.Join(root, "script/run.sh"), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.Symlink("session.go", filepath.Join(root, "internal/auth/link.go")); err != nil {
		t.Skipf("symlinks unavailable: %v", err)
	}
	testGit(t, root, "add", ".")
	testGit(t, root, "commit", "-qm", "enforce expired device session revocation")

	writeTestFile(t, root, "internal/auth/modified.go", "package auth\n\nfunc SessionHeartbeat() int { return 99 }\n")
	if err := os.Remove(filepath.Join(root, "internal/auth/deleted.go")); err != nil {
		t.Fatal(err)
	}
	unreadable := filepath.Join(root, "internal/auth/unreadable.go")
	if err := os.Chmod(unreadable, 0o000); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { _ = os.Chmod(unreadable, 0o644) })
	if _, err := os.ReadFile(unreadable); err == nil {
		t.Skip("this process can read a 0000 file, so the diverged branch is unreachable here")
	} else if !errors.Is(err, os.ErrPermission) {
		t.Fatalf("unreadable fixture failed for the wrong reason: %v", err)
	}
	return root, "internal/auth/unreadable.go"
}

// withEagerBlobs builds one index over the construction that read every
// candidate's blob up front. It is not parallel-safe by construction, which is
// why the parity tests are the only callers.
func withEagerBlobs[Result any](t *testing.T, build func() Result) Result {
	t.Helper()
	buildEagerBlobs = true
	defer func() { buildEagerBlobs = false }()
	return build()
}

// TestDeferredBlobPinIsByteIdenticalToEagerPin is the standing proof that not
// reading a blob the clean worktree already pinned changes nothing an index
// records. A worktree copy is used only when it hashes to the entry's recorded
// oid, which is what makes it that blob; the deferral acts on exactly that
// verdict, so every source, exclusion and dirty path must be identical.
func TestDeferredBlobPinIsByteIdenticalToEagerPin(t *testing.T) {
	root, _ := pinParityRepository(t)
	roots := append([]string{root}, parityRepositoriesFromEnvironment()...)
	for _, repository := range roots {
		eager := withEagerBlobs(t, func() *Index {
			built, err := BuildEval(context.Background(), repository)
			if err != nil {
				t.Fatalf("eager BuildEval(%s): %v", repository, err)
			}
			return built
		})
		deferred, err := BuildEval(context.Background(), repository)
		if err != nil {
			t.Fatalf("deferred BuildEval(%s): %v", repository, err)
		}
		assertIndexEvidenceEqual(t, repository, eager, deferred)
		t.Logf("%s: %d sources, %d exclusions, %d dirty paths identical",
			repository, len(deferred.Sources), len(deferred.Exclusions), len(deferred.DirtyPaths))
	}
}

// TestDeferredBlobPinEmitsIdenticalReceipts carries the comparison all the way
// to the bytes a consumer reads, across the same contrasting query and budget
// matrix the keep-set parity test uses, so a divergence that survived the
// source comparison would still be caught where it is observable.
func TestDeferredBlobPinEmitsIdenticalReceipts(t *testing.T) {
	root, _ := pinParityRepository(t)
	// The clean fixture is carried alongside the dirty one: a clean repository
	// is the case the deferral is entirely about, and it is the only one that
	// reaches READY and OUT_OF_SCOPE.
	roots := append([]string{root, evalQueryRepository(t)}, parityRepositoriesFromEnvironment()...)
	for _, repository := range roots {
		eager := withEagerBlobs(t, func() *Index {
			built, err := BuildEval(context.Background(), repository)
			if err != nil {
				t.Fatalf("eager BuildEval(%s): %v", repository, err)
			}
			return built
		})
		deferred, err := BuildEval(context.Background(), repository)
		if err != nil {
			t.Fatalf("deferred BuildEval(%s): %v", repository, err)
		}
		compared, states := compareReceiptMatrix(t, repository, eager, deferred)
		if compared == 0 {
			t.Fatalf("no receipt could be compared in %s", repository)
		}
		t.Logf("%s: %d receipts byte-identical, states %v", repository, compared, states)
	}
}

// TestDeferredBlobPinReadsFewerBlobs is the negative control for the two tests
// above: it proves they compare two genuinely different constructions. A parity
// test between a branch and itself passes for free, so the switch is only
// evidence while the deferred build is demonstrably asking Git for less. It
// also pins what the residual set must still contain -- the dirty, deleted,
// symlinked and unreadable entries -- because a deferral that dropped one of
// those would silently substitute worktree bytes for committed ones.
func TestDeferredBlobPinReadsFewerBlobs(t *testing.T) {
	root, unreadable := pinParityRepository(t)

	before := blobBatchEntries.Load()
	eager := withEagerBlobs(t, func() *Index {
		built, err := BuildEval(context.Background(), root)
		if err != nil {
			t.Fatalf("eager BuildEval: %v", err)
		}
		return built
	})
	eagerFetched := blobBatchEntries.Load() - before

	before = blobBatchEntries.Load()
	deferred, err := BuildEval(context.Background(), root)
	if err != nil {
		t.Fatalf("deferred BuildEval: %v", err)
	}
	deferredFetched := blobBatchEntries.Load() - before

	if eagerFetched == 0 {
		t.Fatal("the eager build fetched no blob, so the switch is not restoring the old construction")
	}
	if deferredFetched >= eagerFetched {
		t.Fatalf("deferred build fetched %d blobs against the eager build's %d: the parity tests are comparing one construction with itself",
			deferredFetched, eagerFetched)
	}
	t.Logf("blobs fetched: eager %d, deferred %d", eagerFetched, deferredFetched)

	// The residual set is not merely smaller: every entry the worktree cannot
	// pin has to be in it, and each of these reaches the residual by a
	// different predicate.
	for _, path := range []string{"internal/auth/modified.go", "internal/auth/deleted.go", unreadable} {
		if !contains(setOf(deferred.DirtyPaths), path) {
			t.Errorf("%s is not recorded dirty by the deferred build: %v", path, deferred.DirtyPaths)
		}
	}
	assertIndexEvidenceEqual(t, root, eager, deferred)
}

// TestDeferredBlobPinKeepsWholeSetAdmission pins that narrowing the batch did
// not narrow the two refusals that answer for the whole candidate set. Both are
// verdicts about the repository, so they may not depend on how much of it the
// worktree happened to pin.
func TestDeferredBlobPinKeepsWholeSetAdmission(t *testing.T) {
	oversized := []treeEntry{{path: "big.go", oid: strings.Repeat("a", 40), size: maxBatchBytes, mode: "100644"}}
	if err := readOnlyResidual(t, oversized, nil); err == nil {
		t.Error("an aggregate over the batch bound was admitted when nothing was needed from it")
	}
	conflicting := []treeEntry{
		{path: "one.go", oid: strings.Repeat("b", 40), size: 10, mode: "100644"},
		{path: "two.go", oid: strings.Repeat("b", 40), size: 11, mode: "100644"},
	}
	if err := readOnlyResidual(t, conflicting, nil); err == nil {
		t.Error("one oid recorded at two sizes was admitted when nothing was needed from it")
	}
}

func readOnlyResidual(t *testing.T, all, needed []treeEntry) error {
	t.Helper()
	_, err := readResidualBlobs(context.Background(), t.TempDir(), all, needed)
	return err
}

func assertIndexEvidenceEqual(t *testing.T, repository string, eager, deferred *Index) {
	t.Helper()
	if len(eager.Sources) != len(deferred.Sources) {
		t.Fatalf("%s: %d sources eager against %d deferred", repository, len(eager.Sources), len(deferred.Sources))
	}
	for path, want := range eager.Sources {
		got, ok := deferred.Sources[path]
		if !ok {
			t.Fatalf("%s: %s pinned eagerly and missing from the deferred build", repository, path)
		}
		if got.BlobHash != want.BlobHash || got.Mode != want.Mode {
			t.Fatalf("%s: %s identity diverged: %+v against %+v", repository, path, want, got)
		}
		if !bytes.Equal(got.Data, want.Data) {
			t.Fatalf("%s: %s bytes diverged (%d eager, %d deferred)", repository, path, len(want.Data), len(got.Data))
		}
	}
	if !reflect.DeepEqual(eager.Exclusions, deferred.Exclusions) {
		t.Fatalf("%s: exclusions diverged:\n eager = %v\n deferred = %v", repository, eager.Exclusions, deferred.Exclusions)
	}
	if !reflect.DeepEqual(eager.DirtyPaths, deferred.DirtyPaths) {
		t.Fatalf("%s: dirty paths diverged:\n eager = %v\n deferred = %v", repository, eager.DirtyPaths, deferred.DirtyPaths)
	}
	if !reflect.DeepEqual(eager.Symbols, deferred.Symbols) {
		t.Fatalf("%s: symbols diverged", repository)
	}
	if !reflect.DeepEqual(eager.Documents, deferred.Documents) {
		t.Fatalf("%s: documents diverged", repository)
	}
	if !reflect.DeepEqual(eager.Markers, deferred.Markers) {
		t.Fatalf("%s: markers diverged", repository)
	}
	if !reflect.DeepEqual(eager.Imports, deferred.Imports) {
		t.Fatalf("%s: imports diverged", repository)
	}
}

// compareReceiptMatrix emits the user-prompt receipt from both indexes over the
// shared task and budget matrix and compares the bytes.
func compareReceiptMatrix(t *testing.T, repository string, expectedIndex, actualIndex *Index) (int, map[string]int) {
	t.Helper()
	expected := emitParityReceipts(expectedIndex)
	actual := emitParityReceipts(actualIndex)
	return compareParityReceipts(t, repository, "expected", "  actual", expected, actual)
}

// parityRepositoriesFromEnvironment widens every parity test in this package
// over real repositories, which are the only place the fixtures' branches
// appear at scale.
func parityRepositoriesFromEnvironment() []string {
	value := os.Getenv("CORVINT_EVAL_PARITY_REPOS")
	if value == "" {
		return nil
	}
	return strings.Split(value, ":")
}

func setOf(values []string) map[string]struct{} {
	result := make(map[string]struct{}, len(values))
	for _, value := range values {
		result[value] = struct{}{}
	}
	return result
}
