package contextindex

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"runtime"
	"sort"
	"strings"
	"testing"
	"time"
	"unicode/utf8"
)

// roleFixtures is one source per extraction rule, keyed by path.
var roleFixtures = map[string]string{
	"go/doc.go":       "// Package parser reads task text into terms.\n// It keeps no state.\npackage parser\n",
	"go/license.go":   "// Copyright 2026 Example.\n\n// Package frob frobnicates values.\npackage frob\n",
	"go/directive.go": "//go:build linux\n\n// Package unix wraps the kernel calls. It is\n// linux only.\n//go:generate stringer\npackage unix\n",
	"go/decl.go":      "// Copyright 2026 Example.\n\npackage store\n\nimport \"os\"\n\n// Open opens the ledger file.\nfunc Open() {}\n",
	"go/block.go":     "/*\nPackage block is\ndocumented in a block.\n*/\npackage block\n",
	"go/generated.go": "// Code generated by stringer. DO NOT EDIT.\npackage gen\n",
	"go/none.go":      "package none\n\nfunc run() {}\n",
	// Review fix: a `*/` after code, or a scan crossing another comment, is
	// no doc comment, and a `*/` per declaration costs linear work.
	"go/misattributed.go": "package p\n\n/*\nInternal notes about parsing.\n*/\n\nvar limit = 10 /* bytes */\nfunc Parse() {}\n",
	"go/trailing.go":      "package p\n\n/*\nInternal notes\n*/\nimport \"os\" /* os */\nfunc Parse() {}\n",
	"go/quadratic.go":     roleQuadraticInput,
	"py/module.py":        "#!/usr/bin/env python\n# -*- coding: utf-8 -*-\n\"\"\"Command line entry points.\n\nMore detail.\n\"\"\"\nimport os\n",
	"py/oneline.py":       "'''Fixture helpers for the parser tests.'''\n",
	"py/raw.py":           "r\"\"\"\n    Regex helpers.\n\"\"\"\n",
	"py/code.py":          "import os\n\"\"\"Not a docstring.\"\"\"\n",
	"rs/lib.rs":           "#![deny(missing_docs)]\n//! # Tokio\n//!\n//! A runtime for writing reliable applications.\n\nmod io;\n",
	"rs/item.rs":          "use std::io;\n\n/// Parses a command line.\npub fn parse() {}\n",
	"js/overview.js":      "/**\n * @license MIT\n */\n/**\n * @fileoverview Rule to flag unused variables.\n * @author Someone\n */\nmodule.exports = {};\n",
	"java/Client.java":    "/*\n * Copyright 2026 the original authors.\n */\npackage org.example;\n\n/**\n * HTTP client for the registry. Thread safe.\n */\npublic class Client {}\n",
	"ts/cut.ts":           "/** " + strings.Repeat("word ", 31) + "abcdé tail */\nexport {}\n",
	"docs/readme.md":      "<!-- Package docs. -->\n# Readme\n",
}

// roleQuadraticInput is 64 KiB of `x */` lines each above a declaration,
// under one opening `/*`.
var roleQuadraticInput = "/*\n" + strings.Repeat("x */\nconst a\n", 5041)

func roleGoldenLines() []byte {
	paths := make([]string, 0, len(roleFixtures))
	for name := range roleFixtures {
		paths = append(paths, name)
	}
	sort.Strings(paths)
	var out bytes.Buffer
	for _, name := range paths {
		summary, ok := extractRoleSummary(name, roleFixtures[name])
		if !ok {
			fmt.Fprintf(&out, "%s\t-\n", name)
			continue
		}
		fmt.Fprintf(&out, "%s\t%d-%d\t%s\n", name, summary.start, summary.end, summary.text)
	}
	return out.Bytes()
}

func TestRoleSummaryExtractionIsCommentOnlyAndReproducible(t *testing.T) {
	t.Run("TCP-V0-039", func(t *testing.T) {
		first, second := roleGoldenLines(), roleGoldenLines()
		if !bytes.Equal(first, second) {
			t.Fatalf("two extractions differ:\n%s\n%s", first, second)
		}
		golden, err := os.ReadFile("testdata/role-summary-golden.tsv")
		if err != nil {
			t.Fatal(err)
		}
		if !bytes.Equal(first, golden) {
			t.Fatalf("role summaries drifted from golden:\n%s", first)
		}
	})
}

func TestRoleSummaryBounds(t *testing.T) {
	t.Run("TCP-V0-039", func(t *testing.T) {
		summary, ok := extractRoleSummary("ts/cut.ts", roleFixtures["ts/cut.ts"])
		if !ok || len(summary.text) != roleSummaryMaxBytes-1 || !strings.HasSuffix(summary.text, "abcd") || !utf8.ValidString(summary.text) {
			t.Fatalf("summary = %q, %v", summary.text, ok)
		}
		late := strings.Repeat("\n", roleSummaryScanBytes) + "// Package late is past the scan bound.\npackage late\n"
		if summary, ok := extractRoleSummary("late.go", late); ok {
			t.Fatalf("read past the scan bound: %#v", summary)
		}
		scores := make([]float64, roleCandidateCap+10)
		for source := range scores {
			scores[source] = float64(source%3 + 1)
		}
		var before, after runtime.MemStats
		runtime.GC()
		runtime.ReadMemStats(&before)
		started := time.Now()
		_, ok = extractRoleSummary("go/quadratic.go", roleQuadraticInput)
		elapsed := time.Since(started)
		runtime.ReadMemStats(&after)
		if allocated := after.TotalAlloc - before.TotalAlloc; ok || allocated > 16<<20 || elapsed > 100*time.Millisecond {
			t.Fatalf("pathological input: ok=%v allocated=%d elapsed=%v", ok, allocated, elapsed)
		}
		candidates := roleCandidates(scores)
		if len(candidates) != roleCandidateCap || scores[candidates[0]] != 3 || candidates[0] != 2 || candidates[1] != 5 {
			t.Fatalf("candidates = %d, head %v", len(candidates), candidates[:2])
		}
	})
}

// roleFixtureIndex holds two sources whose bodies carry the task terms
// once each; only ledger.go says so in its package doc comment, and
// helpers.go's comment is attached to no declaration.
func roleFixtureIndex(t *testing.T) *Index {
	t.Helper()
	root := impactRepositoryWithFiles(t, map[string]string{
		"go.mod":             "module example.test/roles\n\ngo 1.27.0\n",
		"AGENTS.md":          "# Standing instructions\n\nRead before editing.\n",
		"store/ledger.go":    "// Package store appends ledger entries.\npackage store\n\nfunc write() {}\n",
		"store/helpers.go":   "package store\n\n// store appends ledger entries here\n\nfunc helper() {}\n",
		"store/unrelated.go": "package store\n\n// nothing\nfunc other() {}\n",
	})
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	return index
}

func TestContextRolesExplainAndNeverOutrankAuthority(t *testing.T) {
	for _, id := range []string{"TCP-V0-040", "TCP-V0-041"} {
		t.Run(id, func(t *testing.T) {
			t.Setenv("CORVINT_CONTEXT_ROLES", "on")
			index := roleFixtureIndex(t)
			packet, err := TaskContext(context.Background(), index, "where does the store append ledger entries? appends", "", 20)
			if err != nil {
				t.Fatal(err)
			}
			results := mapsFromAny(packet["results"])
			if len(results) < 3 || results[0]["id"] != "AGENTS.md" || results[1]["id"] != "store/ledger.go" {
				t.Fatalf("order = %#v", results)
			}
			row := results[1]
			entry := mapsFromAny(row["evidence"])[0]
			if row["kind"] != "lexical" || row["score"].(int) >= results[0]["score"].(int) || entry["authority"] != "vocabulary" {
				t.Fatalf("role row outranks authority: %#v", row)
			}
			want := "role: \"Package store appends ledger entries.\" (store/ledger.go:1-1) matches `appends`, `entries`, `ledger`, `store`; "
			if reason := entry["reason"].(string); !strings.HasPrefix(reason, want) {
				t.Fatalf("reason = %q", reason)
			}
			other := mapsFromAny(results[2]["evidence"])[0]["reason"].(string)
			if strings.Contains(other, "role: ") {
				t.Fatalf("row without a role line carries one: %q", other)
			}
		})
	}
}

func TestContextRolesDefaultBytes(t *testing.T) {
	t.Run("TCP-V0-040", func(t *testing.T) {
		index := recipeFixtureIndex(t)
		golden, err := os.ReadFile("testdata/context-recipe-default-golden.json")
		if err != nil {
			t.Fatal(err)
		}
		for _, flag := range []string{"", "off", "unknown"} {
			t.Setenv("CORVINT_CONTEXT_ROLES", flag)
			if compiler := newTaskContextCompiler(index, "ledger", ""); compiler.roles {
				t.Fatalf("flag %q enabled roles", flag)
			}
			packet := recipePacket(t, index, "", recipeFixtureTask)
			encoded, err := json.MarshalIndent(packet, "", "  ")
			if err != nil {
				t.Fatal(err)
			}
			if !bytes.Equal(append(encoded, '\n'), golden) {
				t.Fatalf("flag %q changed golden packet bytes", flag)
			}
		}
	})
}
