package contextindex

import (
	"context"
	"fmt"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func taskContextFixture(t *testing.T) *Index {
	t.Helper()
	root := impactRepositoryWithFiles(t, map[string]string{
		"go.mod":                 "module example.test/fixture\n\ngo 1.27.0\n",
		"cache/cache.go":         "package cache\n\nfunc Demux() string { return \"demux\" }\n",
		"cache/demux.go":         "package cache\n\nfunc Split(key string) string { return key }\n",
		"cache/demux_test.go":    "package cache\n\nfunc TestSplit() { _ = Split(\"k\") }\n",
		"cache/notes.md":         "# cache\n\nThe cache demuxes keys.\n",
		"server/server.go":       "package server\n\nimport \"example.test/fixture/cache\"\n\nfunc Run() string { return cache.Demux() }\n",
		"docs/unrelated.md":      "# nothing\n\nirrelevant prose\n",
		"pkg/other/other.go":     "package other\n\nfunc Other() {}\n",
		"testing/features.yaml":  "features: []\n",
		"cache/README.md":        "cache package\n",
		"cache/gen.go":           "// Code generated by fixture. DO NOT EDIT.\n\npackage cache\n\nfunc Gen() {}\n",
		"legacy/Legacy.java":     "package legacy;\n\npublic class Legacy {}\n",
		"legacy/LegacyTest.java": "package legacy;\n\npublic class LegacyTest {}\n",
	})
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	return index
}

func contextRowsByKind(t *testing.T, packet map[string]any) map[string][]string {
	t.Helper()
	found := map[string][]string{}
	for _, item := range mapsFromAny(packet["results"]) {
		found[item["kind"].(string)] = append(found[item["kind"].(string)], item["id"].(string))
	}
	return found
}

func TestTaskContextKeepsTheSubjectOutOfTheResults(t *testing.T) {
	index := taskContextFixture(t)
	packet, err := TaskContext(context.Background(), index, "Reviewer asks whether `Split` handles empty keys in cache/demux.go", "cache/demux.go", 20)
	if err != nil {
		t.Fatal(err)
	}
	if packet["state"] != "READY" {
		t.Fatalf("state = %v", packet["state"])
	}
	subject := packet["subject"].(map[string]any)
	if subject["path"] != "cache/demux.go" {
		t.Fatalf("subject = %v", subject)
	}
	found := contextRowsByKind(t, packet)
	for kind, ids := range found {
		for _, id := range ids {
			if id == "cache/demux.go" {
				t.Fatalf("subject appears as a %s result", kind)
			}
		}
	}
	if len(found["pair"]) == 0 || found["pair"][0] != "cache/demux_test.go" {
		t.Fatalf("pair rows = %v, want the test counterpart first", found["pair"])
	}
	// The fixture's one commit co-changes every file and cache.go names the
	// subject's stem, so the cache siblings arrive through an earlier slot
	// (reference or cochange); one of the three must carry them.
	for _, sibling := range []string{"cache/cache.go", "cache/notes.md"} {
		if !slices.Contains(found["reference"], sibling) && !slices.Contains(found["cochange"], sibling) && !slices.Contains(found["sibling"], sibling) {
			t.Fatalf("sibling %s absent: %v", sibling, found)
		}
	}
}

func TestTaskContextAdmitsReverseImportersAndMentionedPaths(t *testing.T) {
	index := taskContextFixture(t)
	packet, err := TaskContext(context.Background(), index, "Change Demux in cache/cache.go and rerun the suite", "cache/cache.go", 20)
	if err != nil {
		t.Fatal(err)
	}
	found := contextRowsByKind(t, packet)
	if len(found["reverse-import"]) != 1 || found["reverse-import"][0] != "server/server.go" {
		t.Fatalf("reverse-import rows = %v", found["reverse-import"])
	}
	if len(found["mentioned"]) != 0 {
		t.Fatalf("the subject was admitted as a mentioned row: %v", found["mentioned"])
	}
	retrieval, err := TaskContext(context.Background(), index, "Does server.go still compile?", "", 20)
	if err != nil {
		t.Fatal(err)
	}
	found = contextRowsByKind(t, retrieval)
	if len(found["mentioned"]) != 1 || found["mentioned"][0] != "server/server.go" {
		t.Fatalf("mentioned rows = %v, want server.go resolved by unambiguous basename", found["mentioned"])
	}
}

func TestTaskContextRetrievalShapeAndNoCandidates(t *testing.T) {
	index := taskContextFixture(t)
	packet, err := TaskContext(context.Background(), index, "Where is `Other` defined?", "", 5)
	if err != nil {
		t.Fatal(err)
	}
	if packet["subject"] != nil {
		t.Fatalf("retrieval packet carries a subject: %v", packet["subject"])
	}
	found := contextRowsByKind(t, packet)
	if len(found["definition"]) != 1 || found["definition"][0] != "pkg/other/other.go" {
		t.Fatalf("definition rows = %v", found["definition"])
	}
	empty, err := TaskContext(context.Background(), index, "zzzz qqqq", "", 5)
	if err != nil {
		t.Fatal(err)
	}
	if empty["state"] != "NO_CANDIDATES" || len(empty["results"].([]any)) != 0 {
		t.Fatalf("empty packet = %v", empty)
	}
	if _, err := TaskContext(context.Background(), index, "task", "missing.go", 5); err == nil {
		t.Fatal("untracked subject was admitted")
	}
	excluded, err := TaskContext(context.Background(), index, "Regenerate `Gen`", "cache/gen.go", 5)
	if err != nil {
		t.Fatalf("excluded subject refused: %v", err)
	}
	subject := excluded["subject"].(map[string]any)
	if _, hashed := subject["blob_hash"]; hashed || subject["path"] != "cache/gen.go" {
		t.Fatalf("excluded subject = %v", subject)
	}
	gapIndex := slices.IndexFunc(index.Exclusions, func(item Exclusion) bool { return item.Path == "cache/gen.go" })
	if gapIndex < 0 {
		t.Fatalf("fixture drifted: cache/gen.go is no longer in index.Exclusions")
	}
	if gap, _ := subject["evidence_gap"].(string); gap != index.Exclusions[gapIndex].Reason {
		t.Fatalf("evidence_gap for an excluded subject = %q, want the recorded exclusion reason %q", gap, index.Exclusions[gapIndex].Reason)
	}
	unread, err := TaskContext(context.Background(), index, "Rename the legacy class", "legacy/Legacy.java", 5)
	if err != nil {
		t.Fatalf("unread-kind subject refused: %v", err)
	}
	if pairs := contextRowsByKind(t, unread)["pair"]; len(pairs) != 1 || pairs[0] != "legacy/LegacyTest.java" {
		t.Fatalf("pair rows for an unread subject = %v", pairs)
	}
	// legacy/LegacyTest.java is itself unadmitted, so its result row's
	// evidence must disclose that gap instead of pairing an empty blob_hash
	// with the pair relation's own high confidence (AGENTS.md invariant 2).
	var pairEvidence map[string]any
	for _, item := range mapsFromAny(unread["results"]) {
		if item["kind"] == "pair" && item["id"] == "legacy/LegacyTest.java" {
			pairEvidence = mapsFromAny(item["evidence"])[0]
		}
	}
	if pairEvidence == nil {
		t.Fatalf("pair result for legacy/LegacyTest.java missing from results: %v", unread["results"])
	}
	if pairEvidence["blob_hash"] != "" || pairEvidence["confidence"] != "low" {
		t.Fatalf("unpinned pair evidence = %v, want an empty blob_hash paired with a low confidence", pairEvidence)
	}
	if gap, ok := pairEvidence["evidence_gap"].(string); !ok || gap == "" {
		t.Fatalf("unpinned pair evidence_gap = %v, want a non-empty explanation", pairEvidence)
	}
	// legacy/Legacy.java's suffix is not admitted, so admittedEntries never
	// pins it and never records an Exclusion either; its evidence_gap must
	// still say something rather than silently omitting the field.
	unreadSubject := unread["subject"].(map[string]any)
	if _, hashed := unreadSubject["blob_hash"]; hashed {
		t.Fatalf("unread subject unexpectedly carries a blob_hash: %v", unreadSubject)
	}
	if slices.ContainsFunc(index.Exclusions, func(item Exclusion) bool { return item.Path == "legacy/Legacy.java" }) {
		t.Fatalf("fixture drifted: legacy/Legacy.java is now in index.Exclusions")
	}
	if gap, ok := unreadSubject["evidence_gap"].(string); !ok || gap == "" {
		t.Fatalf("evidence_gap for a suffix-omitted subject = %v, want a non-empty explanation", unreadSubject)
	}
}

func TestTaskContextAdmitsCoChangedPathsAndIgnoresBulkCommits(t *testing.T) {
	root := impactRepositoryWithFiles(t, map[string]string{
		"go.mod":              "module example.test/fixture\n\ngo 1.27.0\n",
		"cache/cache.go":      "package cache\n\nfunc Demux() string { return \"demux\" }\n",
		"docs/guide.md":       "# guide\n",
		"other/cache_test.go": "package other\n\nfunc TestDemux() {}\n",
	})
	writeTestFile(t, root, "cache/cache.go", "package cache\n\nfunc Demux() string { return \"demux2\" }\n")
	writeTestFile(t, root, "docs/guide.md", "# guide\n\ndemux2\n")
	testGit(t, root, "add", ".")
	testGit(t, root, "commit", "-qm", "change demux and its guide")
	writeTestFile(t, root, "cache/cache.go", "package cache\n\nfunc Demux() string { return \"demux3\" }\n")
	for index := 0; index < contextCochangeYoungCap; index++ {
		writeTestFile(t, root, fmt.Sprintf("bulk/file%02d.txt", index), "bulk\n")
	}
	writeTestFile(t, root, "cache/util.go", "package cache\n\nfunc Util() {}\n")
	testGit(t, root, "add", ".")
	testGit(t, root, "commit", "-qm", "bulk sweep")
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	packet, err := TaskContext(context.Background(), index, "Adjust the demux return value", "cache/cache.go", 20)
	if err != nil {
		t.Fatal(err)
	}
	found := contextRowsByKind(t, packet)
	pair := mapsFromAny(packet["results"])[0]
	if pair["id"] != "other/cache_test.go" || mapsFromAny(pair["evidence"])[0]["confidence"] != "medium" {
		t.Fatalf("a counterpart elsewhere in the tree must be a medium pair row: %v", pair)
	}
	if len(found["cochange"]) != 2 || found["cochange"][0] != "docs/guide.md" || found["cochange"][1] != "go.mod" {
		t.Fatalf("cochange rows = %v, want docs/guide.md (two commits) then go.mod (one), and no bulk path", found["cochange"])
	}
	row := mapsFromAny(packet["results"])[len(found["pair"])]
	reason := mapsFromAny(row["evidence"])[0]["reason"]
	if row["kind"] != "cochange" || reason != "changed with cache/cache.go in 2 of 2 recent commits (commits over 50 paths ignored)" {
		t.Fatalf("cochange row = %v", row)
	}
	if len(found["sibling"]) != 1 || found["sibling"][0] != "cache/util.go" {
		t.Fatalf("sibling rows = %v, want cache/util.go (added only in the ignored bulk commit)", found["sibling"])
	}
}

// TestTaskContextCochangeSkipsTheShallowBoundaryCommit: a shallow clone's
// boundary commit lists every path it holds, a diff against a parent Git does
// not have, so it must not count as a commit that changed them together.
func TestTaskContextCochangeSkipsTheShallowBoundaryCommit(t *testing.T) {
	source := impactRepositoryWithFiles(t, map[string]string{
		"go.mod":         "module example.test/fixture\n\ngo 1.27.0\n",
		"cache/cache.go": "package cache\n\nfunc Demux() string { return \"demux\" }\n",
		"docs/guide.md":  "# guide\n",
	})
	writeTestFile(t, source, "cache/cache.go", "package cache\n\nfunc Demux() string { return \"demux2\" }\n")
	writeTestFile(t, source, "docs/guide.md", "# guide\n\ndemux2\n")
	testGit(t, source, "add", ".")
	testGit(t, source, "commit", "-qm", "change demux and its guide")
	writeTestFile(t, source, "cache/cache.go", "package cache\n\nfunc Demux() string { return \"demux3\" }\n")
	writeTestFile(t, source, "go.mod", "module example.test/fixture\n\ngo 1.27.1\n")
	testGit(t, source, "add", ".")
	testGit(t, source, "commit", "-qm", "change demux and go.mod")
	root := filepath.Join(t.TempDir(), "clone")
	testGit(t, source, "clone", "-q", "--depth", "2", "file://"+source, root)
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	packet, err := TaskContext(context.Background(), index, "Adjust the demux return value", "cache/cache.go", 20)
	if err != nil {
		t.Fatal(err)
	}
	found := contextRowsByKind(t, packet)
	if len(found["cochange"]) != 1 || found["cochange"][0] != "go.mod" {
		t.Fatalf("cochange rows = %v, want only go.mod: the boundary commit is not a co-change", found["cochange"])
	}
	for _, row := range mapsFromAny(packet["results"]) {
		reason := mapsFromAny(row["evidence"])[0]["reason"]
		if row["kind"] == "cochange" && reason != "changed with cache/cache.go in 1 of 1 recent commits (commits over 50 paths ignored)" {
			t.Fatalf("cochange row = %v", row)
		}
	}
}

func TestCochangeCommitCapTightensWithRepositoryAge(t *testing.T) {
	for commits, want := range map[int]int{0: 50, 3: 50, 50: 50, 100: 36, 125: 29, 200: 8, 400: 8} {
		if got := cochangeCommitCap(commits); got != want {
			t.Errorf("cap(%d commits) = %d, want %d", commits, got, want)
		}
	}
}

func TestTaskContextRanksCorroboratedRowsFirst(t *testing.T) {
	index := taskContextFixture(t)
	// cache/notes.md is co-changed, a sibling, and a documentation match;
	// docs/unrelated.md is co-changed only, and the co-change slot lists it
	// after notes.md by path.
	packet, err := TaskContext(context.Background(), index, "The cache demuxes keys; check the notes", "cache/demux.go", 20)
	if err != nil {
		t.Fatal(err)
	}
	rows := mapsFromAny(packet["results"])
	position := map[string]int{}
	for index, row := range rows {
		position[row["id"].(string)] = index
	}
	if position["cache/notes.md"] > position["docs/unrelated.md"] {
		for _, row := range rows {
			t.Logf("%v %v %v", row["id"], row["kind"], row["summary"])
		}
		t.Fatalf("a row two relations admit must rank above a row one admits: %v", position)
	}
	for _, row := range rows {
		if row["id"] == "cache/notes.md" {
			if summary := row["summary"].(string); !strings.HasSuffix(summary, "; also sibling, documentation") {
				t.Fatalf("summary must name the corroborating relation: %q", summary)
			}
			if len(mapsFromAny(row["evidence"])) != 1 {
				t.Fatalf("one evidence row is kept: %v", row["evidence"])
			}
		}
	}
}

func TestTaskContextRowsCarryAnAction(t *testing.T) {
	index := taskContextFixture(t)
	packet, err := TaskContext(context.Background(), index, "Reviewer asks whether `Split` handles empty keys in cache/demux.go", "cache/demux.go", 20)
	if err != nil {
		t.Fatal(err)
	}
	cases := []struct{ name string }{{name: "TCP-V0-003 every row says what to do with the file"}}
	t.Run(cases[0].name, func(t *testing.T) {
		for _, row := range mapsFromAny(packet["results"]) {
			action, _ := row["action"].(string)
			if action == "" {
				t.Fatalf("every row says what to do with the file: %v", row)
			}
			if row["id"] == "cache/demux_test.go" && !strings.HasPrefix(action, "Update this test:") {
				t.Fatalf("a test counterpart's action names the test: %q", action)
			}
			if row["kind"] == "definition" && !strings.Contains(action, "`Split`") {
				t.Fatalf("a definition's action names the identifier: %q", action)
			}
		}
	})
}

func TestTaskContextAdmitsSwiftModuleImportersThatNameASubjectSymbol(t *testing.T) {
	root := impactRepositoryWithFiles(t, map[string]string{
		"Package.swift":                      "// swift-tools-version:5.9\n",
		"Sources/Kit/Play.swift":             "public struct PlaybackStart {}\n",
		"Sources/Kit/Same.swift":             "import Kit\n\nlet same = PlaybackStart()\n",
		"Sources/App/Main.swift":             "import Foundation\nimport Kit\n\nlet start = PlaybackStart()\n",
		"Sources/App/Other.swift":            "import Kit\n\nlet other = 1\n",
		"Tests/KitTests/PlaybackTests.swift": "@testable import Kit\n\nfunc testStart() { _ = PlaybackStart() }\n",
	})
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	packet, err := TaskContext(context.Background(), index, "TCP-V0-004 swift module importers: change `PlaybackStart`", "Sources/Kit/Play.swift", 20)
	if err != nil {
		t.Fatal(err)
	}
	found := contextRowsByKind(t, packet)
	want := []string{"Sources/App/Main.swift", "Tests/KitTests/PlaybackTests.swift"}
	if !slices.Equal(found["reverse-import"], want) {
		t.Fatalf("reverse-import rows = %v, want %v: importers naming the symbol, not the same module or a client that never names it", found["reverse-import"], want)
	}
	for _, item := range mapsFromAny(packet["results"]) {
		if item["id"] != "Sources/App/Main.swift" {
			continue
		}
		evidence := mapsFromAny(item["evidence"])[0]
		if evidence["line"] != 2.0 && evidence["line"] != 2 || evidence["confidence"] != "medium" {
			t.Fatalf("evidence = %v, want the import line at medium", evidence)
		}
	}
}

func TestSiblingsSharingASubjectTermRankFirst(t *testing.T) {
	root := impactRepositoryWithFiles(t, map[string]string{
		"go.mod":                "module example.test/sib\n\ngo 1.27.0\n",
		"play/PlaybackPlan.go":  "package play\n\nfunc Plan() {}\n",
		"play/Aardvark.go":      "package play\n\nfunc Aardvark() {}\n",
		"play/PlaybackState.go": "package play\n\nfunc State() {}\n",
		"play/Zebra.go":         "package play\n\nfunc Zebra() {}\n",
	})
	index, err := Build(context.Background(), root)
	if err != nil {
		t.Fatal(err)
	}
	compiler := newTaskContextCompiler(index, "TCP-V0-004 sibling order: adjust the plan", "play/PlaybackPlan.go")
	rows := compiler.siblingRows()
	if len(rows) != 4 || rows[0].path != "play/PlaybackPlan.go" || rows[1].path != "play/PlaybackState.go" || rows[2].path != "play/Aardvark.go" {
		t.Fatalf("sibling order = %v, want the basename-sharing sibling first, then path order", rows)
	}
}

func TestTaskContextAdmitsFilesNamingASubjectSymbol(t *testing.T) {
	index := taskContextFixture(t)
	packet, err := TaskContext(context.Background(), index, "tidy the exported surface", "cache/cache.go", 20)
	if err != nil {
		t.Fatal(err)
	}
	summaries := map[string]string{}
	for _, row := range mapsFromAny(packet["results"]) {
		summaries[row["id"].(string)] = row["kind"].(string) + ": " + row["summary"].(string)
	}
	// server.go imports the subject and names Demux, which it defines: the
	// importer slot keeps it and the reference slot corroborates.
	if got := summaries["server/server.go"]; !strings.HasPrefix(got, "reverse-import:") || !strings.Contains(got, "reference") {
		t.Fatalf("server.go = %q, want an importer corroborated by reference", got)
	}
	// At the slot level: a file naming Demux without importing the subject is
	// a reference row with the symbol in its reason; a two-letter symbol and
	// the subject itself admit nothing.
	index.Sources["docs/demux-notes.md"] = Source{Path: "docs/demux-notes.md", Data: []byte("Call Demux before Split.\n")}
	index.Symbols = append(index.Symbols, Symbol{Kind: "func", Name: "Go", Path: "cache/cache.go", Line: 1})
	index.Vocabulary = nil
	rows := newTaskContextCompiler(index, "tidy", "cache/cache.go").referenceRows()
	paths := map[string]string{}
	for _, row := range rows {
		paths[row.path] = row.reason
	}
	if paths["docs/demux-notes.md"] != "names Demux, which the subject defines" || paths["server/server.go"] == "" {
		t.Fatalf("reference rows = %v", paths)
	}
	if _, present := paths["cache/cache.go"]; present {
		t.Fatal("the subject never references itself")
	}
	for _, row := range rows {
		if row.score > contextReferenceMaxScore || row.score < 600 || row.confidence != "medium" {
			t.Fatalf("row shape: %+v", row)
		}
	}
}

func TestTaskContextAbstainsOnAnUnsupportedConjunction(t *testing.T) {
	t.Setenv("CORVINT_CONTEXT_TERMS", "")
	t.Setenv("CORVINT_CONTEXT_FRAME_RELATION", "")
	task := "Does `httpRetry` honour `maxAttempts` and `backoffBase` inside the `retry_loop`?"
	build := func(loop string, withTest bool) *Index {
		files := map[string]string{
			"go.mod":       "module example.test/retry\n\ngo 1.27.0\n",
			"net/loop.go":  loop,
			"net/other.go": "package net\n\nfunc other() {}\n",
		}
		if withTest {
			files["net/loop_test.go"] = "package net\n\nfunc TestLoop() { loop() }\n"
		}
		index, err := Build(context.Background(), impactRepositoryWithFiles(t, files))
		if err != nil {
			t.Fatal(err)
		}
		return index
	}
	verdict := func(packet map[string]any) map[string]any {
		return packet["coverage"].(map[string]any)["answerability"].(map[string]any)
	}
	t.Run("TCP-V0-016 names no source carries withhold the rows and name the nearest claims", func(t *testing.T) {
		packet, err := TaskContext(context.Background(), build("package net\n\n// retry inside the loop\nfunc loop() {}\n", false), task, "", 20)
		if err != nil {
			t.Fatal(err)
		}
		answer := verdict(packet)
		if packet["state"] != "NO_CANDIDATES" || len(packet["results"].([]any)) != 0 || answer["verdict"] != "unsupported-conjunction" {
			t.Fatalf("packet should abstain: state=%v verdict=%v", packet["state"], answer["verdict"])
		}
		if !strings.Contains(answer["reason"].(string), "`httpRetry`") || !strings.Contains(answer["reason"].(string), "`retry_loop`") {
			t.Fatalf("reason should name the unsupported terms: %v", answer["reason"])
		}
		nearest := answer["nearest_claims"].([]any)
		if len(nearest) < 1 || nearest[0].(map[string]any)["path"] != "net/loop.go" {
			t.Fatalf("nearest claims should be the withheld rows: %v", nearest)
		}
		if lacks := nearest[0].(map[string]any)["lacks"].([]any); !slices.Contains(lacks, any("httpRetry")) {
			t.Fatalf("nearest claim should say what it lacks: %v", lacks)
		}
	})
	t.Run("TCP-V0-016 a lexical test relation does not rescue absent names", func(t *testing.T) {
		index := build("package net\n\n// retry inside the loop\nfunc loop() {}\n", true)
		compiler := newTaskContextCompiler(index, task, "")
		candidates := compiler.compile(20)
		tests := make([]string, 0)
		for _, row := range candidates {
			switch row.kind {
			case "test":
				tests = append(tests, row.path)
			case "lexical", "documentation":
			default:
				t.Fatalf("fixture unexpectedly admits a task relation: %+v", row)
			}
		}
		if !slices.Equal(tests, []string{"net/loop_test.go"}) {
			t.Fatalf("fixture must generate the unrelated mirrored test before answerability: %v", tests)
		}
		packet, err := TaskContext(context.Background(), index, task, "", 20)
		if err != nil {
			t.Fatal(err)
		}
		answer := verdict(packet)
		t.Logf("pre-verdict candidates=%d test=%v; state=%v verdict=%v known=%v", len(candidates), tests, packet["state"], answer["verdict"], answer["known"])
		if answer["known"] != 0 || answer["support"] != 0 || answer["supporting_sources"] != 0 {
			t.Fatalf("unrelated test must not supply any task name: %v", answer)
		}
		names := make([]string, 0)
		for _, term := range mapsFromAny(answer["specific_terms"]) {
			names = append(names, term["term"].(string))
			if term["sources"] != 0 || term["tracked_paths"] != 0 {
				t.Fatalf("specific name unexpectedly has source or path support: %v", term)
			}
		}
		slices.Sort(names)
		if !slices.Equal(names, []string{"backoffBase", "httpRetry", "maxAttempts", "retry_loop"}) {
			t.Fatalf("fixture must retain the four absent names: %v", names)
		}
		if packet["state"] != "NO_CANDIDATES" || answer["verdict"] != "unsupported-conjunction" || len(packet["results"].([]any)) != 0 {
			t.Fatalf("lexically derived test must not rescue absent names: state=%v answer=%v", packet["state"], answer)
		}
		coverage := packet["coverage"].(map[string]any)
		if coverage["candidates"] != len(candidates) || coverage["omitted_results"] != len(candidates) || coverage["included_results"] != 0 {
			t.Fatalf("withholding must retain the pre-verdict candidate and omission counts: %v", coverage)
		}
		withheldTest := false
		for _, claim := range mapsFromAny(answer["nearest_claims"]) {
			if claim["path"] == "net/loop_test.go" {
				withheldTest = true
				if len(claim["supports"].([]any)) != 0 || !slices.Contains(claim["lacks"].([]any), any("httpRetry")) {
					t.Fatalf("withheld test must disclose its missing task names: %v", claim)
				}
			}
		}
		if !withheldTest {
			t.Fatalf("nearest claims must retain the withheld test: %v", answer["nearest_claims"])
		}
	})
	t.Run("TCP-V0-016 only the named relations can rescue absent names", func(t *testing.T) {
		rows := make([]contextRow, 0)
		for _, kind := range []string{"mentioned", "pair", "definition", "reverse-import", "reference", "cochange", "sibling", "test", "lexical", "documentation", governingRelation, specMentionedRelation, "future-relation"} {
			rows = append(rows, contextRow{kind: kind})
		}
		if got := relationRows(rows); got != 7 {
			t.Fatalf("only the seven relations in TCP-V0-016(c) may rescue a conjunction, got %d", got)
		}
	})
	t.Run("TCP-V0-016 a relation row overrules a vocabulary absence", func(t *testing.T) {
		packet, err := TaskContext(context.Background(), build("package net\n\nfunc loop() {}\n", true), "Does `httpRetry` honour `backoffBase` in net/loop.go today", "", 20)
		if err != nil {
			t.Fatal(err)
		}
		answer := verdict(packet)
		if packet["state"] != "READY" || answer["verdict"] != "relations-answer" || len(contextRowsByKind(t, packet)["mentioned"]) != 1 {
			t.Fatalf("mentioned path should keep the packet: state=%v %v", packet["state"], answer)
		}
	})
	t.Run("TCP-V0-016 one source naming the conjunction answers", func(t *testing.T) {
		packet, err := TaskContext(context.Background(), build("package net\n\nfunc retry_loop() { httpRetry(maxAttempts, backoffBase) }\n", true), task, "", 20)
		if err != nil {
			t.Fatal(err)
		}
		answer := verdict(packet)
		if packet["state"] != "READY" || answer["verdict"] != "supported" || answer["known"] != 4 || answer["support"] != 4 {
			t.Fatalf("packet should answer: %v", answer)
		}
	})
	t.Run("TCP-V0-016 three known names answer with all but one carried together", func(t *testing.T) {
		packet, err := TaskContext(context.Background(), build("package net\n\nfunc retry_loop() { _ = maxAttempts }\nfunc other2() { _ = backoffBase }\n", true), task, "", 20)
		if err != nil {
			t.Fatal(err)
		}
		answer := verdict(packet)
		if packet["state"] != "READY" || answer["verdict"] != "supported" || answer["known"] != 3 || answer["support"] != 3 || answer["required"] != 2 {
			t.Fatalf("all-but-one support should answer: %v", answer)
		}
	})
}

// The fallback ran whenever no Exclusion matched, so it blamed a suffix even
// for a path that has none. Invariant 2 forbids stating a cause the code has
// not established.
func TestSubjectEvidenceGapNamesOnlyTheCauseItEstablished(t *testing.T) {
	recorded := &taskContextCompiler{
		index:   &Index{Exclusions: []Exclusion{{Path: "cache/gen.go", Reason: "generated source"}}},
		subject: "cache/gen.go",
	}
	if got := recorded.subjectEvidenceGap(); got != "generated source" {
		t.Fatalf("recorded exclusion = %q, want the recorded reason", got)
	}
	unadmitted := &taskContextCompiler{index: &Index{}, subject: "legacy/Legacy.java"}
	if got := unadmitted.subjectEvidenceGap(); !strings.Contains(got, "suffix") {
		t.Fatalf("unadmitted suffix = %q, want the suffix named", got)
	}
	// LICENSE, Dockerfile and script/* have no suffix to blame.
	bare := &taskContextCompiler{index: &Index{}, subject: "LICENSE"}
	got := bare.subjectEvidenceGap()
	if got == "" || strings.Contains(got, "suffix") {
		t.Fatalf("extension-less subject = %q, want a non-empty gap that claims no suffix cause", got)
	}
}

// An unpinnable nearest claim (TCP-V0-016) must disclose why its blob_hash
// is empty the same way a result row does (TCP-V0-003), rather than leaving
// the empty hash unexplained (AGENTS.md invariant 2).
func TestAnswerabilityPacketDisclosesAnUnpinnedNearestClaim(t *testing.T) {
	verdict := answerability{
		terms:   []specificTerm{{term: "httpRetry"}, {term: "maxAttempts"}},
		nearest: []nearestClaim{{path: "legacy/Legacy.java", supports: []string{}, lacks: []string{"httpRetry"}}},
	}
	packet := verdict.packet(&Index{Sources: map[string]Source{}})
	if packet["verdict"] != "unsupported-conjunction" {
		t.Fatalf("verdict = %v, want unsupported-conjunction", packet["verdict"])
	}
	claims := mapsFromAny(packet["nearest_claims"])
	if len(claims) != 1 || claims[0]["blob_hash"] != "" {
		t.Fatalf("nearest claims = %v, want one claim with an empty blob_hash", claims)
	}
	if gap, ok := claims[0]["evidence_gap"].(string); !ok || gap == "" {
		t.Fatalf("unpinned nearest claim evidence_gap = %v, want a non-empty explanation", claims[0])
	}
}
