#!/usr/bin/env bash
# SPDX-License-Identifier: AGPL-3.0-or-later
# A synthetic local proof tour. Structural CEM acceptance is not semantic review.
set -u
set -m

out= resume= ack= verifier= verifier_sha= timeout_seconds=120
child_pid= watch_pid=

finish() {
  printf 'outcome=%s reason=%s out=%s\n' "$1" "$2" "${out:-NOT_CREATED}"
  exit "$3"
}
operational() { finish operational "$1" 2; }
incomplete() { finish incomplete "$1" 3; }
sha256_of() {
  local value
  if command -v sha256sum >/dev/null 2>&1; then value=$(sha256sum < "$1") || return 1
  else value=$(shasum -a 256 < "$1") || return 1; fi
  printf '%s\n' "${value%% *}"
}
is_hex() {
  [ "${#1}" -eq "$2" ] || return 1
  case "$1" in *[!0123456789abcdef]*) return 1;; esac
}
is_oid() { is_hex "$1" 40 || is_hex "$1" 64; }

# Reject symlinks at every existing path component. /private/tmp is supported;
# a symlink alias such as macOS /tmp must be replaced with its physical path.
regular_path() {
  local cursor=$1
  case "$cursor" in /*) ;; *) return 1;; esac
  case "$cursor" in */|*'//'*|*/../*|*/./*|*/..|*/.|*[$'\n\r']*) return 1;; esac
  while [ "$cursor" != / ]; do
    [ ! -L "$cursor" ] || return 1
    cursor=${cursor%/*}; [ -n "$cursor" ] || cursor=/
  done
}

retire_group() {
  kill -TERM -- "-$1" 2>/dev/null || return 0
  sleep 1
  kill -KILL -- "-$1" 2>/dev/null || :
}
cleanup() {
  if [ -n "$watch_pid" ]; then kill -KILL -- "-$watch_pid" 2>/dev/null || :; wait "$watch_pid" 2>/dev/null || :; fi
  if [ -n "$child_pid" ]; then retire_group "$child_pid"; wait "$child_pid" 2>/dev/null || :; fi
  child_pid= watch_pid=
}
trap cleanup EXIT
trap 'cleanup; exit 129' HUP
trap 'cleanup; exit 130' INT
trap 'cleanup; exit 143' TERM

run_step() {
  local name=$1 status=0
  shift
  local suffix
  for suffix in out stderr argv exit timeout; do
    [ ! -e "$out/receipts/$name.$suffix" ] && [ ! -L "$out/receipts/$name.$suffix" ] || operational "receipt-already-exists:$name"
  done
  printf '%q ' "$@" > "$out/receipts/$name.argv"
  printf '\n' >> "$out/receipts/$name.argv"
  "$@" > "$out/receipts/$name.out" 2> "$out/receipts/$name.stderr" &
  child_pid=$!
  (
    elapsed=0
    while [ "$elapsed" -lt "$timeout_seconds" ]; do
      sleep 1
      kill -0 "$child_pid" 2>/dev/null || exit 0
      elapsed=$((elapsed + 1))
    done
    : > "$out/receipts/$name.timeout"
    retire_group "$child_pid"
  ) &
  watch_pid=$!
  wait "$child_pid" 2>/dev/null || status=$?
  # Also retire ordinary descendants whose leader has already exited.
  kill -KILL -- "-$child_pid" 2>/dev/null || :
  kill -KILL -- "-$watch_pid" 2>/dev/null || :
  wait "$watch_pid" 2>/dev/null || :
  child_pid= watch_pid=
  if [ -e "$out/receipts/$name.timeout" ]; then status=124; fi
  printf '%s\n' "$status" > "$out/receipts/$name.exit"
  printf 'step=%s exit=%s\n' "$name" "$status"
  return "$status"
}
required_step() {
  local name=$1 status=0
  run_step "$@" || status=$?
  [ "$status" -ne 124 ] || operational "timeout:$name"
  [ "$status" -eq 0 ] || incomplete "refused:$name"
}

usage() {
  cat <<'USAGE'
Synthetic local proof tour (experimental; no complete review or third-party interop claim).
  script/proof-tour.sh --out NEW_ABSOLUTE_DIR --verifier ABSOLUTE_EXECUTABLE \
    --verifier-sha256 LOWERCASE_SHA256 [--timeout SECONDS]
  script/proof-tour.sh --resume EXISTING_ABSOLUTE_DIR --ack ABSOLUTE_ACK_FILE \
    [--timeout SECONDS]
Fresh runs exit 3 awaiting independent review. Resume validates original bytes and a
reviewer-supplied inert ACK before digest-pinned structural verification; exit 0 complete,
2 operational failure, 3 incomplete. No ACK is generated by this script.
Dependencies: Bash >=3.2, Git, local Go, installed corvint, sha256sum or shasum, ordinary
POSIX tools. Receipts, fixture and refusal rows are retained. No network installation.
USAGE
}
while [ "$#" -gt 0 ]; do
  case "$1" in --help) usage; exit 0;; esac
  [ "$#" -ge 2 ] || operational missing-argument
  case "$1" in
    --out) [ -z "$out" ] || operational repeated-out; out=$2;;
    --resume) [ -z "$resume" ] || operational repeated-resume; resume=$2;;
    --ack) [ -z "$ack" ] || operational repeated-ack; ack=$2;;
    --verifier) [ -z "$verifier" ] || operational repeated-verifier; verifier=$2;;
    --verifier-sha256) [ -z "$verifier_sha" ] || operational repeated-digest; verifier_sha=$2;;
    --timeout) timeout_seconds=$2;;
    *) operational unknown-argument;;
  esac
  shift 2
done
case "$timeout_seconds" in ''|0|*[!0123456789]*) operational invalid-timeout;; esac
[ "${#timeout_seconds}" -le 4 ] && [ "$timeout_seconds" -le 3600 ] || operational invalid-timeout
core=$(command -v corvint) || operational corvint-unavailable
command -v git >/dev/null && command -v go >/dev/null || operational prerequisites-unavailable
if ! command -v sha256sum >/dev/null && ! command -v shasum >/dev/null; then operational sha256-unavailable; fi

if [ -n "$resume" ]; then
  [ -z "$out" ] && [ -z "$verifier" ] && [ -z "$verifier_sha" ] || operational mixed-resume-inputs
  out=$resume
  regular_path "$out" && [ -d "$out" ] || operational unsafe-resume-directory
  regular_path "$out/receipts" && [ -d "$out/receipts" ] && regular_path "$out/tools" && [ -d "$out/tools" ] || incomplete unsafe-receipt-directory
  state=$out/review-request.txt
  [ -f "$state" ] && regular_path "$state" && [ "$(wc -c < "$state")" -le 1024 ] || incomplete missing-review-request
  [ "$(sed -n '1p' "$state")" = proof-tour-review/0 ] && [ "$(wc -l < "$state")" -eq 6 ] || incomplete invalid-review-request
  base=$(sed -n '2s/^base=//p' "$state")
  head=$(sed -n '3s/^head=//p' "$state")
  map_sha=$(sed -n '4s/^map_sha256=//p' "$state")
  patch_sha=$(sed -n '5s/^patch_sha256=//p' "$state")
  verifier_sha=$(sed -n '6s/^verifier_sha256=//p' "$state")
  is_oid "$base" && is_oid "$head" && is_hex "$map_sha" 64 && is_hex "$patch_sha" 64 && is_hex "$verifier_sha" 64 || incomplete invalid-review-bindings
  printf 'proof-tour-review/0\nbase=%s\nhead=%s\nmap_sha256=%s\npatch_sha256=%s\nverifier_sha256=%s\n' "$base" "$head" "$map_sha" "$patch_sha" "$verifier_sha" | cmp -s - "$state" || incomplete noncanonical-review-request
  fixture=$out/fixture
  regular_path "$fixture/.git" && [ -d "$fixture/.git" ] || incomplete unsafe-fixture
  regular_path "$out/change.patch" && regular_path "$fixture/.corvint/change.cem.json" || incomplete unsafe-original-bytes
  [ -f "$out/change.patch" ] && [ -f "$fixture/.corvint/change.cem.json" ] || incomplete missing-original-bytes
  [ "$(git -C "$fixture" rev-parse HEAD 2>/dev/null)" = "$head" ] || incomplete stale-head
  # Re-derive into a new receipt, never overwrite the reviewed patch or fixture.
  round=1
  # A round is used once its status or patch receipt exists, so a refused status
  # read keeps its receipts and the next resume starts a new round.
  while [ -e "$out/receipts/resume-$round-status.out" ] || [ -e "$out/receipts/resume-$round-patch.out" ]; do
    for prior in status patch; do
      prior=$out/receipts/resume-$round-$prior.out
      [ ! -e "$prior" ] && [ ! -L "$prior" ] || { [ ! -L "$prior" ] && [ -f "$prior" ]; } || operational unsafe-prior-receipt
    done
    round=$((round + 1)); [ "$round" -le 100 ] || operational resume-limit
  done
  prefix=resume-$round
  # Admit the entire round before any receipt or auxiliary output is written.
  # In particular cp/printf must not follow pre-existing ACK/identity symlinks.
  for step_name in status patch core-version ready go-revalidated portable; do
    for suffix in out stderr argv exit timeout; do
      destination=$out/receipts/$prefix-$step_name.$suffix
      [ ! -e "$destination" ] && [ ! -L "$destination" ] || operational resume-output-collision
    done
  done
  for auxiliary in ack.txt tool-identity.txt; do
    destination=$out/receipts/$prefix-$auxiliary
    [ ! -e "$destination" ] && [ ! -L "$destination" ] || operational resume-output-collision
  done
  # Git status failure never means clean; its exit and diagnostic stay as receipts.
  run_step "$prefix-status" git -C "$fixture" status --porcelain --untracked-files=all || {
    [ ! -e "$out/receipts/$prefix-status.timeout" ] || operational "timeout:$prefix-status"
    incomplete git-status-failed
  }
  [ ! -s "$out/receipts/$prefix-status.out" ] || incomplete dirty-fixture
  [ "$(sha256_of "$fixture/.corvint/change.cem.json")" = "$map_sha" ] && [ "$(sha256_of "$out/change.patch")" = "$patch_sha" ] || incomplete stale-original-bytes
  committed_map=$(git -C "$fixture" show "$head:.corvint/change.cem.json" | { if command -v sha256sum >/dev/null; then sha256sum; else shasum -a 256; fi; })
  [ "${committed_map%% *}" = "$map_sha" ] || incomplete stale-committed-map
  required_step "$prefix-patch" git -C "$fixture" -c core.quotePath=false -c diff.algorithm=myers -c diff.context=3 diff --binary --full-index --no-color --no-ext-diff --no-textconv --no-renames --no-indent-heuristic --diff-algorithm=myers --unified=3 --src-prefix=a/ --dst-prefix=b/ --ignore-submodules=none "$base" "$head" -- . ':(exclude).corvint/change.cem.json'
  [ "$(sha256_of "$out/receipts/$prefix-patch.out")" = "$patch_sha" ] || incomplete stale-derived-patch
  [ -n "$ack" ] && regular_path "$ack" && [ -f "$ack" ] && [ "$(wc -c < "$ack")" -le 1024 ] || incomplete independent-review-not-supplied
  [ "$(sed -n '1p' "$ack")" = proof-tour-ack/0 ] && [ "$(wc -l < "$ack")" -eq 7 ] || incomplete invalid-review-ack
  [ "$(sed -n '2p' "$ack")" = "base=$base" ] && [ "$(sed -n '3p' "$ack")" = "head=$head" ] && [ "$(sed -n '4p' "$ack")" = "map_sha256=$map_sha" ] && [ "$(sed -n '5p' "$ack")" = "patch_sha256=$patch_sha" ] || incomplete stale-review-ack
  [ "$(sed -n '6p' "$ack")" = verdict=ACCEPT ] || incomplete review-not-accepted
  reviewer=$(sed -n '7s/^reviewer=//p' "$ack")
  case "$reviewer" in ''|*[!ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789._/-]*) incomplete invalid-reviewer;; esac
  printf 'proof-tour-ack/0\nbase=%s\nhead=%s\nmap_sha256=%s\npatch_sha256=%s\nverdict=ACCEPT\nreviewer=%s\n' "$base" "$head" "$map_sha" "$patch_sha" "$reviewer" | cmp -s - "$ack" || incomplete noncanonical-review-ack
  cp "$ack" "$out/receipts/$prefix-ack.txt" || operational retain-ack-failed
  copied=$out/tools/cem01-go
  regular_path "$copied" && [ -f "$copied" ] && [ -x "$copied" ] || incomplete copied-verifier-missing
  [ "$(sha256_of "$copied")" = "$verifier_sha" ] || incomplete copied-verifier-digest-mismatch
  required_step "$prefix-core-version" "$core" --version
  printf 'core_path=%s\ncore_sha256=%s\nverifier_sha256=%s\n' "$core" "$(sha256_of "$core")" "$verifier_sha" > "$out/receipts/$prefix-tool-identity.txt"
  required_step "$prefix-ready" "$core" --root "$fixture" cem status --map .corvint/change.cem.json --patch "$out/change.patch" --max-unknown 0 --max-mechanical 0
  required_step "$prefix-go-revalidated" env GOTOOLCHAIN=local GOPROXY=off GOSUMDB=off GOCACHE="${GOCACHE:-$out/go-cache}" go -C "$fixture" test -count=1 -timeout 30m ./...
  required_step "$prefix-portable" "$copied" ci --repository "$fixture" --base "$base" --head "$head" --map .corvint/change.cem.json
  grep -F '"verdict":"accepted"' "$out/receipts/$prefix-portable.out" >/dev/null || incomplete portable-verdict-not-accepted
  printf 'independent_review=operator-supplied-bound-ACK reviewer=%s semantic_support=reviewer-assessment portability=second-Corvint-authored-implementation third_party_interop=NOT_OBSERVED\n' "$reviewer"
  printf 'limits=constant-only-fixture token_expiration_runtime=NOT_PROVEN timing_boundaries=NOT_PROVEN authenticated_semantic_proof=NOT_OBSERVED external_adoption=NOT_OBSERVED\n'
  finish complete exact-reviewed-fixture-and-structural-acceptance 0
fi

[ -z "$ack" ] || operational ack-requires-resume
regular_path "$out" || operational unsafe-output-directory
[ ! -e "$out" ] || { [ -d "$out" ] && [ -z "$(ls -A "$out")" ]; } || operational output-not-new-or-empty
regular_path "$verifier" && [ -f "$verifier" ] && [ -x "$verifier" ] && is_hex "$verifier_sha" 64 || operational invalid-verifier-input
mkdir -p "$out/receipts" "$out/tools" "$out/fixture/auth" "$out/fixture/docs" || operational output-create-failed
copied=$out/tools/cem01-go
cp "$verifier" "$copied" && chmod 700 "$copied" || operational verifier-copy-failed
[ "$(sha256_of "$copied")" = "$verifier_sha" ] || operational verifier-digest-mismatch-not-executed
required_step core-version "$core" --version
printf 'core_path=%s\ncore_sha256=%s\nverifier_source=%s\nverifier_sha256=%s\nqualification=synthetic-local-proof-tour\n' "$core" "$(sha256_of "$core")" "$verifier" "$verifier_sha" > "$out/tool-identity.txt"
fixture=$out/fixture
cat > "$fixture/go.mod" <<'FIXTURE'
module example.test/proof-tour

go 1.27.0
FIXTURE
cat > "$fixture/AGENTS.md" <<'FIXTURE'
This is a synthetic proof-tour fixture, not a production authorization policy.
Use docs/policy.md as the original policy evidence for token lifetime.
FIXTURE
cat > "$fixture/docs/policy.md" <<'FIXTURE'
# Synthetic session policy

Session tokens expire after nine hundred seconds.
FIXTURE
cat > "$fixture/auth/auth.go" <<'FIXTURE'
package auth

// Lifetime is the session token lifetime in seconds.
const Lifetime = 600
FIXTURE
cat > "$fixture/auth/auth_test.go" <<'FIXTURE'
package auth

import "testing"

func TestLifetime(t *testing.T) {
  if Lifetime != 900 { t.Fatalf("got %d, want 900", Lifetime) }
}
FIXTURE
required_step git-init git -C "$fixture" -c core.excludesFile=/dev/null -c core.hooksPath=/dev/null -c init.templateDir= init -q
required_step base-add git -C "$fixture" -c core.excludesFile=/dev/null -c core.hooksPath=/dev/null add AGENTS.md go.mod docs/policy.md auth/auth.go auth/auth_test.go
required_step base-commit git -C "$fixture" -c core.excludesFile=/dev/null -c core.hooksPath=/dev/null -c commit.gpgsign=false -c user.name='Proof tour fixture' -c user.email=fixture@invalid.test commit -qm 'Synthetic policy and incorrect lifetime'
base=$(git -C "$fixture" rev-parse HEAD) || operational base-unavailable
required_step query "$core" --root "$fixture" query --task 'auth token lifetime policy' --limit 5
required_step context "$core" --root "$fixture" context --task 'repair auth token lifetime to match docs/policy.md' --subject auth/auth.go --limit 10
status=0
run_step go-baseline env GOTOOLCHAIN=local GOPROXY=off GOSUMDB=off GOCACHE="${GOCACHE:-$out/go-cache}" go -C "$fixture" test -count=1 -timeout 30m ./... || status=$?
[ "$status" -ne 124 ] || operational timeout:go-baseline
[ "$status" -eq 1 ] && grep -F 'got 600, want 900' "$out/receipts/go-baseline.out" >/dev/null || incomplete expected-baseline-failure-not-observed
sed 's/const Lifetime = 600/const Lifetime = 900/' "$fixture/auth/auth.go" > "$out/repaired.go"
cp "$out/repaired.go" "$fixture/auth/auth.go" || operational repair-copy-failed
required_step change-add git -C "$fixture" -c core.excludesFile=/dev/null -c core.hooksPath=/dev/null add auth/auth.go
required_step change-commit git -C "$fixture" -c core.excludesFile=/dev/null -c core.hooksPath=/dev/null -c commit.gpgsign=false -c user.name='Proof tour fixture' -c user.email=fixture@invalid.test commit -qm 'Match original synthetic policy'
change=$(git -C "$fixture" rev-parse HEAD) || operational change-unavailable
required_step impact "$core" --root "$fixture" impact --base "$base" --limit 10
required_step affected "$core" --root "$fixture" affected --base "$base"
required_step go-repaired env GOTOOLCHAIN=local GOPROXY=off GOSUMDB=off GOCACHE="${GOCACHE:-$out/go-cache}" go -C "$fixture" test -count=1 -timeout 30m ./...
required_step patch git -C "$fixture" -c core.quotePath=false -c diff.algorithm=myers -c diff.context=3 diff --binary --full-index --no-color --no-ext-diff --no-textconv --no-renames --no-indent-heuristic --diff-algorithm=myers --unified=3 --src-prefix=a/ --dst-prefix=b/ --ignore-submodules=none "$base" "$change" -- . ':(exclude).corvint/change.cem.json'
cp "$out/receipts/patch.out" "$out/change.patch" || operational patch-retain-failed
required_step begin "$core" --root "$fixture" cem begin --patch "$out/change.patch" --output .corvint/change.cem.json --base "$base"
status=0
run_step missing-witness "$core" --root "$fixture" cem status --map .corvint/change.cem.json --patch "$out/change.patch" --max-unknown 0 --max-mechanical 0 || status=$?
[ "$status" -eq 1 ] && grep -F '"code":"max-unknown-exceeded"' "$out/receipts/missing-witness.out" >/dev/null || incomplete expected-missing-witness-refusal-not-observed
required_step cite-policy "$core" --root "$fixture" cem cite --map .corvint/change.cem.json --hunk 1 --evidence-path docs/policy.md --lines 3:3 --relation decision
required_step map-add git -C "$fixture" -c core.excludesFile=/dev/null -c core.hooksPath=/dev/null add .corvint/change.cem.json
required_step map-commit git -C "$fixture" -c core.excludesFile=/dev/null -c core.hooksPath=/dev/null -c commit.gpgsign=false -c user.name='Proof tour fixture' -c user.email=fixture@invalid.test commit -qm 'Retain original policy witness'
head=$(git -C "$fixture" rev-parse HEAD) || operational head-unavailable
required_step ready "$core" --root "$fixture" cem status --map .corvint/change.cem.json --patch "$out/change.patch" --max-unknown 0 --max-mechanical 0
required_step report "$core" --root "$fixture" cem report --map .corvint/change.cem.json --patch "$out/change.patch" --max-unknown 0 --max-mechanical 0 --output "$out/review.md"
required_step advisory-review "$core" --root "$fixture" review --base "$base"
map_sha=$(sha256_of "$fixture/.corvint/change.cem.json") || operational map-digest-unavailable
patch_sha=$(sha256_of "$out/change.patch") || operational patch-digest-unavailable
printf 'proof-tour-review/0\nbase=%s\nhead=%s\nmap_sha256=%s\npatch_sha256=%s\nverifier_sha256=%s\n' "$base" "$head" "$map_sha" "$patch_sha" "$verifier_sha" > "$out/review-request.txt"
printf 'independent_review=NOT_RUN semantic_support=NOT_PROVEN third_party_interop=NOT_OBSERVED\n'
printf 'ACK format: proof-tour-ack/0, same base/head/map_sha256/patch_sha256 lines, verdict=ACCEPT, reviewer=IDENTIFIER (seven LF-terminated lines).\n'
finish awaiting-independent-review retain-originals-for-fresh-reviewer 3
