package native

import (
	"encoding/json"
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"strings"
	"testing"

	tr "github.com/Beamfall/corvint/internal/testrunner"
)

// The fixtures below are shaped from the pinned Ginkgo v2.33.0 JSON projection
// (testdata/ginkgo-provenance.json). They are not runner-generated bytes: actual
// Ginkgo qualification is NOT_RUN because no Ginkgo module is present locally.
const ginkgoDesc = "Calc (v1.2) [x]+"
const ginkgoTargetID = "TestCalc::" + ginkgoDesc
const ginkgoRoot = "/src/calc"

func ginkgoID(full string) string { return ginkgoTargetID + "::" + full }

func ginkgoLocation() map[string]any {
	return map[string]any{"FileName": "/src/calc/calc_test.go", "LineNumber": 10}
}

func ginkgoRecord(containers []string, leaf, node, state string, attempts int) map[string]any {
	var c any
	if containers != nil {
		c = containers
	}
	return map[string]any{"ContainerHierarchyTexts": c, "ContainerHierarchyLocations": nil, "ContainerHierarchyLabels": nil, "ContainerHierarchySemVerConstraints": nil, "ContainerHierarchyComponentSemVerConstraints": nil, "LeafNodeType": node, "LeafNodeLocation": ginkgoLocation(), "LeafNodeLabels": nil, "LeafNodeSemVerConstraints": nil, "LeafNodeText": leaf, "State": state, "StartTime": "2026-10-01T00:00:00Z", "EndTime": "2026-10-01T00:00:00Z", "RunTime": 1000, "ParallelProcess": 1, "NumAttempts": attempts, "MaxFlakeAttempts": 1, "MaxMustPassRepeatedly": 0}
}

func ginkgoFailureRecord(message, context string) map[string]any {
	return map[string]any{"Message": message, "Location": ginkgoLocation(), "TimelineLocation": map[string]any{"Offset": 0, "Order": 0, "Time": "2026-10-01T00:00:00Z"}, "FailureNodeContext": context, "FailureNodeType": "It", "FailureNodeLocation": ginkgoLocation(), "ProgressReport": map[string]any{}}
}

func ginkgoConfigRecord(focus []string) map[string]any {
	var f any
	if focus != nil {
		f = focus
	}
	return map[string]any{"RandomSeed": 1, "RandomizeAllSpecs": false, "FocusStrings": f, "SkipStrings": nil, "FocusFiles": nil, "SkipFiles": nil, "LabelFilter": "", "SemVerFilter": "", "FailOnPending": false, "FailOnEmpty": true, "FailFast": false, "FlakeAttempts": 1, "MustPassRepeatedly": 0, "DryRun": false, "PollProgressAfter": 0, "PollProgressInterval": 0, "Timeout": 3600000000000, "EmitSpecProgress": false, "OutputInterceptorMode": "none", "SourceRoots": nil, "GracePeriod": 1000000000, "SleepOnFailure": 0, "ParallelProcess": 1, "ParallelTotal": 1, "ParallelHost": ""}
}

func ginkgoSuite(succeeded bool, total, willRun int, focus []string, specs ...map[string]any) map[string]any {
	records := []any{}
	for _, s := range specs {
		records = append(records, s)
	}
	return map[string]any{"SuitePath": ginkgoRoot, "SuiteDescription": ginkgoDesc, "SuiteLabels": nil, "SuiteSemVerConstraints": nil, "SuiteComponentSemVerConstraints": nil, "SuiteSucceeded": succeeded, "SuiteHasProgrammaticFocus": false, "SpecialSuiteFailureReasons": nil, "PreRunStats": map[string]any{"TotalSpecs": total, "SpecsThatWillRun": willRun}, "StartTime": "2026-10-01T00:00:00Z", "EndTime": "2026-10-01T00:00:01Z", "RunTime": 1000000, "SuiteConfig": ginkgoConfigRecord(focus), "SpecReports": records}
}

func ginkgoEncode(in *tr.Input, suites ...map[string]any) {
	a := []any{}
	for _, s := range suites {
		a = append(a, s)
	}
	b, _ := json.Marshal(a)
	in.Reports = map[string][]byte{"ginkgo.json": b}
}

func ginkgoSpecs(rep map[string]any) []map[string]any {
	var out []map[string]any
	for _, s := range rep["SpecReports"].([]any) {
		out = append(out, s.(map[string]any))
	}
	return out
}

// ginkgoMixed is an unselected run: pass, ordinary leaf failure, pending and a
// runtime Skip() inside an It, plus a passing BeforeSuite record.
func ginkgoMixed() (map[string]any, tr.Input) {
	failedSpec := ginkgoRecord([]string{"Math"}, "subtracts", "It", "failed", 1)
	failedSpec["Failure"] = ginkgoFailureRecord("expected 1 to equal 2", "leaf-node")
	skipped := ginkgoRecord([]string{"Math"}, "skips", "It", "skipped", 1)
	skipped["Failure"] = ginkgoFailureRecord("not on this platform", "leaf-node")
	rep := ginkgoSuite(false, 4, 3, nil,
		ginkgoRecord(nil, "", "BeforeSuite", "passed", 1),
		ginkgoRecord([]string{"Math"}, "adds", "It", "passed", 1),
		failedSpec,
		ginkgoRecord([]string{"Math"}, "pends", "It", "pending", 0),
		skipped)
	in := tr.Input{Runner: ginkgoRunner, Target: ginkgoTargetID, SourceRoot: ginkgoRoot, Expected: []string{ginkgoID("Math adds"), ginkgoID("Math subtracts"), ginkgoID("Math pends"), ginkgoID("Math skips")}, ExitCode: 1, SuccessExitCodes: []int{0}, FailureExitCodes: failureExits(ginkgoRunner)}
	ginkgoEncode(&in, rep)
	return rep, in
}

// ginkgoSelected selects "Math adds" only; every other It stays unentered.
func ginkgoSelected() (map[string]any, tr.Input) {
	rep, in := ginkgoMixed()
	in.Selectors = []string{ginkgoID("Math adds")}
	specs := ginkgoSpecs(rep)
	for _, s := range specs[2:] {
		s["NumAttempts"] = 0
		delete(s, "Failure")
		if s["State"] != "pending" {
			s["State"] = "skipped"
		}
	}
	rep["SuiteSucceeded"] = true
	rep["PreRunStats"] = map[string]any{"TotalSpecs": 4, "SpecsThatWillRun": 1}
	rep["SuiteConfig"] = ginkgoConfigRecord([]string{`^Calc \(v1\.2\) \[x\]\+ (Math adds)$`})
	in.ExitCode = 0
	ginkgoEncode(&in, rep)
	return rep, in
}

func ginkgoHas(o tr.Observation, code string) bool {
	for _, p := range o.Problems {
		if p.Code == code {
			return true
		}
	}
	return false
}

func TestGinkgoNativeProjectionStates(t *testing.T) {
	_, in := ginkgoMixed()
	o, e := Parse(in)
	if e != nil || !o.Complete || len(o.Tests) != 4 {
		t.Fatal(o, e)
	}
	got := map[string]tr.Test{}
	for _, row := range o.Tests {
		got[row.ID] = row
	}
	if got[ginkgoID("Math adds")].State != tr.Passed || got[ginkgoID("Math pends")].State != tr.Skipped || len(got[ginkgoID("Math pends")].Attempts) != 0 {
		t.Fatal(got)
	}
	if f := got[ginkgoID("Math subtracts")]; f.State != tr.Failed || f.FailureKind != tr.Unknown || f.Message != "expected 1 to equal 2" || len(f.Attempts) != 1 {
		t.Fatal("failure projection", f)
	}
	if s := got[ginkgoID("Math skips")]; s.State != tr.Skipped || s.Message != "not on this platform" || len(s.Attempts) != 1 {
		t.Fatal("runtime skip projection", s)
	}
	if n := tr.Normalize(in, o); !n.Complete {
		t.Fatal("normalized complete run became incomplete", n)
	}
	_, sel := ginkgoSelected()
	o, e = Parse(sel)
	if e != nil || !o.Complete || len(o.Tests) != 4 {
		t.Fatal(o, e)
	}
	for _, row := range o.Tests {
		if (row.ID == ginkgoID("Math adds")) != (row.State == tr.Passed) {
			t.Fatal("selection projection", row)
		}
	}
}

func TestGinkgoReportCountAndBound(t *testing.T) {
	_, in := ginkgoMixed()
	good := in.Reports["ginkgo.json"]
	for name, reports := range map[string]map[string][]byte{
		"zero": {},
		"two":  {"ginkgo.json": good, "other.json": good},
	} {
		in.Reports = reports
		if o, e := Parse(in); e == nil || e.Error() != "exactly one native report required" || o.Complete {
			t.Fatal(name, o, e)
		}
	}
	in.Reports = map[string][]byte{"other.json": good}
	if _, e := Parse(in); e == nil || e.Error() != "ginkgo report must be ginkgo.json" {
		t.Fatal(e)
	}
	in.Reports = map[string][]byte{"ginkgo.json": append(append([]byte{}, good...), make([]byte, tr.MaxReportBytes)...)}
	if _, e := Parse(in); e == nil || e.Error() != "native report bound exceeded" {
		t.Fatal(e)
	}
	rep, in := ginkgoMixed()
	for name, suites := range map[string][]map[string]any{"zero-suites": {}, "two-suites": {rep, rep}} {
		ginkgoEncode(&in, suites...)
		if o, e := Parse(in); e == nil || !strings.Contains(e.Error(), "exactly one suite") || !ginkgoHas(o, "GINKGO_INVALID_REPORT") {
			t.Fatal(name, o, e)
		}
	}
}

func TestGinkgoParserRefusals(t *testing.T) {
	type mutate func(rep map[string]any, in *tr.Input)
	for _, tc := range []struct {
		name     string
		selected bool
		change   mutate
		code     string // expected problem code with a nil error
		err      string // expected error substring
	}{
		{"exit-0-suite-false", true, func(r map[string]any, i *tr.Input) { r["SuiteSucceeded"] = false }, "GINKGO_EXIT_SUITE_CONTRADICTION", ""},
		{"exit-0-with-failure", false, func(r map[string]any, i *tr.Input) { r["SuiteSucceeded"] = true; i.ExitCode = 0 }, "GINKGO_EXIT_SUITE_CONTRADICTION", ""},
		{"exit-1-suite-true", false, func(r map[string]any, i *tr.Input) { r["SuiteSucceeded"] = true }, "GINKGO_EXIT_SUITE_CONTRADICTION", ""},
		{"unexplained-failure", true, func(r map[string]any, i *tr.Input) { r["SuiteSucceeded"] = false; i.ExitCode = 1 }, "GINKGO_UNEXPLAINED_SUITE_FAILURE", ""},
		{"reasons-with-success", true, func(r map[string]any, i *tr.Input) {
			r["SpecialSuiteFailureReasons"] = []string{"Detected no specs ran and --fail-on-empty is set"}
		}, "GINKGO_SUITE_FAILURE_REASON", ""},
		{"exit-2", false, func(r map[string]any, i *tr.Input) { i.ExitCode = 2 }, "GINKGO_EXIT_UNSUPPORTED", ""},
		{"exit-197-focus", true, func(r map[string]any, i *tr.Input) { r["SuiteHasProgrammaticFocus"] = true; i.ExitCode = 197 }, "GINKGO_PROGRAMMATIC_FOCUS", ""},
		{"programmatic-focus-exit-0", true, func(r map[string]any, i *tr.Input) { r["SuiteHasProgrammaticFocus"] = true }, "GINKGO_PROGRAMMATIC_FOCUS", ""},
		{"null-state", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[1]["State"] = nil }, "", "State is not a known enum string"},
		{"null-node-type", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[1]["LeafNodeType"] = nil }, "", "LeafNodeType is not a known enum string"},
		{"invalid-state-string", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[1]["State"] = "INVALID SPEC STATE" }, "", "State is not a known enum string"},
		{"null-failure-context", false, func(r map[string]any, i *tr.Input) {
			ginkgoSpecs(r)[2]["Failure"].(map[string]any)["FailureNodeContext"] = nil
		}, "", "FailureNodeContext is not a known enum string"},
		{"null-event-type", false, func(r map[string]any, i *tr.Input) {
			ginkgoSpecs(r)[1]["SpecEvents"] = []any{map[string]any{"SpecEventType": nil, "CodeLocation": ginkgoLocation(), "TimelineLocation": map[string]any{}}}
		}, "", "SpecEventType is not a known enum string"},
		{"unknown-key", false, func(r map[string]any, i *tr.Input) { r["Extra"] = 1 }, "", `unknown key "Extra"`},
		{"unknown-spec-key", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[1]["Extra"] = 1 }, "", `unknown key "Extra"`},
		{"missing-key", false, func(r map[string]any, i *tr.Input) { delete(r, "PreRunStats") }, "", `lacks key "PreRunStats"`},
		{"fractional-attempts", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[1]["NumAttempts"] = json.Number("1.0") }, "", "NumAttempts must be a non-negative integer"},
		{"not-entered", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[4]["NumAttempts"] = 0 }, "GINKGO_NOT_ENTERED", ""},
		{"unselected-executed", true, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[2]["NumAttempts"] = 1 }, "GINKGO_UNSELECTED_EXECUTED", ""},
		{"unselected-passed", true, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[2]["State"] = "passed" }, "GINKGO_UNSELECTED_EXECUTED", ""},
		{"retry-event", false, func(r map[string]any, i *tr.Input) {
			ginkgoSpecs(r)[1]["SpecEvents"] = []any{map[string]any{"SpecEventType": "Retry", "CodeLocation": ginkgoLocation(), "TimelineLocation": map[string]any{}}}
		}, "GINKGO_RETRY_UNSUPPORTED", ""},
		{"repeat-event", false, func(r map[string]any, i *tr.Input) {
			ginkgoSpecs(r)[1]["SpecEvents"] = []any{map[string]any{"SpecEventType": "Repeat", "CodeLocation": ginkgoLocation(), "TimelineLocation": map[string]any{}, "Attempt": 2}}
		}, "GINKGO_RETRY_UNSUPPORTED", ""},
		{"two-attempts", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[1]["NumAttempts"] = 2 }, "GINKGO_RETRY_UNSUPPORTED", ""},
		{"must-pass-repeatedly", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[1]["MaxMustPassRepeatedly"] = 2 }, "GINKGO_RETRY_UNSUPPORTED", ""},
		{"parallel-process", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[1]["ParallelProcess"] = 2 }, "GINKGO_PARALLEL_UNSUPPORTED", ""},
		{"suite-level-skipped", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[0]["State"] = "skipped" }, "GINKGO_SUITE_PROBLEM", ""},
		{"non-leaf-failure", false, func(r map[string]any, i *tr.Input) {
			ginkgoSpecs(r)[2]["Failure"].(map[string]any)["FailureNodeContext"] = "in-container"
		}, "GINKGO_HOOK_FAILURE", ""},
		{"top-level-failure", false, func(r map[string]any, i *tr.Input) {
			ginkgoSpecs(r)[2]["Failure"].(map[string]any)["FailureNodeContext"] = "top-level"
		}, "GINKGO_HOOK_FAILURE", ""},
		{"additional-failures", false, func(r map[string]any, i *tr.Input) {
			ginkgoSpecs(r)[1]["AdditionalFailures"] = []any{map[string]any{"State": "failed", "Failure": ginkgoFailureRecord("after each", "in-container")}}
		}, "GINKGO_ADDITIONAL_FAILURE", ""},
		{"passed-with-failure", false, func(r map[string]any, i *tr.Input) {
			ginkgoSpecs(r)[1]["Failure"] = ginkgoFailureRecord("late", "leaf-node")
		}, "GINKGO_UNEXPECTED_FAILURE", ""},
		{"panicked", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[2]["State"] = "panicked" }, "GINKGO_UNRESOLVED_STATE", ""},
		{"unsupported-node", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[0]["LeafNodeType"] = "BeforeEach" }, "GINKGO_UNSUPPORTED_NODE", ""},
		{"total-count", false, func(r map[string]any, i *tr.Input) { r["PreRunStats"] = map[string]any{"TotalSpecs": 5, "SpecsThatWillRun": 3} }, "GINKGO_COUNT_MISMATCH", ""},
		{"will-run-count", false, func(r map[string]any, i *tr.Input) { r["PreRunStats"] = map[string]any{"TotalSpecs": 4, "SpecsThatWillRun": 4} }, "GINKGO_COUNT_MISMATCH", ""},
		{"inventory", false, func(r map[string]any, i *tr.Input) { i.Expected[0] = ginkgoID("Math other") }, "GINKGO_INVENTORY_MISMATCH", ""},
		{"suite-path", false, func(r map[string]any, i *tr.Input) { r["SuitePath"] = "/private" + ginkgoRoot }, "GINKGO_SUITE_PATH_MISMATCH", ""},
		{"seed", false, func(r map[string]any, i *tr.Input) { r["SuiteConfig"].(map[string]any)["RandomSeed"] = 2 }, "GINKGO_CONFIG_MISMATCH", ""},
		{"dry-run", false, func(r map[string]any, i *tr.Input) { r["SuiteConfig"].(map[string]any)["DryRun"] = true }, "GINKGO_CONFIG_MISMATCH", ""},
		{"unrequested-focus", false, func(r map[string]any, i *tr.Input) { r["SuiteConfig"].(map[string]any)["FocusStrings"] = []string{"adds"} }, "GINKGO_CONFIG_MISMATCH", ""},
		{"unanchored-focus", true, func(r map[string]any, i *tr.Input) { r["SuiteConfig"].(map[string]any)["FocusStrings"] = []string{`^(Math adds)$`} }, "GINKGO_CONFIG_MISMATCH", ""},
		{"target", false, func(r map[string]any, i *tr.Input) { r["SuiteDescription"] = "Other" }, "", "SuiteDescription differs from Target"},
		{"duplicate-fulltext", false, func(r map[string]any, i *tr.Input) {
			s := ginkgoSpecs(r)[3]
			s["ContainerHierarchyTexts"], s["LeafNodeText"] = nil, "Math adds"
		}, "", "full text is empty, too long or duplicated"},
		{"newline-text", false, func(r map[string]any, i *tr.Input) { ginkgoSpecs(r)[1]["LeafNodeText"] = "a\nb" }, "", "contains NUL, CR or LF"},
	} {
		t.Run(tc.name, func(t *testing.T) {
			rep, in := ginkgoMixed()
			if tc.selected {
				rep, in = ginkgoSelected()
			}
			tc.change(rep, &in)
			ginkgoEncode(&in, rep)
			o, e := Parse(in)
			if tc.err != "" {
				if e == nil || !strings.Contains(e.Error(), tc.err) {
					t.Fatalf("want error %q, got %v %+v", tc.err, e, o)
				}
			} else if e != nil || o.Complete || !ginkgoHas(o, tc.code) {
				t.Fatalf("want problem %s, got %v %+v", tc.code, e, o)
			}
			if e == nil {
				n := tr.Normalize(in, o)
				for _, row := range n.Tests {
					if n.Complete || row.State != tr.Unknown {
						t.Fatal("normalized contradiction resolved", row)
					}
				}
			}
		})
	}
}

func TestGinkgoStrictJSON(t *testing.T) {
	_, in := ginkgoMixed()
	good := string(in.Reports["ginkgo.json"])
	for name, c := range map[string]struct{ raw, err string }{
		"duplicate-key": {strings.Replace(good, `"SuiteSucceeded":false`, `"SuiteSucceeded":false,"SuiteSucceeded":true`, 1), "duplicate ginkgo report key"},
		"trailing":      {good + "[]", "trailing ginkgo report content"},
		"invalid-utf8":  {strings.Replace(good, "subtracts", "sub\xfftracts", 1), "not valid UTF-8"},
		"truncated":     {good[:len(good)-10], "unexpected EOF"},
	} {
		in.Reports = map[string][]byte{"ginkgo.json": []byte(c.raw)}
		if o, e := Parse(in); e == nil || !strings.Contains(e.Error(), c.err) || !ginkgoHas(o, "GINKGO_INVALID_REPORT") {
			t.Fatal(name, o, e)
		}
	}
}

// TestGinkgoBeforeSuiteSkipShape models qualification case 28 (Skip() in
// BeforeSuite) from the pinned suite.go reading: the suite records a reason and
// may still report success with exit 0. Actual observed values are NOT_RUN.
func TestGinkgoBeforeSuiteSkipShape(t *testing.T) {
	rep, in := ginkgoMixed()
	specs := ginkgoSpecs(rep)
	specs[0]["State"] = "skipped"
	for _, s := range specs[1:] {
		s["NumAttempts"] = 0
		delete(s, "Failure")
		if s["State"] != "pending" {
			s["State"] = "skipped"
		}
	}
	rep["SuiteSucceeded"] = true
	rep["SpecialSuiteFailureReasons"] = []string{"Suite skipped in BeforeSuite"}
	in.ExitCode = 0
	ginkgoEncode(&in, rep)
	o, e := Parse(in)
	if e != nil || o.Complete {
		t.Fatal(o, e)
	}
	for _, code := range []string{"GINKGO_NOT_ENTERED", "GINKGO_SUITE_PROBLEM", "GINKGO_SUITE_FAILURE_REASON"} {
		if !ginkgoHas(o, code) {
			t.Fatal("missing", code, o.Problems)
		}
	}
	if ginkgoHas(o, "GINKGO_EXIT_SUITE_CONTRADICTION") {
		t.Fatal("exit 0 with SuiteSucceeded true is coherent", o.Problems)
	}
}

// TestGinkgoOrderedFollowOnFailure records N5: an ordinary leaf failure in an
// Ordered container leaves later specs skipped with zero attempts and a
// populated Failure, which is NOT_ENTERED and keeps the run incomplete.
func TestGinkgoOrderedFollowOnFailure(t *testing.T) {
	first := ginkgoRecord([]string{"Flow"}, "first", "It", "failed", 1)
	first["Failure"] = ginkgoFailureRecord("boom", "leaf-node")
	second := ginkgoRecord([]string{"Flow"}, "second", "It", "skipped", 0)
	second["Failure"] = ginkgoFailureRecord("Spec skipped because an earlier spec in an ordered container failed", "leaf-node")
	rep := ginkgoSuite(false, 2, 2, nil, first, second)
	in := tr.Input{Runner: ginkgoRunner, Target: ginkgoTargetID, SourceRoot: ginkgoRoot, Expected: []string{ginkgoID("Flow first"), ginkgoID("Flow second")}, ExitCode: 1, SuccessExitCodes: []int{0}, FailureExitCodes: []int{1}}
	ginkgoEncode(&in, rep)
	o, e := Parse(in)
	if e != nil || o.Complete || !ginkgoHas(o, "GINKGO_NOT_ENTERED") || o.Tests[0].State != tr.Failed || o.Tests[1].State != tr.Unknown {
		t.Fatal(o, e)
	}
	if n := tr.Normalize(in, o); n.Complete || n.Tests[0].State != tr.Unknown {
		t.Fatal("ordered follow-on admitted", n)
	}
}

func ginkgoTestRequest(t *testing.T, q *tr.Request) {
	t.Helper()
	root, e := filepath.EvalSymlinks(t.TempDir())
	if e != nil {
		t.Fatal(e)
	}
	q.Target = ginkgoTargetID
	q.ExpectedTests = []string{ginkgoID("Math adds"), ginkgoID("Math subtracts")}
	q.Project = "calc_suite_test.go"
	q.InputFiles = map[string]string{q.Project: strings.Repeat("a", 64)}
	q.Root = root
}

func TestGinkgoClosedBuild(t *testing.T) {
	valid := func() tr.Request {
		q := tr.Request{Runner: ginkgoRunner, Executable: "/calc.test", ReportDir: "/fresh"}
		ginkgoTestRequest(t, &q)
		return q
	}
	v, e := Build(valid())
	want := []string{"-test.run=^TestCalc$", "-test.timeout=0", "-ginkgo.json-report=/fresh/ginkgo.json", "-ginkgo.seed=1", "-ginkgo.randomize-all=false", "-ginkgo.fail-fast=false", "-ginkgo.fail-on-pending=false", "-ginkgo.fail-on-empty=true", "-ginkgo.flake-attempts=1", "-ginkgo.dry-run=false", "-ginkgo.timeout=1h", "-ginkgo.grace-period=1s", "-ginkgo.sleep-on-failure=0", "-ginkgo.poll-progress-after=0", "-ginkgo.poll-progress-interval=0", "-ginkgo.output-interceptor-mode=none", "-ginkgo.no-color=true"}
	if e != nil || len(v.Argv) != 17 || !reflect.DeepEqual(v.Argv, want) || len(v.Phases) != 0 || !reflect.DeepEqual(v.ReportPaths, []string{"ginkgo.json"}) || !reflect.DeepEqual(v.FailureExitCodes, []int{1}) || !reflect.DeepEqual(v.SuccessExitCodes, []int{0}) {
		t.Fatal(v, e)
	}
	if !reflect.DeepEqual(v.Environment, map[string]string{"GOTOOLCHAIN": "local", "GOPROXY": "off", "GOSUMDB": "off", "GOFLAGS": "", "GOWORK": "off"}) {
		t.Fatal(v.Environment)
	}
	q := valid()
	q.Selectors = []string{ginkgoID("Math adds")}
	v, e = Build(q)
	focus := `^Calc \(v1\.2\) \[x\]\+ (Math adds)$`
	if e != nil || len(v.Argv) != 18 || v.Argv[17] != "-ginkgo.focus="+focus || !reflect.DeepEqual(v.Argv[:17], want) {
		t.Fatal(v, e)
	}
	for _, a := range v.Argv {
		for _, banned := range []string{"-test.parallel", "-test.count", "-test.shuffle"} {
			if strings.HasPrefix(a, banned) {
				t.Fatal("banned argv", a)
			}
		}
	}
	// Ginkgo matches the focus unanchored against SuiteDescription + " " + FullText.
	re := regexp.MustCompile(focus)
	if !re.MatchString(ginkgoDesc + " Math adds") {
		t.Fatal("selected spec not matched")
	}
	for _, decoy := range []string{ginkgoDesc + " Math adds more", ginkgoDesc + " Math addsX", "X" + ginkgoDesc + " Math adds", "Calc (v1x2) [x]+ Math adds", "Calc (v1.2) xx Math adds", ginkgoDesc + " Math subtracts"} {
		if re.MatchString(decoy) {
			t.Fatal("decoy matched", decoy)
		}
	}
	for name, c := range map[string]struct {
		change func(*tr.Request)
		err    string
	}{
		"no-wrapper":         {func(r *tr.Request) { r.Target = ginkgoDesc }, "Target must be GoWrapper::SuiteDescription"},
		"lower-wrapper":      {func(r *tr.Request) { r.Target = "Testcalc::" + ginkgoDesc }, "Target must be GoWrapper::SuiteDescription"},
		"colon-desc":         {func(r *tr.Request) { r.Target = "TestCalc::a::b" }, "Target must be GoWrapper::SuiteDescription"},
		"trailing-colon":     {func(r *tr.Request) { r.Target = "TestCalc::Calc:" }, "Target must be GoWrapper::SuiteDescription"},
		"empty-expected":     {func(r *tr.Request) { r.ExpectedTests = nil }, "1..4096 expected tests"},
		"duplicate-expected": {func(r *tr.Request) { r.ExpectedTests = append(r.ExpectedTests, r.ExpectedTests[0]) }, "unique Target::FullText"},
		"foreign-expected":   {func(r *tr.Request) { r.ExpectedTests = []string{"TestCalc::Other::adds"} }, "unique Target::FullText"},
		"unknown-selector":   {func(r *tr.Request) { r.Selectors = []string{ginkgoID("Math")} }, "selectors must be unique expected identities"},
		"duplicate-selector": {func(r *tr.Request) { r.Selectors = []string{r.ExpectedTests[0], r.ExpectedTests[0]} }, "selectors must be unique expected identities"},
		"config":             {func(r *tr.Request) { r.Config = "ginkgo.cfg" }, "does not admit configuration"},
		"reporter":           {func(r *tr.Request) { r.Reporter = "r" }, "does not admit configuration"},
		"report-files":       {func(r *tr.Request) { r.ReportFiles = []string{"x.json"} }, "does not admit configuration"},
		"tools":              {func(r *tr.Request) { r.Tools = map[string]tr.Tool{"other": {Executable: "/other"}} }, "does not admit configuration"},
		"no-project":         {func(r *tr.Request) { r.Project = "" }, "pinned literal suite file"},
		"non-test-project":   {func(r *tr.Request) { r.Project = "calc.go"; r.InputFiles = map[string]string{"calc.go": "x"} }, "pinned literal suite file"},
		"unpinned-project":   {func(r *tr.Request) { r.InputFiles = nil }, "pinned literal suite file"},
		"relative-root":      {func(r *tr.Request) { r.Root = "src" }, "symlink-resolved Root"},
	} {
		r := valid()
		c.change(&r)
		if _, e := Build(r); e == nil || !strings.Contains(e.Error(), c.err) {
			t.Fatalf("%s: want %q, got %v", name, c.err, e)
		}
	}
	r := valid()
	link := filepath.Join(t.TempDir(), "link")
	if e := os.Symlink(r.Root, link); e != nil {
		t.Fatal(e)
	}
	r.Root = link
	if _, e := Build(r); e == nil || !strings.Contains(e.Error(), "symlink-resolved Root") {
		t.Fatal("symlinked Root admitted", e)
	}
}

// TestGinkgoFocusBound pins the whole focus element at the shared executor's
// 4096-byte per-argument limit.
func TestGinkgoFocusBound(t *testing.T) {
	prefix := len("-ginkgo.focus=^" + regexp.QuoteMeta(ginkgoDesc) + " (")
	for _, c := range []struct {
		n  int
		ok bool
	}{{4096 - prefix - 2, true}, {4096 - prefix - 1, false}} {
		q := tr.Request{Runner: ginkgoRunner, Executable: "/calc.test", ReportDir: "/fresh"}
		ginkgoTestRequest(t, &q)
		id := ginkgoID(strings.Repeat("a", c.n))
		q.ExpectedTests, q.Selectors = []string{id}, []string{id}
		v, e := Build(q)
		if c.ok && (e != nil || len(v.Argv[17]) != 4096) {
			t.Fatal("bound-sized focus refused", e)
		}
		if !c.ok && (e == nil || e.Error() != "ginkgo focus argument exceeds 4096 bytes") {
			t.Fatal("oversized focus admitted", e)
		}
	}
}
