import org.gradle.api.tasks.testing.Test
import java.awt.image.BufferedImage
import java.util.Properties
import javax.imageio.ImageIO

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.plugin.compose")
    // PHOTOPAR-11: kotlinx.serialization for the persisted camera-backup queue index (mirrors
    // beamfall-android-ui kit's FileOfflinePackStore pattern).
    id("org.jetbrains.kotlin.plugin.serialization")
    alias(libs.plugins.roborazzi)
    // TEST-ANDROID-2 / ADR-0121 §4: JVM unit-test coverage (koverXmlReportDebug).
    alias(libs.plugins.kover)
    // TECHAUDIT-5: consumes the checked-in baseline profile generated by
    // :baselineprofile-mobile — adds the `nonMinifiedRelease` benchmark variant used for
    // generation and wires the profile into the release build.
    alias(libs.plugins.baselineprofile)
}

// ── Release signing (review C5) ────────────────────────────────────────────────────────────────
// The upload key is supplied by the operator at build time and is NEVER committed. Two sources are
// supported, env vars taking precedence (CI) over the gitignored keystore.properties file (local):
//   keystore.properties (gitignored):  storeFile, storePassword, keyAlias, keyPassword
//   environment variables:             BEAMFALL_KEYSTORE_PATH, BEAMFALL_KEYSTORE_PASSWORD,
//                                      BEAMFALL_KEY_ALIAS, BEAMFALL_KEY_PASSWORD
// When no credentials are present (CI smoke builds, contributors), the release signingConfig is
// simply not created and `release` builds stay unsigned — the build still succeeds.
val keystoreProps =
    Properties().apply {
        val f = rootProject.file("keystore.properties")
        if (f.exists()) f.inputStream().use { load(it) }
    }

fun signingValue(
    propKey: String,
    envKey: String,
): String? =
    (System.getenv(envKey)?.takeIf { it.isNotBlank() } ?: keystoreProps.getProperty(propKey))
        ?.takeIf { it.isNotBlank() }

val keystorePath = signingValue("storeFile", "BEAMFALL_KEYSTORE_PATH")
val keystorePassword = signingValue("storePassword", "BEAMFALL_KEYSTORE_PASSWORD")
val keyAliasValue = signingValue("keyAlias", "BEAMFALL_KEY_ALIAS")
val keyPasswordValue = signingValue("keyPassword", "BEAMFALL_KEY_PASSWORD")
val hasReleaseSigning =
    keystorePath != null && keystorePassword != null && keyAliasValue != null && keyPasswordValue != null

android {
    namespace = "com.beamfall.mobile"
    compileSdk = 36

    defaultConfig {
        applicationId = "com.beamfall.mobile"
        minSdk = 29
        targetSdk = 36
        // ANDROID-RELEASE-VERSION-SOURCE-1: read from the root project's single authoritative
        // source (gradle/version.properties + git commit-history depth) rather than restating a
        // literal here — see build.gradle.kts.
        versionCode = rootProject.extra["releaseVersionCode"] as Int
        versionName = rootProject.extra["releaseVersionName"] as String
        buildConfigField("String", "RELEASE_COMMIT_SHA", "\"${rootProject.extra["releaseCommitSha"]}\"")
        // AUDIT-ANDROID-9: required for the app-mobile androidTest source set (instrumented smoke
        // test) so `:app-mobile:connectedDebugAndroidTest` actually runs code instead of no-oping.
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    buildFeatures {
        buildConfig = true
        compose = true
    }

    signingConfigs {
        if (hasReleaseSigning) {
            create("release") {
                storeFile = rootProject.file(keystorePath!!)
                storePassword = keystorePassword
                keyAlias = keyAliasValue
                keyPassword = keyPasswordValue
            }
        }
    }
    // UI-state screenshot catalog runs as JVM unit tests via Robolectric (no device). Robolectric
    // needs merged Android resources + the manifest to inflate Compose; default-return keeps any
    // unstubbed framework call deterministic instead of throwing. See ui-catalog/README.md.
    testOptions {
        unitTests.isIncludeAndroidResources = true
        unitTests.isReturnDefaultValues = true
    }

    buildTypes {
        debug {
            isPseudoLocalesEnabled = true
        }
        release {
            // Use the operator-supplied upload key when present; otherwise leave unsigned so CI and
            // contributor builds don't break (an unsigned release artifact is not Play-uploadable).
            signingConfig = if (hasReleaseSigning) signingConfigs.getByName("release") else null
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
        }
        create("benchmark") {
            initWith(getByName("release"))
            signingConfig = signingConfigs.getByName("debug")
            isDebuggable = false
            matchingFallbacks += listOf("release")
        }
    }
}

// ORG-33 demoted the heavy Roborazzi screenshot test out of the *plain* unit-test gate. But the
// catalog record/verify tasks (recordUiCatalog / verifyUiCatalog, via record/verifyRoborazziDebug)
// drive this same `testDebugUnitTest` task — so excluding it unconditionally froze the catalog: the
// screenshot test never re-rendered and verifyUiCatalog only diffed committed images against
// themselves. Keep the exclude for the bare unit-test run, but lift it whenever a Roborazzi
// record/verify task is in the graph (i.e. exactly when the catalog gate is being exercised), so the
// blocking catalog gate actually renders + diffs every entry (ADR-0100 + android-ui ADR-0001 a11y variants included).
gradle.taskGraph.whenReady {
    val roborazziActive =
        allTasks.any {
            it.project == project &&
                it.name in setOf("recordRoborazziDebug", "verifyRoborazziDebug", "compareRoborazziDebug")
        }
    tasks.withType<Test>().configureEach {
        if (name == "testDebugUnitTest" && !roborazziActive) {
            exclude("com/beamfall/mobile/UiCatalogScreenshotTest.class")
        }
    }
}

kover {
    reports {
        variant("debug") {
            xml {
                xmlFile = layout.buildDirectory.file("reports/kover/report.xml")
            }
        }
    }
}

// TECHAUDIT-5: baseline-profile consumption. The generator (:baselineprofile-mobile) writes
// src/main/baselineProfiles/baseline-prof.txt, which is bundled into the release APK/AAB and AOT
// compiled by R8; androidx.profileinstaller (below) installs it on-device at first launch.
baselineProfile {
    dexLayoutOptimization = true
}

tasks.matching { it.name in setOf("koverGenerateArtifact", "koverXmlReportDebug") }.configureEach {
    dependsOn("testDebugUnitTest")
}

dependencies {
    implementation(libs.beamfall.android.ui.kit)
    implementation(libs.beamfall.android.ui.ui)
    implementation(platform(libs.compose.bom))
    implementation(libs.androidx.activity.compose)
    implementation(libs.androidx.biometric)
    implementation(libs.androidx.fragment.ktx)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    implementation(libs.androidx.lifecycle.runtime.compose)
    implementation(libs.androidx.lifecycle.viewmodel.compose)
    implementation(libs.kotlinx.coroutines.android)
    implementation(libs.compose.material3)
    implementation(libs.compose.material3.window.size)
    implementation(libs.compose.ui)
    implementation(libs.compose.ui.tooling.preview)
    implementation(libs.bundles.media3)
    // AND-2: LGPL-only FFmpeg audio extension + BeamfallRenderersFactory (ADR-0017 §3).
    implementation(project(":decoder-ffmpeg"))
    implementation(libs.play.services.cast.framework)
    implementation(libs.play.billing)
    // SETTINGS-3 (ADR-0172 §2): device-scoped DataStore<Preferences> layer (non-secret; Law I).
    implementation(libs.androidx.datastore.preferences)
    implementation(libs.coil.compose)
    implementation(libs.coil.network.okhttp)
    // PHOTOPAR-11 (ADR-0045 §2.11): camera-backup background-transfer worker + its persisted queue.
    implementation(libs.androidx.work.runtime.ktx)
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.okhttp)
    // TECHAUDIT-5: installs the checked-in baseline profile at app startup.
    implementation(libs.androidx.profileinstaller)
    // TECHAUDIT-5: names :baselineprofile-mobile as this app's baseline-profile producer, so
    // `generateBaselineProfile` drives that module's BaselineProfileRule instead of no-oping.
    baselineProfile(project(":baselineprofile-mobile"))
    debugImplementation(libs.compose.ui.tooling)
    // Merges a bare ComponentActivity (MAIN/LAUNCHER) into the debug manifest so the Roborazzi
    // screenshot tests' createComposeRule can launch a host activity under Robolectric.
    debugImplementation(libs.compose.ui.test.manifest)

    // UI-state screenshot catalog (JVM unit tests, src/test). Roborazzi renders Compose under
    // Robolectric and writes PNG + the semantics-tree dump consumed by the LLM refiner.
    testImplementation(platform(libs.compose.bom))
    testImplementation(libs.junit)
    // SETTINGS-3: JVM round-trip test drives an on-disk DataStore<Preferences> directly.
    testImplementation(libs.androidx.datastore.preferences)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.androidx.test.ext.junit)
    testImplementation(libs.compose.ui.test.junit4)
    testImplementation(libs.compose.ui.test.manifest)
    testImplementation(libs.roborazzi)
    testImplementation(libs.roborazzi.compose)
    testImplementation(libs.roborazzi.junit.rule)
    testImplementation(libs.kotlinx.coroutines.test)
    // TEST-ANDROID-3: MockWebServer integration tests (ADR-0121 §3 — JVM-only, no device).
    testImplementation(libs.okhttp.mockwebserver)
    testImplementation(libs.okhttp.tls)
    // PHOTOPAR-11: drives BackupWorker deterministically via TestListenableWorkerBuilder.
    testImplementation(libs.androidx.work.testing)

    // AUDIT-ANDROID-9: real instrumented smoke test (src/androidTest) so
    // :app-mobile:connectedDebugAndroidTest exercises actual on-device code.
    androidTestImplementation(platform(libs.compose.bom))
    androidTestImplementation(libs.compose.ui.test.junit4)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.androidx.test.ext.junit)
    androidTestImplementation(libs.androidx.test.runner)
    // PHOTOPAR-11: CameraBackupInstrumentedTest is the ticket's AVD lane — it uploads real bytes
    // over a real socket to a MockWebServer standing in for the server (see that test's header).
    androidTestImplementation(libs.okhttp.mockwebserver)
}

// ── UI-state screenshot catalog: record / verify wiring (ui-catalog/SPEC.md) ──────────────────
//
// The screenshot tests write the *current* render to ui-catalog/images/<id>.png (via Roborazzi's
// captureRoboImage) plus the semantics dump to images/<id>.txt. The SPEC then layers a regression
// gate on top: baselines/<id>.png is the committed golden; diffs/<id>.png is the (generated)
// baseline-vs-current delta written only on mismatch. We implement that gate here with two tasks
// over the same render, so a baseline only ever changes through an explicit `record`.
//
//   ./gradlew :app-mobile:recordUiCatalog   re-renders images/, then blesses baselines/ from them.
//   ./gradlew :app-mobile:verifyUiCatalog   re-renders images/, then diffs each vs baselines/,
//                                           writing diffs/<id>.png on mismatch and failing if any differ.
//
val uiCatalogDir = rootProject.layout.projectDirectory.dir("ui-catalog")

// recordRoborazziDebug forces the test task to (re)write images/. The Roborazzi plugin registers it
// during afterEvaluate, so depend on it by name (resolved lazily) rather than tasks.named() here.
tasks.register("recordUiCatalog") {
    group = "ui-catalog"
    description = "Re-render the catalog and bless ui-catalog/baselines/ from ui-catalog/images/."
    dependsOn("recordRoborazziDebug")
    doLast {
        val images = uiCatalogDir.dir("images").asFile
        val baselines = uiCatalogDir.dir("baselines").asFile.apply { mkdirs() }
        var blessed = 0
        // Only bless the mobile module's own cells, so :app-mobile never overwrites :app-tv baselines.
        // Bless both the PNG render and the .txt semantics dump (the LLM's structural input), so a
        // structural-tree change with no pixel delta is also captured.
        images
            .listFiles { f ->
                (f.extension == "png" || f.extension == "txt") && f.name.startsWith("androidmobile.")
            }?.sortedBy { it.name }
            ?.forEach { src ->
                src.copyTo(File(baselines, src.name), overwrite = true)
                blessed++
            }
        logger.lifecycle("ui-catalog: blessed $blessed mobile baseline(s) into ${baselines.relativeTo(rootDir)}")
    }
}

tasks.register("verifyUiCatalog") {
    group = "ui-catalog"
    description = "Re-render the catalog and diff ui-catalog/images/ against ui-catalog/baselines/."
    dependsOn("recordRoborazziDebug")
    doLast {
        val images = uiCatalogDir.dir("images").asFile
        val baselines = uiCatalogDir.dir("baselines").asFile
        val diffs = uiCatalogDir.dir("diffs").asFile.apply { mkdirs() }
        val mismatches = mutableListOf<String>()
        // Only diff the mobile module's own cells against their baselines.
        images
            .listFiles { f -> f.extension == "png" && f.name.startsWith("androidmobile.") }
            ?.sortedBy { it.name }
            ?.forEach { current ->
                File(diffs, current.name).delete()
                val baseline = File(baselines, current.name)
                if (!baseline.exists()) {
                    mismatches += "${current.name} (no baseline — run recordUiCatalog)"
                    return@forEach
                }
                val diff = writeImageDiff(baseline, current, File(diffs, current.name))
                if (diff > 0) mismatches += "${current.name} ($diff differing px — see diffs/${current.name})"
            }
        // Also gate the .txt semantics-tree dumps (now deterministic via stableForCatalog()): a
        // structural change with no pixel delta must still red the build.
        images
            .listFiles { f -> f.extension == "txt" && f.name.startsWith("androidmobile.") }
            ?.sortedBy { it.name }
            ?.forEach { current ->
                val baseline = File(baselines, current.name)
                if (!baseline.exists()) {
                    mismatches += "${current.name} (no baseline — run recordUiCatalog)"
                    return@forEach
                }
                if (baseline.readText() != current.readText()) {
                    mismatches += "${current.name} (semantics-tree dump diverged)"
                }
            }
        if (mismatches.isNotEmpty()) {
            throw GradleException(
                "ui-catalog regression: ${mismatches.size} entr(y/ies) diverged from baseline:\n  " +
                    mismatches.joinToString("\n  ") +
                    "\nIf intentional, re-bless with ./gradlew :app-mobile:recordUiCatalog.",
            )
        }
        logger.lifecycle("ui-catalog: all mobile entries match baselines.")
    }
}

/**
 * Pixel-diffs [baseline] against [current]; returns the count of differing pixels (0 == match) and,
 * when non-zero, writes a red-highlight delta PNG to [diffOut] (SPEC's diffs/<id>.png). A size
 * mismatch counts as a full diff. Throws [GradleException] if either image cannot be decoded —
 * an unreadable baseline or render is a failure, never a match. Pure Java2D — no extra deps, so
 * the gate stays offline-safe.
 */
fun writeImageDiff(
    baseline: File,
    current: File,
    diffOut: File,
): Long {
    // An unreadable baseline or render must fail loudly, not fall through a sentinel that a
    // ">0" check can confuse with "no difference".
    val a = ImageIO.read(baseline) ?: throw GradleException("ui-catalog: cannot read baseline image ${baseline.name}")
    val b = ImageIO.read(current) ?: throw GradleException("ui-catalog: cannot read rendered image ${current.name}")
    if (a.width != b.width || a.height != b.height) {
        ImageIO.write(b, "png", diffOut)
        return (b.width.toLong() * b.height.toLong()).coerceAtLeast(1)
    }
    val out = BufferedImage(a.width, a.height, BufferedImage.TYPE_INT_ARGB)
    var differing = 0L
    for (y in 0 until a.height) {
        for (x in 0 until a.width) {
            val pa = a.getRGB(x, y)
            val pb = b.getRGB(x, y)
            if (pa != pb) {
                differing++
                out.setRGB(x, y, 0xFFFF0000.toInt())
            } else {
                // Dim the matching pixels so the diff overlay reads at a glance.
                val gray = (((pa shr 16 and 0xFF) + (pa shr 8 and 0xFF) + (pa and 0xFF)) / 3) / 3
                out.setRGB(x, y, (0xFF shl 24) or (gray shl 16) or (gray shl 8) or gray)
            }
        }
    }
    if (differing > 0) {
        diffOut.parentFile.mkdirs()
        ImageIO.write(out, "png", diffOut)
    }
    return differing
}

// ── ANDROID-LIBMPV-RUNG-SHIPS-1: the artifact's engine set must match the documented claim ──────
//
// ADR-0017 §3's ladder is ExoPlayer -> libmpv -> server transcode. Engine 2's native half is an
// opt-in build in `beamfall-android-ui`'s `:kit` (`-Pbeamfall.libmpv=true`) that this repo cannot
// enable: the release path consumes `:kit` as a published AAR. The recorded direction and its
// evidence are in docs/engine-ladder-shipping-status.md, which carries a machine-read claim block.
//
// Two tasks keep that claim honest instead of leaving it as prose:
//
//   :app-mobile:verifyShippedEngineSet      reads the release variant's merged native libraries — the
//                                       exact set the artifact packages, from this module and from
//                                       every dependency AAR — and reds on any disagreement with
//                                       the claim block, in every direction.
//   :app-mobile:verifyShippedEngineSetTest  planted-red self-test over synthetic fixtures, proving the
//                                       check still reds on each disagreement class before it runs
//                                       over the real tree (the repo's <x>GateTest/<x>Gate idiom).
//
// Both hang off testDebugUnitTest so `make gate` runs them; the root gate wiring is outside this
// ticket's Allowed Paths.

/** Doc holding the machine-read claim about what the release artifacts package. */
val engineSetClaimDoc =
    rootProject.layout.projectDirectory
        .file("docs/engine-ladder-shipping-status.md")
        .asFile

/**
 * Libraries whose presence *defines* the libmpv rung: the engine itself and this project's JNI
 * bridge. Engine 1's LGPL FFmpeg audio extension (`libffmpegJNI.so`) is deliberately not one.
 */
val mpvRungMarkerNames = setOf("libmpv.so", "libbeamfall_mpv.so")

/**
 * Every shared object `beamfall-android-ui`'s kit/scripts/build_libmpv.sh stages into
 * `kit/src/main/jniLibs/`. That directory is a default AGP source dir, so it is packaged whether or
 * not `-Pbeamfall.libmpv=true` was passed — see the doc section "Why the app modules exclude the
 * rung's libraries from packaging". While the claim reads `libmpv-shipped: no` these are excluded
 * from this artifact; the exclusion lifts automatically when the claim flips.
 */
val mpvRungNativeLibraryNames =
    listOf(
        "libass.so",
        "libavcodec.so",
        "libavfilter.so",
        "libavformat.so",
        "libavutil.so",
        "libbeamfall_mpv.so",
        "libc++_shared.so",
        "libfreetype.so",
        "libfribidi.so",
        "libharfbuzz-subset.so",
        "libharfbuzz.so",
        "libmpv.so",
        "libplacebo.so",
        "libswresample.so",
        "libswscale.so",
    )

/** The parsed claim block: whether the rung ships, and the complete set of packaged libraries. */
data class EngineSetClaim(
    val libmpvShipped: Boolean,
    val packagedNativeLibraries: Set<String>,
)

/**
 * Parses [doc]'s machine-read claim block. A missing doc, a missing or malformed block, or a block
 * that contradicts itself all throw — the claim is never inferred from a partial read.
 */
fun readEngineSetClaim(doc: File): EngineSetClaim {
    if (!doc.isFile) {
        throw GradleException("engine-set: claim doc ${doc.path} is missing; the artifact claim cannot be read.")
    }
    val block =
        doc
            .readText()
            .substringAfter("<!-- engine-set:begin -->", "")
            .substringBefore("<!-- engine-set:end -->", "")
    val shipped =
        when (val raw = engineSetClaimValue(doc, block, "libmpv-shipped")) {
            "yes" -> true
            "no" -> false
            else -> throw GradleException("engine-set: ${doc.name} has 'libmpv-shipped: $raw'; expected yes or no.")
        }
    val packaged =
        engineSetClaimValue(doc, block, "packaged-native-libraries")
            .split(",")
            .map { it.trim() }
            .filter { it.isNotEmpty() }
            .toSet()
    if (packaged.isEmpty()) {
        throw GradleException("engine-set: ${doc.name} lists no packaged native libraries; that cannot be right.")
    }
    val markersListed = packaged.any { it in mpvRungMarkerNames }
    if (markersListed != shipped) {
        throw GradleException(
            "engine-set: ${doc.name} contradicts itself — 'libmpv-shipped: ${if (shipped) "yes" else "no"}' " +
                "while packaged-native-libraries ${if (markersListed) "lists" else "omits"} an mpv marker library.",
        )
    }
    return EngineSetClaim(shipped, packaged)
}

/** Reads exactly one `key: value` line out of the claim block, or throws. */
fun engineSetClaimValue(
    doc: File,
    block: String,
    key: String,
): String {
    val values =
        block
            .lineSequence()
            .map { it.trim() }
            .filter { it.startsWith("$key:") }
            .map { it.removePrefix("$key:").trim() }
            .toList()
    return values.singleOrNull()
        ?: throw GradleException(
            "engine-set: ${doc.name} must carry exactly one '$key:' line inside its engine-set " +
                "claim block; found ${values.size}.",
        )
}

/** Distinct native library file names packaged under [root], sorted. */
fun packagedNativeLibrariesUnder(root: File): List<String> =
    root
        .walkTopDown()
        .filter { it.isFile && it.name.endsWith(".so") }
        .map { it.name }
        .distinct()
        .sorted()
        .toList()

/** Reds unless the documented claim and the artifact agree, in every direction. */
fun assertEngineSetClaim(
    moduleLabel: String,
    doc: File,
    packagedNativeLibraries: List<String>,
) {
    val claim = readEngineSetClaim(doc)
    val markers = packagedNativeLibraries.filter { it in mpvRungMarkerNames }
    val unexpected = packagedNativeLibraries.filterNot { it in claim.packagedNativeLibraries }
    val absent = claim.packagedNativeLibraries.filterNot { it in packagedNativeLibraries }.sorted()
    val problems = mutableListOf<String>()
    if (claim.libmpvShipped && markers.isEmpty()) {
        problems += "claim reads 'libmpv-shipped: yes' but the artifact packages no mpv marker library"
    }
    if (!claim.libmpvShipped && markers.isNotEmpty()) {
        problems += "claim reads 'libmpv-shipped: no' but the artifact packages ${markers.joinToString()}"
    }
    if (unexpected.isNotEmpty()) {
        problems += "artifact packages ${unexpected.joinToString()}, which the claim does not list"
    }
    if (absent.isNotEmpty()) {
        problems += "claim lists ${absent.joinToString()}, which the artifact does not package"
    }
    if (problems.isEmpty()) return
    throw GradleException(
        "engine-set: $moduleLabel disagrees with ${doc.name}:\n  " + problems.joinToString("\n  ") +
            "\nReconcile the artifact and the claim block together — see " +
            "docs/engine-ladder-shipping-status.md.",
    )
}

/** Runs [probe] and reds if it did NOT throw — a control that stopped controlling is a failure. */
fun expectEngineSetRed(
    disagreementClass: String,
    probe: () -> Unit,
) {
    try {
        probe()
    } catch (expected: GradleException) {
        logger.info("engine-set self-test: red as required for \"$disagreementClass\" (${expected.message})")
        return
    }
    throw GradleException(
        "engine-set self-test: the check stayed green for \"$disagreementClass\" — it no longer controls.",
    )
}

/** Writes a claim-block fixture. */
fun writeEngineSetClaimFixture(
    target: File,
    shipped: String,
    packaged: String,
): File =
    target.apply {
        parentFile.mkdirs()
        writeText(
            "preamble\n\n<!-- engine-set:begin -->\nlibmpv-shipped: $shipped\n" +
                "packaged-native-libraries: $packaged\n<!-- engine-set:end -->\n",
        )
    }

android {
    packaging {
        jniLibs {
            // Configuration-time read: the claim decides whether this artifact carries the rung.
            if (!readEngineSetClaim(engineSetClaimDoc).libmpvShipped) {
                excludes += mpvRungNativeLibraryNames.map { "lib/*/$it" }
            }
        }
    }
}

tasks.register("verifyShippedEngineSet") {
    group = "verification"
    description = "Check the release artifact's native-library set against docs/engine-ladder-shipping-status.md."
    val mergeReleaseNativeLibs = tasks.named("mergeReleaseNativeLibs")
    dependsOn(mergeReleaseNativeLibs)
    val mergedOutputs = mergeReleaseNativeLibs.map { it.outputs.files }
    val moduleLabel = path
    doLast {
        val roots = mergedOutputs.get().files.filter { it.isDirectory }
        // An absent merge output must red, never pass vacuously — that is how a gate quietly stops
        // gating.
        if (roots.isEmpty()) {
            throw GradleException(
                "engine-set: $moduleLabel produced no merged native-library directory; " +
                    "the check cannot read what the artifact packages.",
            )
        }
        val packaged = roots.flatMap { packagedNativeLibrariesUnder(it) }.distinct().sorted()
        if (packaged.isEmpty()) {
            throw GradleException("engine-set: $moduleLabel packages no native library at all; the check has no subject.")
        }
        assertEngineSetClaim(moduleLabel, engineSetClaimDoc, packaged)
        logger.lifecycle("engine-set: $moduleLabel matches ${engineSetClaimDoc.name} (${packaged.size} native librar(y/ies)).")
    }
}

tasks.register("verifyShippedEngineSetTest") {
    group = "verification"
    description = "Planted-red self-test: prove verifyShippedEngineSet reds on every claim/artifact disagreement."
    val fixtureRoot = layout.buildDirectory.dir("engine-set-selftest")
    val moduleLabel = path
    doLast {
        val fixtures = fixtureRoot.get().asFile
        fixtures.deleteRecursively()
        val elfMagic = byteArrayOf(0x7F, 0x45, 0x4C, 0x46)
        val withoutRung = File(fixtures, "without-rung/lib/arm64-v8a").apply { mkdirs() }
        File(withoutRung, "libffmpegJNI.so").writeBytes(elfMagic)
        File(withoutRung, "notes.txt").writeText("not a shared object")
        val withRung = File(fixtures, "with-rung/lib/arm64-v8a").apply { mkdirs() }
        File(withRung, "libffmpegJNI.so").writeBytes(elfMagic)
        File(withRung, "libmpv.so").writeBytes(elfMagic)
        File(withRung, "libbeamfall_mpv.so").writeBytes(elfMagic)

        // The reader is under test too: it must ignore non-.so files and find both markers.
        val absent = packagedNativeLibrariesUnder(File(fixtures, "without-rung"))
        val present = packagedNativeLibrariesUnder(File(fixtures, "with-rung"))
        if (absent != listOf("libffmpegJNI.so")) {
            throw GradleException("engine-set self-test: reader returned $absent for a rung-free tree.")
        }
        if (present != listOf("libbeamfall_mpv.so", "libffmpegJNI.so", "libmpv.so")) {
            throw GradleException("engine-set self-test: reader missed the planted mpv libraries: $present.")
        }

        val claimsNoRung = writeEngineSetClaimFixture(File(fixtures, "claim-no.md"), "no", "libffmpegJNI.so")
        val claimsRung =
            writeEngineSetClaimFixture(
                File(fixtures, "claim-yes.md"),
                "yes",
                "libbeamfall_mpv.so, libffmpegJNI.so, libmpv.so",
            )

        // Agreeing pairs must stay green, or the check is merely broken rather than strict.
        assertEngineSetClaim(moduleLabel, claimsNoRung, absent)
        assertEngineSetClaim(moduleLabel, claimsRung, present)

        expectEngineSetRed("artifact carries the rung while the claim reads no") {
            assertEngineSetClaim(moduleLabel, claimsNoRung, present)
        }
        expectEngineSetRed("claim reads yes while the artifact carries no mpv marker") {
            assertEngineSetClaim(moduleLabel, claimsRung, absent)
        }
        expectEngineSetRed("artifact packages a library the claim does not list") {
            assertEngineSetClaim(moduleLabel, claimsNoRung, absent + "libsomethingnew.so")
        }
        expectEngineSetRed("claim lists a library the artifact does not package") {
            assertEngineSetClaim(moduleLabel, claimsNoRung, emptyList())
        }
        expectEngineSetRed("claim block contradicts itself") {
            assertEngineSetClaim(
                moduleLabel,
                writeEngineSetClaimFixture(File(fixtures, "claim-contradictory.md"), "no", "libffmpegJNI.so, libmpv.so"),
                absent,
            )
        }
        expectEngineSetRed("claim block missing from the doc") {
            assertEngineSetClaim(moduleLabel, File(fixtures, "claim-empty.md").apply { writeText("no block\n") }, absent)
        }
        expectEngineSetRed("claim doc absent") {
            assertEngineSetClaim(moduleLabel, File(fixtures, "does-not-exist.md"), absent)
        }
        logger.lifecycle("engine-set self-test: the check reds on all 7 disagreement classes.")
    }
}

// AGP registers testDebugUnitTest after this script is evaluated, so match lazily rather than
// tasks.named(), which would resolve too early.
tasks.matching { it.name == "testDebugUnitTest" }.configureEach {
    dependsOn("verifyShippedEngineSetTest", "verifyShippedEngineSet")
}
