package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"maps"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"sync"
	"testing"
	"time"
)

// frozenCoreVerbs is the CCF-V1-001 Core boundary from decision 0332, in the order root help lists it.
var frozenCoreVerbs = []string{"init", "adopt", "index", "query", "context", "impact", "affected", "prove", "cem", "ocm", "frontier", "dogfood"}

// hookPlumbingVerbs are the CCF-V1-003 adapter plumbing verbs runContext dispatches before the
// topLevelCommands check; they are undocumented, absent from root help and outside the freeze.
var hookPlumbingVerbs = []string{"native-hook", "authority-event", "qualified-event"}

// absentMember marks a wanted member that the frozen document must not carry.
type absentMember struct{}

// coreFreezeParent returns the full id of HEAD's first parent, the committed range base the
// --base modes need.
func coreFreezeParent(t *testing.T, root string) string {
	t.Helper()
	return strings.TrimSpace(affectedGit(t, root, "rev-parse", "HEAD~1"))
}

// coreFreezeCommit commits files on top of a fixture, so a frozen mode reaches a CCF-V1-007 (d)
// register row its base fixture never writes (proposed, V1-0350).
func coreFreezeCommit(t *testing.T, root string, files map[string]string) string {
	t.Helper()
	for relative, content := range files {
		if err := os.MkdirAll(filepath.Join(root, filepath.Dir(relative)), 0o755); err != nil {
			t.Fatal(err)
		}
		writeFixtureFile(t, root, relative, content)
	}
	affectedGit(t, root, "add", ".")
	affectedGit(t, root, "commit", "-qm", "add frozen enumeration fixture")
	return root
}

// jsonMember reads one dotted member path from a decoded JSON object.
func jsonMember(document map[string]any, path string) (any, bool) {
	var value any = document
	for _, name := range strings.Split(path, ".") {
		object, ok := value.(map[string]any)
		if !ok {
			return nil, false
		}
		if value, ok = object[name]; !ok {
			return nil, false
		}
	}
	return value, true
}

// coreEvidenceArguments builds a committed cem/0.2 map and bound OCM, and returns the read
// arguments of one CEM, OCM or frontier mode against them.
func coreEvidenceArguments(t *testing.T, verb string, extra ...string) []string {
	t.Helper()
	fixture := newOCMReadFixture(t)
	maps := map[string][]string{
		"cem":      {"--map", fixture.mapPath},
		"ocm":      {"--map", "change.ocm.json", "--cem", fixture.mapPath},
		"frontier": {"--cem", fixture.mapPath, "--ocm", "change.ocm.json", "--json"},
	}
	arguments := append([]string{"--root", fixture.root, verb}, extra...)
	arguments = append(arguments, maps[verb]...)
	return append(arguments, "--expected-base", fixture.base, "--target", fixture.target)
}

// TestCoreVerbsEmitTheFrozenProfiles pins CCF-V1-002: every frozen Core mode exits with its
// frozen code and emits one JSON document carrying the exact envelope and profile identifiers the
// freeze lists. Unless a case says otherwise the envelope is ok=true, mutates=false and exit 0. A
// change to any value here is a breaking change under CCF-V1-006 and needs a new profile version,
// an N-1 reader and a decision.
func TestCoreVerbsEmitTheFrozenProfiles(t *testing.T) {
	t.Parallel()
	genesis := "genesis-inventory/0.1-experimental"
	genesisSummary := "genesis-inventory-summary/0.1-experimental"
	task := "where is StableValue"
	excluded := map[string]string{
		"vendor/lib/lib.go":   "package lib\n\nfunc StableValue() string { return \"vendored\" }\n",
		"pkg/value_string.go": "// Code generated by stringer. DO NOT EDIT.\n\npackage main\n",
	}
	cases := []struct {
		name   string
		invoke func(*testing.T) []string
		exit   int
		want   map[string]any
	}{
		{"init summary", func(t *testing.T) []string {
			return activationArguments(newActivationFixture(t, "sha1"), "init", false)
		}, 0,
			map[string]any{"tool": "init", "inventory.profile": genesis, "inventory.summaryProfile": genesisSummary}},
		{"init full receipt", func(t *testing.T) []string { return activationArguments(newActivationFixture(t, "sha1"), "init", true) }, 0,
			map[string]any{"tool": "init", "inventory.profile": genesis}},
		{"adopt summary", func(t *testing.T) []string {
			return activationArguments(newActivationFixture(t, "sha1"), "adopt", false)
		}, 0,
			map[string]any{"tool": "adopt", "inventory.profile": genesis, "inventory.summaryProfile": genesisSummary}},
		{"index write", func(t *testing.T) []string { return []string{"--root", impactCLIRepository(t), "index"} }, 0,
			map[string]any{"command": "index", "profile": "corvint-index-snapshot/1", "mutates": true}},
		{"index if stale when fresh", func(t *testing.T) []string {
			root := impactCLIRepository(t)
			if code, _, stderr := runCLI(t, "--root", root, "index"); code != 0 {
				t.Fatalf("index: exit %d, stderr=%s", code, stderr)
			}
			return []string{"--root", root, "index", "--if-stale"}
		}, 0, map[string]any{"state": "fresh", "ok": absentMember{}, "profile": absentMember{}, "command": absentMember{}}},
		{"query repository task", func(t *testing.T) []string {
			return []string{"--root", impactCLIRepository(t), "query", "--task", task}
		}, 0,
			map[string]any{"tool": "query", "context.schema_version": float64(1), "context.mode": "query"}},
		{"query authority start", func(t *testing.T) []string {
			return []string{"--root", queryCLIRepository(t), "query", "--task", authorityStartPrompt, "--limit", "1"}
		}, 0, map[string]any{"tool": "query", "context.schema_version": float64(1), "context.mode": "query", "context.intent.id": "project-operations"}},
		{"query excluded sources", func(t *testing.T) []string {
			return []string{"--root", coreFreezeCommit(t, impactCLIRepository(t), excluded), "query", "--task", task}
		}, 0,
			map[string]any{"tool": "query", "context.schema_version": float64(1), "context.mode": "query"}},
		{"context task", func(t *testing.T) []string {
			return []string{"--root", impactCLIRepository(t), "context", "--task", task}
		}, 0,
			map[string]any{"tool": "context", "schema_version": float64(1)}},
		{"context reserved rows", func(t *testing.T) []string {
			spec := map[string]string{"docs/specs/queue.md": "# Queue spec\n\n- **QUE-001:** The roadmap is the only active work queue.\n"}
			root := coreFreezeCommit(t, queryCLIRepository(t), spec)
			return []string{"--root", root, "context", "--task", "Where does docs/specs/queue.md define the work queue", "--limit", "1"}
		}, 0,
			map[string]any{"tool": "context", "schema_version": float64(1)}},
		{"impact path", func(t *testing.T) []string {
			return []string{"--root", impactCLIRepository(t), "impact", "pkg/main.go"}
		}, 0,
			map[string]any{"tool": "impact", "context.schema_version": float64(1), "context.mode": "impact"}},
		{"impact path excluded sources", func(t *testing.T) []string {
			return []string{"--root", coreFreezeCommit(t, impactCLIRepository(t), excluded), "impact", "pkg/main.go"}
		}, 0,
			map[string]any{"tool": "impact", "context.schema_version": float64(1), "context.mode": "impact"}},
		{"impact committed range", func(t *testing.T) []string {
			root := impactCLIRepository(t)
			return []string{"--root", root, "impact", "--base", coreFreezeParent(t, root)}
		}, 0, map[string]any{"tool": "impact", "context.profile": "corvint-range-impact/0"}},
		{"impact untracked working tree", func(t *testing.T) []string {
			root := impactCLIRepository(t)
			writeFixtureFile(t, root, "pkg/extra.go", "package main\n")
			return []string{"--root", root, "impact", "--working-tree-untracked", "pkg/extra.go"}
		}, 0, map[string]any{"tool": "impact", "context.profile": "corvint-working-tree-impact/0"}},
		{"affected worktree", func(t *testing.T) []string { return []string{"--root", impactCLIRepository(t), "affected"} }, 0,
			map[string]any{"tool": "affected", "profile": "affected-plan/0"}},
		{"affected committed range", func(t *testing.T) []string {
			root := impactCLIRepository(t)
			return []string{"--root", root, "affected", "--base", coreFreezeParent(t, root)}
		}, 0, map[string]any{"tool": "affected", "profile": "affected-plan/0"}},
		{"prove task", func(t *testing.T) []string {
			return []string{"--root", impactCLIRepository(t), "prove", "--task", task}
		}, 0,
			map[string]any{"tool": "prove", "profile": "falsifiable-packet/0"}},
		{"prove path", func(t *testing.T) []string { return []string{"--root", impactCLIRepository(t), "prove", "pkg/main.go"} }, 0,
			map[string]any{"tool": "prove", "profile": "falsifiable-packet/0"}},
		{"prove committed range", func(t *testing.T) []string {
			root := impactCLIRepository(t)
			return []string{"--root", root, "prove", "--base", coreFreezeParent(t, root)}
		}, 0, map[string]any{"tool": "prove", "profile": "falsifiable-packet/0", "packet.profile": "corvint-range-impact/0"}},
		{"cem status", func(t *testing.T) []string { return coreEvidenceArguments(t, "cem", "status") }, 0,
			map[string]any{"tool": "cem-status", "verification.spec": "cem/0.2"}},
		{"cem verify", func(t *testing.T) []string { return coreEvidenceArguments(t, "cem", "verify") }, 0,
			map[string]any{"tool": "cem-verify", "verification.spec": "cem/0.2"}},
		{"ocm status", func(t *testing.T) []string { return coreEvidenceArguments(t, "ocm", "status") }, 0,
			map[string]any{"tool": "ocm-status", "verification.spec": "ocm/0.1-experimental"}},
		{"ocm verify", func(t *testing.T) []string { return coreEvidenceArguments(t, "ocm", "verify") }, 0,
			map[string]any{"tool": "ocm-verify", "verification.spec": "ocm/0.1-experimental"}},
		{"frontier open json", func(t *testing.T) []string { return coreEvidenceArguments(t, "frontier") }, 1,
			map[string]any{"profile": "frontier/0", "frontierState": "OPEN", "ok": absentMember{}, "mutates": absentMember{}}},
		{"dogfood status retained outcome", func(t *testing.T) []string {
			return []string{"--root", impactCLIRepository(t), "dogfood", "status", "--session-key", strings.Repeat("a", 64)}
		}, 0, map[string]any{"tool": "dogfood-status", "profile": "corvint-local-completion/0", "claim": "caller-owned-selected-workflow-only"}},
	}
	register := observeCoreEnumerations(t)
	previous := os.Getenv("CORVINT_CORE_N1_BINARY")
	for _, test := range cases {
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			document := runCoreMode(t, test.invoke, test.exit)
			register.observe(t, document)
			golden := filepath.Join("testdata", "core-freeze", strings.ReplaceAll(test.name, " ", "-")+".json")
			if os.Getenv("CORVINT_UPDATE_GOLDEN") == "1" {
				time.Sleep(1100 * time.Millisecond) // a later second gives the second fixture new commit ids
				writeCoreGolden(t, golden, mergeCoreRuns(t, "$", document, runCoreMode(t, test.invoke, test.exit)))
			}
			compareCoreGolden(t, "$", readCoreGolden(t, golden), document)
			want := map[string]any{"ok": true, "mutates": false}
			for path, value := range test.want {
				want[path] = value
			}
			checkCoreWant(t, document, want)
			if previous != "" {
				t.Run("N-1", func(t *testing.T) { replayCoreModeN1(t, previous, test.invoke, test.exit, document, want, register) })
			}
		})
	}
}

// checkCoreWant checks the CCF-V1-002 identifiers one frozen mode must carry or must omit.
func checkCoreWant(t *testing.T, document map[string]any, want map[string]any) {
	t.Helper()
	for path, value := range want {
		got, present := jsonMember(document, path)
		if _, absent := value.(absentMember); absent == present || !absent && got != value {
			t.Errorf("%s = %#v (present %v), want %#v", path, got, present, value)
		}
	}
}

// coreN1Skips names the modes the N-1 replay cannot run, and why.
var coreN1Skips = map[string]string{
	"TestCoreVerbsEmitTheFrozenProfiles/index_if_stale_when_fresh": "its setup writes the snapshot with this build, and an engine mismatch is a miss by design (CCF-V1-007 (a))",
}

// replayCoreModeN1 is the opt-in CCF-V1-007 N-1 replay (proposed, decision 0398): the N-1 release
// binary runs the same mode over a fresh fixture. It must exit alike and keep the identifiers; every
// member it emits must still be emitted here with the same JSON type; and every value it writes at a
// registered path must be in this register, so no registered value was removed or renamed.
func replayCoreModeN1(t *testing.T, binary string, invoke func(*testing.T) []string, exit int, current, want map[string]any, register *coreEnumerationObserver) {
	if reason, skipped := coreN1Skips[strings.TrimSuffix(t.Name(), "/N-1")]; skipped {
		t.Skip(reason)
	}
	var stdout, stderr bytes.Buffer
	command := exec.Command(binary, invoke(t)...)
	command.Stdout, command.Stderr = &stdout, &stderr
	var exited *exec.ExitError
	if err := command.Run(); err != nil && !errors.As(err, &exited) {
		t.Fatalf("N-1 binary %s did not run: %v", binary, err)
	}
	if code := command.ProcessState.ExitCode(); code != exit {
		t.Fatalf("N-1 exit %d, want %d, stderr=%s", code, exit, stderr.String())
	}
	var document map[string]any
	if err := json.Unmarshal(stdout.Bytes(), &document); err != nil {
		t.Fatalf("N-1 stdout is not one JSON document: %v\n%s", err, stdout.String())
	}
	checkCoreWant(t, document, want)
	register.observe(t, document)
	kinds := map[string]string{}
	coreMemberKinds("$", current, kinds)
	previous := map[string]string{}
	coreMemberKinds("$", document, previous)
	for _, path := range slices.Sorted(maps.Keys(previous)) {
		if kind, kept := kinds[path]; !kept || kind != previous[path] {
			t.Errorf("N-1 member %s (%s) is %q here: removed or retyped", path, previous[path], kind)
		}
	}
}

// coreMemberKinds records the JSON type of every member path of a document, spreading arrays as [].
func coreMemberKinds(path string, value any, kinds map[string]string) {
	kinds[path] = jsonKind(value)
	switch value := value.(type) {
	case map[string]any:
		for name, member := range value {
			coreMemberKinds(path+"."+name, member, kinds)
		}
	case []any:
		for _, element := range value {
			coreMemberKinds(path+"[]", element, kinds)
		}
	}
}

// TestCoreRefusalsKeepTheFrozenEnvelope pins CCF-V1-004 with one refusal per Core verb: a Core
// refusal exits 2 with empty stdout and one stderr JSON envelope whose ok is false and whose code
// keeps its frozen family, including the codeless repository envelope. frontier keeps its frozen
// frontier-error/0 document, and dogfood carries the top-level code beside its error object.
func TestCoreRefusalsKeepTheFrozenEnvelope(t *testing.T) {
	t.Parallel()
	cases := []struct {
		verb, name string
		arguments  func(string) []string
		code       string
		// profile, when set, is the frontier-error/0 document: exactly code and profile.
		profile string
	}{
		{"init", "init with an unrecognized argument", func(root string) []string { return []string{"--root", root, "init", "--bogus"} }, "invalid-arguments", ""},
		{"adopt", "adopt with an unrecognized argument", func(root string) []string { return []string{"--root", root, "adopt", "--bogus"} }, "invalid-arguments", ""},
		{"index", "index with an unrecognized argument", func(root string) []string { return []string{"--root", root, "index", "--bogus"} }, "invalid-arguments", ""},
		{"query", "query without a task", func(root string) []string { return []string{"--root", root, "query"} }, "invalid-arguments", ""},
		{"context", "context without a task", func(root string) []string { return []string{"--root", root, "context"} }, "invalid-arguments", ""},
		{"impact", "impact of an untracked path", func(root string) []string { return []string{"--root", root, "impact", "pkg/absent.go"} }, "", ""},
		{"affected", "affected with an abbreviated base", func(root string) []string { return []string{"--root", root, "affected", "--base", "abc1234"} }, "invalid-arguments", ""},
		{"prove", "prove with an abbreviated base", func(root string) []string { return []string{"--root", root, "prove", "--base", "abc1234"} }, "unsupported-impact-range", ""},
		{"cem", "cem status without a map", func(root string) []string { return []string{"--root", root, "cem", "status"} }, "invalid-arguments", ""},
		{"ocm", "ocm status without a map", func(root string) []string { return []string{"--root", root, "ocm", "status"} }, "invalid-arguments", ""},
		{"frontier", "frontier without its maps", func(root string) []string { return []string{"--root", root, "frontier", "--json"} }, "invalid-frontier-input", "frontier-error/0"},
		{"dogfood", "dogfood status with a malformed session key", func(root string) []string {
			return []string{"--root", root, "dogfood", "status", "--session-key", "k"}
		}, "invalid-session-key", ""},
	}
	covered := []string{}
	for _, test := range cases {
		covered = append(covered, test.verb)
		t.Run(test.name, func(t *testing.T) {
			t.Parallel()
			root := impactCLIRepository(t)
			code, stdout, stderr := runCLI(t, test.arguments(root)...)
			if code != 2 || stdout != "" {
				t.Fatalf("exit %d stdout %q, want 2 and empty", code, stdout)
			}
			var envelope map[string]any
			if err := json.Unmarshal([]byte(stderr), &envelope); err != nil || strings.Count(strings.TrimSpace(stderr), "\n") != 0 {
				t.Fatalf("stderr is not one JSON line: %v\n%s", err, stderr)
			}
			if test.profile != "" {
				if len(envelope) != 2 || envelope["code"] != test.code || envelope["profile"] != test.profile {
					t.Fatalf("envelope %v, want exactly code %q and profile %q", envelope, test.code, test.profile)
				}
				return
			}
			if envelope["ok"] != false || envelope["error"] == nil {
				t.Fatalf("envelope %v lacks ok=false and error", envelope)
			}
			got, present := envelope["code"]
			if test.code == "" && present || test.code != "" && got != test.code {
				t.Fatalf("code = %#v (present %v), want %q", got, present, test.code)
			}
		})
	}
	if !slices.Equal(covered, frozenCoreVerbs) {
		t.Errorf("refusal cases cover %v, want one per Core verb %v", covered, frozenCoreVerbs)
	}
}

// coreRootRefusal runs one Core verb without --root from directory in a fresh process and
// decodes its one-line stderr refusal.
func coreRootRefusal(t *testing.T, directory string, arguments ...string) map[string]any {
	t.Helper()
	command := candidateCommand(arguments...)
	command.Dir = directory
	var stdout, stderr strings.Builder
	command.Stdout, command.Stderr = &stdout, &stderr
	err := command.Run()
	var exit *exec.ExitError
	if !errors.As(err, &exit) || exit.ExitCode() != 2 || stdout.Len() != 0 {
		t.Fatalf("%v: %v stdout %q stderr %s, want exit 2 and empty stdout", arguments, err, stdout.String(), stderr.String())
	}
	var envelope map[string]any
	if err := json.Unmarshal([]byte(stderr.String()), &envelope); err != nil {
		t.Fatalf("%v: stderr is not one JSON document: %v\n%s", arguments, err, stderr.String())
	}
	return envelope
}

// coreRootRefusingVerbs are the Core modes that read the repository at the working directory
// when --root is omitted.
var coreRootRefusingVerbs = [][]string{
	{"index"}, {"query", "--task", "fix login"}, {"context", "--task", "fix login"}, {"impact", "pkg/main.go"},
	{"affected"}, {"prove", "pkg/main.go"}, {"dogfood", "status", "--session-key", strings.Repeat("a", 64)},
}

// TestCoreVerbsRefuseAWorkingDirectoryOutsideTheRootAlike pins CCF-V1-004: with --root omitted,
// a subdirectory of a repository and a directory outside any repository are each refused with
// the same invalid-arguments diagnostic by every Core verb that reads the repository, and the
// subdirectory refusal names the top level instead of claiming no repository exists.
func TestCoreVerbsRefuseAWorkingDirectoryOutsideTheRootAlike(t *testing.T) {
	t.Parallel()
	root := impactCLIRepository(t)
	topLevel, err := filepath.EvalSymlinks(root)
	if err != nil {
		t.Fatal(err)
	}
	outside := t.TempDir()
	for _, arguments := range coreRootRefusingVerbs {
		t.Run(arguments[0], func(t *testing.T) {
			t.Parallel()
			nested := coreRootRefusal(t, filepath.Join(root, "pkg"), arguments...)
			message, _ := nested["error"].(string)
			named, _ := strings.CutPrefix(message, "not the repository root; top level is ")
			if resolved, _ := filepath.EvalSymlinks(named); nested["code"] != "invalid-arguments" || resolved != topLevel {
				t.Errorf("subdirectory refusal %v, want invalid-arguments naming top level %s", nested, topLevel)
			}
			absent := coreRootRefusal(t, outside, arguments...)
			message, _ = absent["error"].(string)
			if absent["code"] != "invalid-arguments" || !strings.HasPrefix(message, "not a Git repository: ") {
				t.Errorf("outside refusal %v, want invalid-arguments not a Git repository", absent)
			}
			for _, envelope := range []map[string]any{nested, absent} {
				if fixes, _ := envelope["supported_fixes"].([]any); len(fixes) != 1 || fixes[0] != "cli.use-git-repository-root" {
					t.Errorf("supported_fixes = %v, want [cli.use-git-repository-root]", envelope["supported_fixes"])
				}
			}
		})
	}
}

// TestIndexedCoreVerbsCodeAnUnbornHead pins CCF-V1-004: a repository with no commit yet is
// refused with the coded repository-head-unborn diagnostic, not the codeless Git error text.
func TestIndexedCoreVerbsCodeAnUnbornHead(t *testing.T) {
	t.Parallel()
	root := t.TempDir()
	affectedGit(t, root, "init", "-q")
	if err := os.WriteFile(filepath.Join(root, "main.go"), []byte("package main\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	affectedGit(t, root, "add", "main.go")
	for _, arguments := range [][]string{{"index"}, {"query", "--task", "fix login"}, {"context", "--task", "fix login"}, {"impact", "main.go"}, {"prove", "main.go"}} {
		t.Run(arguments[0], func(t *testing.T) {
			t.Parallel()
			code, stdout, stderr := runCLI(t, append([]string{"--root", root}, arguments...)...)
			var envelope map[string]any
			if err := json.Unmarshal([]byte(stderr), &envelope); err != nil || code != 2 || stdout != "" {
				t.Fatalf("exit %d stdout %q stderr %s, want 2, empty stdout and one JSON line", code, stdout, stderr)
			}
			fixes, _ := envelope["supported_fixes"].([]any)
			if envelope["code"] != "repository-head-unborn" || len(fixes) != 1 || fixes[0] != "git.create-head-commit" {
				t.Fatalf("envelope %v, want repository-head-unborn with git.create-head-commit", envelope)
			}
		})
	}
}

var maturityLabel = regexp.MustCompile(`([a-z][a-z-]*) \(([A-Z][A-Z0-9-]*)\)`)

// TestRootHelpLabelsEveryVerbWithMaturityAndOwner pins CCF-V1-008: root help names exactly the
// frozen Core verbs, and labels every other dispatched verb experimental with an owning spec
// prefix that docs/specs/INDEX.json indexes, so no companion or research verb is frozen by omission.
func TestRootHelpLabelsEveryVerbWithMaturityAndOwner(t *testing.T) {
	t.Parallel()
	section, found := strings.CutPrefix(rootHelp[strings.Index(rootHelp, "\nCommand maturity:\n")+1:], "Command maturity:\n")
	if !found {
		t.Fatal("root help has no Command maturity section")
	}
	section, _, _ = strings.Cut(section, "\n\n")
	core, experimental, found := strings.Cut(section, "  Experimental, no stability promise;")
	if !found {
		t.Fatalf("maturity section has no experimental block:\n%s", section)
	}
	coreVerbs := []string{}
	for _, line := range strings.Split(core, "\n") {
		if strings.HasPrefix(line, "    ") {
			coreVerbs = append(coreVerbs, strings.TrimSpace(line))
		}
	}
	if got := strings.Split(strings.Join(coreVerbs, " "), ", "); !slices.Equal(got, frozenCoreVerbs) {
		t.Fatalf("Core verbs = %q, want %q", got, frozenCoreVerbs)
	}

	raw, err := os.ReadFile(filepath.Join(moduleRoot(t), "docs", "specs", "INDEX.json"))
	if err != nil {
		t.Fatal(err)
	}
	var entries []struct {
		ReqPrefix string `json:"reqPrefix"`
	}
	if err := json.Unmarshal(raw, &entries); err != nil {
		t.Fatal(err)
	}
	indexed := map[string]bool{}
	for _, entry := range entries {
		indexed[entry.ReqPrefix] = true
	}
	if !indexed["CCF-V1"] {
		t.Error("the Core contract prefix CCF-V1 is not indexed")
	}

	labelled := map[string]string{}
	for _, match := range maturityLabel.FindAllStringSubmatch(experimental, -1) {
		if _, repeated := labelled[match[1]]; repeated {
			t.Errorf("verb %q is labelled twice", match[1])
		}
		labelled[match[1]] = match[2]
		if !indexed[match[2]] {
			t.Errorf("verb %q names owner %q, which docs/specs/INDEX.json does not index", match[1], match[2])
		}
	}
	for _, command := range topLevelCommands {
		_, isExperimental := labelled[command]
		if slices.Contains(frozenCoreVerbs, command) == isExperimental {
			t.Errorf("verb %q must be exactly one of Core or labelled experimental", command)
		}
	}
	if len(labelled)+len(frozenCoreVerbs) != len(topLevelCommands) {
		t.Errorf("%d labelled + %d Core verbs, want the %d dispatched verbs", len(labelled), len(frozenCoreVerbs), len(topLevelCommands))
	}
}

var preDispatchVerb = regexp.MustCompile(`arguments\[0\] == "([a-z][a-z-]*)"`)

// TestOnlyThePinnedHookPlumbingVerbsBypassRootHelp pins CCF-V1-003 and CCF-V1-008: the verbs
// runContext compares literally are either listed in topLevelCommands, and so labelled in root
// help, or exactly the three hook-plumbing verbs, which stay out of root help and outside the freeze.
// A fourth verb dispatched this way fails here until it is listed or deliberately pinned.
func TestOnlyThePinnedHookPlumbingVerbsBypassRootHelp(t *testing.T) {
	t.Parallel()
	source, err := os.ReadFile("main.go")
	if err != nil {
		t.Fatal(err)
	}
	_, body, found := strings.Cut(string(source), "\nfunc runContext(")
	if !found {
		t.Fatal("main.go has no runContext")
	}
	body, _, _ = strings.Cut(body, "\n}\n")
	unlisted := []string{}
	for _, match := range preDispatchVerb.FindAllStringSubmatch(body, -1) {
		if !slices.Contains(topLevelCommands, match[1]) {
			unlisted = append(unlisted, match[1])
		}
	}
	if !slices.Equal(unlisted, hookPlumbingVerbs) {
		t.Fatalf("runContext dispatches unlisted verbs %q, want exactly the pinned plumbing %q", unlisted, hookPlumbingVerbs)
	}
	for _, verb := range hookPlumbingVerbs {
		if strings.Contains(rootHelp, verb) {
			t.Errorf("plumbing verb %q appears in root help", verb)
		}
	}
}

// coreEnumeration is one row of the CCF-V1-007 (d) frozen enumeration register.
type coreEnumeration struct {
	member string
	tools  []string
	values []string
	status string
}

// coreEnumerationObserver checks every string a frozen Core mode emits at a registered member
// against the register row the spec states, and records which rows some mode reached.
type coreEnumerationObserver struct {
	rows    []coreEnumeration
	mu      sync.Mutex
	reached map[int]bool
}

var registerCell = regexp.MustCompile("`([^`]+)`")

// coreEnumerationRegister reads the register table from CCF-V1-007 (d) in the Core contract, the
// single statement of every frozen enumeration, its values and its closed or open status.
func coreEnumerationRegister(t *testing.T) []coreEnumeration {
	t.Helper()
	raw, err := os.ReadFile(filepath.Join(moduleRoot(t), "docs", "specs", "core-compatibility-freeze-v1.md"))
	if err != nil {
		t.Fatal(err)
	}
	_, clause, _ := strings.Cut(string(raw), "- **CCF-V1-007:**")
	clause, _, _ = strings.Cut(clause, "- **CCF-V1-008:**")
	rows := []coreEnumeration{}
	for _, line := range strings.Split(clause, "\n") {
		cells := strings.Split(strings.TrimSpace(line), " | ")
		if len(cells) != 5 || !strings.HasPrefix(cells[0], "| `") {
			continue
		}
		row := coreEnumeration{member: strings.Trim(cells[0], "| `"), status: cells[3]}
		for _, match := range registerCell.FindAllStringSubmatch(cells[1], -1) {
			row.tools = append(row.tools, match[1])
		}
		for _, match := range registerCell.FindAllStringSubmatch(cells[2], -1) {
			row.values = append(row.values, match[1])
		}
		if row.status != "closed" && row.status != "open" || len(row.tools) == 0 || len(row.values) == 0 {
			t.Fatalf("malformed CCF-V1-007 register row: %s", line)
		}
		rows = append(rows, row)
	}
	if len(rows) == 0 {
		t.Fatal("CCF-V1-007 has no frozen enumeration register")
	}
	return rows
}

// observeCoreEnumerations pins CCF-V1-007 (d) and the CCF-V1-006 enumeration rule: a value outside
// its register row fails the observing mode, and once every mode has run, a row no mode reached
// fails the parent test, so the register cannot list a member the frozen modes never emit.
func observeCoreEnumerations(t *testing.T) *coreEnumerationObserver {
	t.Helper()
	observer := &coreEnumerationObserver{rows: coreEnumerationRegister(t), reached: map[int]bool{}}
	t.Cleanup(func() {
		for index, row := range observer.rows {
			if !observer.reached[index] {
				t.Errorf("CCF-V1-007 register row %s (%v) is reached by no frozen Core mode", row.member, row.tools)
			}
		}
	})
	return observer
}

// provePacketTools maps the mode of the packet `prove` embeds to the tool whose register rows govern
// it (proposed, decision 0398): `prove` embeds the query or impact packet unchanged as `packet`.
var provePacketTools = map[string]string{"query": "query", "impact": "impact", "range-impact": "impact"}

func (observer *coreEnumerationObserver) observe(t *testing.T, document map[string]any) {
	t.Helper()
	tool, _ := document["tool"].(string)
	observer.observeAs(t, tool, document)
	packet, embedded := document["packet"].(map[string]any)
	if tool == "prove" && embedded {
		mode, _ := packet["mode"].(string)
		observer.observeAs(t, provePacketTools[mode], map[string]any{"context": packet})
	}
}

func (observer *coreEnumerationObserver) observeAs(t *testing.T, tool string, document map[string]any) {
	t.Helper()
	for index, row := range observer.rows {
		if !slices.Contains(row.tools, tool) {
			continue
		}
		emitted := jsonMembers(document, strings.Split(row.member, "."))
		for _, value := range emitted {
			if text, ok := value.(string); !ok || !slices.Contains(row.values, text) {
				t.Errorf("%s %s = %#v, outside the CCF-V1-007 register values %q", tool, row.member, value, row.values)
			}
		}
		if len(emitted) != 0 {
			observer.mu.Lock()
			observer.reached[index] = true
			observer.mu.Unlock()
		}
	}
}

// jsonMembers reads every value at a dotted member path, where a name ending in [] spreads over
// the elements of that array.
func jsonMembers(value any, names []string) []any {
	if len(names) == 0 {
		return []any{value}
	}
	object, ok := value.(map[string]any)
	if !ok {
		return nil
	}
	name, spread := strings.CutSuffix(names[0], "[]")
	member, present := object[name]
	if !present {
		return nil
	}
	if !spread {
		return jsonMembers(member, names[1:])
	}
	elements, _ := member.([]any)
	found := []any{}
	for _, element := range elements {
		found = append(found, jsonMembers(element, names[1:])...)
	}
	return found
}

// coreFreezeVaries prefixes a golden leaf whose value differs between two independent fixture
// builds (commit ids, temporary paths and digests over them); the golden pins its JSON type only.
const coreFreezeVaries = "<varies:"

// runCoreMode runs one frozen Core mode, checks its exit code and decodes its one JSON document.
func runCoreMode(t *testing.T, invoke func(*testing.T) []string, exit int) map[string]any {
	t.Helper()
	code, stdout, stderr := runCLI(t, invoke(t)...)
	if code != exit {
		t.Fatalf("exit %d, want %d, stderr=%s", code, exit, stderr)
	}
	var document map[string]any
	if err := json.Unmarshal([]byte(stdout), &document); err != nil {
		t.Fatalf("stdout is not one JSON document: %v\n%s", err, stdout)
	}
	return document
}

// jsonKind names the JSON type of one decoded value.
func jsonKind(value any) string {
	switch value.(type) {
	case map[string]any:
		return "object"
	case []any:
		return "array"
	case string:
		return "string"
	case float64:
		return "number"
	case bool:
		return "boolean"
	}
	return "null"
}

// mergeCoreRuns folds two independent runs of one mode into its golden (CCF-V1-002): an equal value
// stays, and a scalar that differs becomes a type placeholder. A difference in members, array length
// or type is output that cannot be frozen, and fails.
func mergeCoreRuns(t *testing.T, path string, first, second any) any {
	t.Helper()
	kind := jsonKind(first)
	if kind != jsonKind(second) {
		t.Fatalf("%s is %s in one run and %s in another: not deterministic, cannot freeze", path, kind, jsonKind(second))
	}
	switch kind {
	case "object":
		return mergeCoreObjects(t, path, first.(map[string]any), second.(map[string]any))
	case "array":
		return mergeCoreArrays(t, path, first.([]any), second.([]any))
	}
	if first == second && !slices.Contains(coreExecutableMembers, path) {
		return first
	}
	return coreFreezeVaries + kind + ">"
}

// coreExecutableMembers carry a digest of the running executable, which changes with every build of
// the test binary, so their goldens pin the JSON type only.
var coreExecutableMembers = []string{"$.engine"}

func mergeCoreObjects(t *testing.T, path string, first, second map[string]any) map[string]any {
	t.Helper()
	names := slices.Sorted(maps.Keys(first))
	if !slices.Equal(names, slices.Sorted(maps.Keys(second))) {
		t.Fatalf("%s has members %q in one run and %q in another: not deterministic, cannot freeze", path, names, slices.Sorted(maps.Keys(second)))
	}
	merged := make(map[string]any, len(first))
	for _, name := range names {
		merged[name] = mergeCoreRuns(t, path+"."+name, first[name], second[name])
	}
	return merged
}

func mergeCoreArrays(t *testing.T, path string, first, second []any) []any {
	t.Helper()
	if len(first) != len(second) {
		t.Fatalf("%s has %d elements in one run and %d in another: not deterministic, cannot freeze", path, len(first), len(second))
	}
	merged := make([]any, len(first))
	for index := range first {
		merged[index] = mergeCoreRuns(t, fmt.Sprintf("%s[%d]", path, index), first[index], second[index])
	}
	return merged
}

// writeCoreGolden writes a merged golden as indented JSON with sorted members.
func writeCoreGolden(t *testing.T, path string, golden any) {
	t.Helper()
	var buffer bytes.Buffer
	encoder := json.NewEncoder(&buffer)
	encoder.SetEscapeHTML(false)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(golden); err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(path, buffer.Bytes(), 0o644); err != nil {
		t.Fatal(err)
	}
}

func readCoreGolden(t *testing.T, path string) any {
	t.Helper()
	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("%v: every frozen Core mode needs a golden; generate it with CORVINT_UPDATE_GOLDEN=1", err)
	}
	var golden any
	if err := json.Unmarshal(data, &golden); err != nil {
		t.Fatalf("%s: %v", path, err)
	}
	return golden
}

// compareCoreGolden reports every structural or value difference between a frozen mode's document
// and its golden. A placeholder leaf pins only the JSON type.
func compareCoreGolden(t *testing.T, path string, golden, got any) {
	t.Helper()
	placeholder, _ := golden.(string)
	if strings.HasPrefix(placeholder, coreFreezeVaries) {
		golden = strings.TrimSuffix(strings.TrimPrefix(placeholder, coreFreezeVaries), ">")
		if jsonKind(got) != golden {
			t.Errorf("%s is %s, the golden pins %s: retyping is breaking under CCF-V1-006", path, jsonKind(got), golden)
		}
		return
	}
	if jsonKind(got) != jsonKind(golden) {
		t.Errorf("%s is %s, the golden has %s: retyping is breaking under CCF-V1-006", path, jsonKind(got), jsonKind(golden))
		return
	}
	switch golden := golden.(type) {
	case map[string]any:
		compareCoreObjects(t, path, golden, got.(map[string]any))
	case []any:
		compareCoreArrays(t, path, golden, got.([]any))
	default:
		if got != golden {
			t.Errorf("%s = %#v, the golden has %#v", path, got, golden)
		}
	}
}

func compareCoreObjects(t *testing.T, path string, golden, got map[string]any) {
	t.Helper()
	for name, value := range golden {
		member, present := got[name]
		if !present {
			t.Errorf("%s.%s is missing: removing or renaming a member is breaking under CCF-V1-006", path, name)
			continue
		}
		compareCoreGolden(t, path+"."+name, value, member)
	}
	for name := range got {
		if _, known := golden[name]; !known {
			t.Errorf("%s.%s is not in the golden: an optional member is compatible under CCF-V1-006 but the same change regenerates the golden (CORVINT_UPDATE_GOLDEN=1)", path, name)
		}
	}
}

func compareCoreArrays(t *testing.T, path string, golden, got []any) {
	t.Helper()
	if len(got) != len(golden) {
		t.Errorf("%s has %d elements, the golden has %d", path, len(got), len(golden))
		return
	}
	for index := range golden {
		compareCoreGolden(t, fmt.Sprintf("%s[%d]", path, index), golden[index], got[index])
	}
}
